### ISSUE TITLE
[Performance] gRPC instrumentation: interceptor causes full payload to marshal into memory

### ISSUE THREAD

**Issue by a-feld** [open-telemetry/opentelemetry-go-contrib#1028]
[This call causes the proto to get marshalled into memory](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/be89a1bdcc5b8696c914688b3c5c0e2d9e45ee84/instrumentation/google.golang.org/grpc/otelgrpc/interceptor.go#L52)

Stack Trace:
```
go.opentelemetry.io/collector/model/internal/data/protogen/collector/metrics/v1.(*ExportMetricsServiceRequest).Marshal (opentelemetry-collector/model/internal/data/protogen/collector/metrics/v1/metrics_service.pb.go:238)
google.golang.org/protobuf/internal/impl.legacyMarshal (google.golang.org/protobuf@v1.27.1/internal/impl/legacy_message.go:404)
google.golang.org/protobuf/proto.MarshalOptions.size (google.golang.org/protobuf@v1.27.1/proto/size.go:43)
google.golang.org/protobuf/proto.MarshalOptions.Size (google.golang.org/protobuf@v1.27.1/proto/size.go:26)
google.golang.org/protobuf/proto.Size (google.golang.org/protobuf@v1.27.1/proto/size.go:16)
github.com/golang/protobuf/proto.Size (github.com/golang/protobuf@v1.5.2/proto/wire.go:18)
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.messageType.Event (go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.21.0/interceptor.go:52)
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1 (go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.21.0/interceptor.go:336)
go.opentelemetry.io/collector/model/internal/data/protogen/collector/metrics/v1._MetricsService_Export_Handler (opentelemetry-collector/model/internal/data/protogen/collector/metrics/v1/metrics_service.pb.go:218)
google.golang.org/grpc.(*Server).processUnaryRPC (google.golang.org/grpc@v1.39.0/server.go:1292)
google.golang.org/grpc.(*Server).handleStream (google.golang.org/grpc@v1.39.0/server.go:1617)
google.golang.org/grpc.(*Server).serveStreams.func1.2 (google.golang.org/grpc@v1.39.0/server.go:940)
runtime.goexit (/usr/local/Cellar/go/1.17/libexec/src/runtime/asm_amd64.s:1581)
```

Calling `proto.size()` from `go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.messageType.Event` leads to the full payload being marshalled in memory. This ultimately leads to garbage getting created on each request.

**Comment by MrAlias** [comment]
Do you have a proposed solution?

Based on [the specification](https://github.com/open-telemetry/opentelemetry-specification/blob/028ac126af850e7fd31a16e93372b160448a068b/specification/trace/semantic_conventions/rpc.md#events) this event should be annotated the way it currently is. I do not know of another way to get the uncompressed request payload size without calling the function we are calling. I'm interested to know know what you had in mind here.

**Comment by a-feld** [comment]
I'm looking into it right now 😄 
I think the solution here may have to be in the collector protos. [It looks like there's a fast path if there's a size method available](https://github.com/protocolbuffers/protobuf-go/blob/5aec41b4809b9822a34e17acd06ae9ae9f41c13d/proto/size.go#L34)

**Comment by a-feld** [comment]
I'm also wondering if there's a way to omit this parameter if we can detect if we have to go on the slow path?

**Comment by jack-berg** [comment]
I ran this in debug mode. The [fast path](https://github.com/protocolbuffers/protobuf-go/blob/5aec41b4809b9822a34e17acd06ae9ae9f41c13d/proto/size.go#L34) @a-feld mentioned doesn't called because there's logic which normalizes proto v1 and v2 messages as v2 messages. The the otel protos (like `ExportTraceServiceRequest`) get [wrapped in a legacy message](https://github.com/protocolbuffers/protobuf-go/blob/v1.27.1/internal/impl/api_export.go#L134) because they qualify as v1 messages [here](https://github.com/protocolbuffers/protobuf-go/blob/v1.27.1/internal/impl/api_export.go#L118-L119). 

This causes the reflection to fail to resolve that a `Size` method exists, and the slow path to be taken rather than the fast path.
