### ISSUE TITLE
Don't send all requests

### ISSUE THREAD

**Issue by HammerMeetNail** [open-telemetry/opentelemetry-go-contrib#1087]
Hey folks,

Just integrated [otelgin](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation/github.com/gin-gonic/gin/otelgin) and am able to send metrics to Honeycomb. By default it forwards on all requests. Does anyone know if there's a way to prevent certain endpoints from sending? We have a healthcheck endpoint that doesn't need to be pushed. 

Thanks,
Dave

**Comment by MrAlias** [comment]
Would using [`RouterGroup`](https://pkg.go.dev/github.com/gin-gonic/gin#RouterGroup)s work for you?

You could split your healthcheck and other routes into different groups and only register the tracing middleware with the other routes group. Something like in [the example](https://github.com/gin-gonic/examples/tree/master/group-routes).

**Comment by flc1125** [comment]
In addition to MrAlias' solution, there are two other ways to solve it.

```go
package main

import (
	"net/http"

	"github.com/gin-gonic/gin"

	"go.opentelemetry.io/contrib/instrumentation/github.com/gin-gonic/gin/otelgin"
)

func main() {
	router := gin.New()

	router.Use(otelgin.Middleware("my-server",
		// way 1: use request filter
		otelgin.WithFilter(func(request *http.Request) bool {
			return request.URL.Path != "/health"
		}),

		// way 2: use gin filter
		otelgin.WithGinFilter(func(c *gin.Context) bool {
			return c.Request.URL.Path != "/health"
		}),
	))

	if err := router.Run(":8080"); err != nil {
		panic(err)
	}
}
```

**Comment by dmathieu** [comment]
Closing, as this is a question that now got two different answers. @HammerMeetNail feel free to reopen if none of the answer works for you.
