### ISSUE TITLE
statusCode Return :UNSET,  statusMessage return Empty

### ISSUE THREAD

**Issue by toniz** [open-telemetry/opentelemetry-go-contrib#1088]
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/f650585d08df31ecbdec0b22f3778bdd7da1dedd/instrumentation/net/http/otelhttp/handler.go#L209

**Comment by MrAlias** [comment]
It is not clear to me what this issue's topic is.

If this is still an issue can you reopen this and include information about what this is for, the environment being run in, sample code producing the issue you are describing, and the expected behavior you thought you would see?

E.g.

```
### Description

A clear and concise description of what the bug is.

### Environment

- OS: [e.g. iOS]
- Architecture: [e.g. x86, i386]
- Go Version: [e.g. 1.15]
- opentelemetry-go-contrib version: [e.g. v0.14.0, 3c7face]

### Steps To Reproduce

1. Use the configuration '...'
2. Run '...'
3. See error

### Expected behavior

A clear and concise description of what you expected to happen.
```
