### ISSUE TITLE
Add `WithTracerProvider()` to  the `net/http/httptrace` package

### ISSUE THREAD

**Issue by erichsueh3** [open-telemetry/opentelemetry-go-contrib#1105]
## Background

Currently, the `net/http/httptrace` package is missing a `WithTracerProvider()` function.

## Proposed Solution

Add in a `WithTracerProvider()` function. The `config` struct would also need to be modified to include 
`tracerProvider trace.TracerProvider`.

**Comment by erichsueh3** [comment]
Would a test for the `WithTracerProvider()` function be necessary? Not sure how much value it adds due to the simplicity of the function.

**Comment by yeya24** [comment]
This issue can be closed in favor of https://github.com/open-telemetry/opentelemetry-go-contrib/pull/1128.

**Comment by MrAlias** [comment]
Closed in #1128
