### ISSUE TITLE
Update instrumentation readme to include links to instrumentation in external repos

### ISSUE THREAD

**Issue by reggiemcdonald** [open-telemetry/opentelemetry-go-contrib#116]
As per discussion with @MrAlias, we agreed that the readme in the instrumentation directory should be updated to include links to integrations that are not in the opentelemetry-go-contrib repo.

@TigerHe7 and I found that [go-redis/go](https://github.com/go-redis/redis) already contains an integration for opentelemetry. 

This issue is to update the readme with a table including a link to that repo.

**Comment by evantorrie** [comment]
I checked https://opentelemetry.io/registry/ and the `go-redis/go` OTel integration does not appear there either. Should we take it upon ourselves to add this to the registry? Or expect the go-redis maintainers to do so?

**Comment by MrAlias** [comment]
> I checked https://opentelemetry.io/registry/ and the `go-redis/go` OTel integration does not appear there either. Should we take it upon ourselves to add this to the registry? Or expect the go-redis maintainers to do so?

Probably worth doing ourselves given the newness of things. That said I know @vmihailenco has contributed to OTel already and might be interested in registering it.
