### ISSUE TITLE
Implement an Exporter for Cortex

### ISSUE THREAD

**Issue by connorlindsey** [open-telemetry/opentelemetry-go-contrib#119]
We (@alolita, @ercl, @connorlindsey) are interested in developing a push-based exporter, sending metrics data to a [Cortex](https://cortexmetrics.io/) instance for supporting scalable metrics storage and processing. 

We plan to provide a detailed design document for review, code and tests to support this implementation. Please assign this issue to us for implementation. You can assign it to @alolita since we’re still in the process of becoming members.

We also request a mentor from the Go SDK maintainer team for this project for design and code review and guidance.

Filed by: @connorlindsey
Assigned to: @alolita

**Comment by MrAlias** [comment]
This looks complete. Going to close. Please feel free to reopen if needed.
