### ISSUE TITLE
Add instrumentation for gqlgen: github.com/99designs/gqlgen

### ISSUE THREAD

**Issue by rot1024** [open-telemetry/opentelemetry-go-contrib#126]
It seems that there is no instrumentation library for [gqlgen](https://github.com/99designs/gqlgen) for now.

## Tasks

- [ ] code complete with tests passing
- [ ] `Dockerfile` with example app showing instrumentation
- [ ] documentation updated
- [ ] instrumentation added to the opentelemetry [registry](https://opentelemetry.io/registry/)

## Prior Art

Reference: https://github.com/rot1024/otelgqlgen (Created for experimental)

**Comment by MrAlias** [comment]
@rot1024 https://github.com/rot1024/otelgqlgen returns a 404 when I try to access it. Does it need to be made public?

**Comment by rot1024** [comment]
Sorry, I have made it public.

**Comment by rot1024** [comment]
https://github.com/99designs/gqlgen-contrib/tree/master/gqlopencensus is available, so I think this issue is no longer needed.
