### ISSUE TITLE
`otelhttp.Transport` is unable to properly handle protocol switching (e.g. for websockets)

### ISSUE THREAD

**Issue by djcass44** [open-telemetry/opentelemetry-go-contrib#1329]
Attempting to proxy a websocket through the `otelhttp.Transport` returns a 502 and this message: `http: proxy error: internal error: 101 switching protocols response with non-writable body`. 

It may also affect H2C connections (and anything that provides write access to the underlying TCP connection) as stated by the [Go source](https://go-review.googlesource.com/c/go/+/131279/4/src/net/http/transport.go#1862).

---

The smallest possible fix I could think of was this: https://github.com/djcass44/opentelemetry-go-contrib/commit/3f58f5c72838e1d58b42444ad73dc8583c9eb5fd which disables the wrapping of the response body if the http response code is `101`

This feels like a hack, however it does work. Have you got any thoughts on an optimal implementation?

**Comment by mhahl** [comment]
Hey,

Is there any progress of fixing this issue? It's super annoying, having to work around it using @djcass44 fix.

Thanks!
