### ISSUE TITLE
OTel HTTP server duration microseconds instead of milliseconds

### ISSUE THREAD

**Issue by victoraugustolls** [open-telemetry/opentelemetry-go-contrib#1335]
Hi! According to the [specs](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md), shouldn't `http.server.duration` be in milliseconds instead of microseconds?

If I understood correctly, the current `otelhttp` implementation is using `microseconds` instead (see [here](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/1412a89570649ed3cea04d6b0598e913ac9018b8/instrumentation/net/http/otelhttp/common.go#L36)).

If that's the case, would it be ok for me to open a PR changing it?

Thanks in advance!

**Comment by MrAlias** [comment]
Closed by https://github.com/open-telemetry/opentelemetry-go-contrib/pull/1537
