### ISSUE TITLE
Add Instrumentation (metric) for net/http

### ISSUE THREAD

**Issue by victoraugustolls** [open-telemetry/opentelemetry-go-contrib#1336]
## Background

**Package Link**: `net/http`

stdlib http client.

## Proposed Solution

Collect `http.client.duration` metric from the stdlib http client. Currently I'm using a custom `RoundTripper` that calls the `otelhttp` tracing `RoundTripper`, and I think it would be nice if this was inside the contrib. If agreed, I can open a PR for it!

I see something similar was done in #427 , but it was unfortunately closed! That makes me think that this might not be desired? This is why I'm asking in advance. Thanks!

### Metrics

Instruments

- http.client.duration: measure the duration of the outbound HTTP request
  - type: Histogram
  - unit: milliseconds
  - description: measure the duration of the outbound HTTP request

### Prior Art

- This is a metric defined in the [specs](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md#http-client). Previous PR here: #427 .

## Tasks

- Code complete:
  - [ ] Comprehensive unit tests.
  - [ ] End-to-end integration tests.
  - [ ] Tests all passing.
  - [ ] Instrumentation functionality verified.
- Documented
  - [ ] Added to the [OpenTelemetry Registry](https://opentelemetry.io/registry/)
  - [ ] README included for the module describing high-level purpose.
  - [ ] Complete documentation of all public API including package documentation.
  - [ ] [Instrumentation documentation](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/README.md#instrumentation-packages) updated.
- Examples
  - [ ] `Dockerfile` file to build example application.
  - [ ] `docker-compose.yml` to run example in a docker environment to demonstrate instrumentation.

**Comment by tonglil** [comment]
Personally I feel like that kind of information is critical to the instrumentation. As far as I can tell, the otelhttp instrumentation is mostly barebones at the moment and only records `HTTP GET/POST/etc`, like without parameterized http.url and http.target attributes that I feel like are needed.

Would love to see this data @victoraugustolls!
