### ISSUE TITLE
Runtime instrumentation: Make runtime.uptime an Asynchronous Gauge

### ISSUE THREAD

**Issue by cwildman** [open-telemetry/opentelemetry-go-contrib#1341]
Currently the `runtime.uptime` metric is reported as an [Asynchronous Counter](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/8e44f3f02293665b0547280bf151da43d9a8fb2a/instrumentation/runtime/runtime.go#L120-L121). Uptime as a concept is certainly monotonic which makes it seem like it should be a Counter, but it's also non-additive, it doesn't make sense to sum the uptime of different processes.

Additionally reporting uptime as a Counter presents a problem when trying to use delta temporality. The obvious question you want to answer with a metric like this is "How long has my process been running?". Using delta temporality with uptime would force you to track the running sum of all data points since the process started.

Because runtime.uptime is not additive and we don't actually care about rates or sum I think it is best served as an Asynchronous Gauge.

**Comment by krak3n** [comment]
In the prometheus exporter in [open-telemetry/opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusexporter) this metric fails to get exported due to this error:

```
{
   "level":"error",
   "ts":1659451541.6164072,
   "caller":"prometheusexporter@v0.53.0/log.go:34",
   "msg":"error gathering metrics: collected metric runtime_uptime counter:<value:8.415e+07 >  should be a Gauge\n",
   "kind":"exporter",
   "name":"prometheus",
   "stacktrace":"github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*promLogger).Println\n\tgithub.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.53.0/log.go:34\ngithub.com/prometheus/client_golang/prometheus/promhttp.HandlerFor.func1\n\tgithub.com/prometheus/client_golang@v1.12.2/prometheus/promhttp/http.go:129\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2084\nnet/http.(*ServeMux).ServeHTTP\n\tnet/http/server.go:2462\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:2916\nnet/http.(*conn).serve\n\tnet/http/server.go:1966"
}
```

**Comment by starzhanganz** [comment]
Can we have someone looking into this please? The incorrect type caused high error rate while exporting the metrics to Google Cloud. It reports `runtime.uptime must be GAUGE, but is CUMULATIVE`
