### ISSUE TITLE
Update metrics exporters

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/opentelemetry-go-contrib#1478]
The metrics version V0.26.0 removes the Points aggregation and MinMaxSumCount aggregation from the API, and includes a new Histogram aggregation which is not interchangeable.  This prevented us from updating modules in the `experimental-metrics` module set.

Things that need to be addressed:

- [x] Remove the MinMaxSumCount from cortex.
- [ ] Remove Point aggregations from datadog exporter.
- [ ] Handle Histograms in the datadog exporter
- [ ] Remove Point aggregations from dogstatsd exporter.
- [ ] Handle Histograms in the dogstatsd exporter

**Comment by hanyuancheung** [comment]
I think this issue has been finished, cause with the deprecation of the datadog exporter and removal of histogram support, we don't need to spend efforts trying to handle others. Could you please help to close it?
