### ISSUE TITLE
Missing modules in 0.28.0 instrumentation release

### ISSUE THREAD

**Issue by pkwarren** [open-telemetry/opentelemetry-go-contrib#1518]
As part of upgrading dependencies to the latest opentelemetry-go and opentelemetry-go-contrib, I noticed that the go.opentelemetry.io/contrib/instrumentation/runtime@v0.27.0 module remained a version behind the others.

Scanning tags between 0.27.0 and 0.28.0, I found that these modules weren't tagged as part of the 0.28.0 release:

```diff
--- 0.27-modules	2021-12-14 11:12:31.000000000 -0600
+++ 0.28-modules	2021-12-14 11:12:40.000000000 -0600
@@ -1,9 +1,4 @@
 detectors/aws/lambda
-exporters/metric/cortex
-exporters/metric/cortex/example
-exporters/metric/cortex/utils
-exporters/metric/datadog
-exporters/metric/dogstatsd
 instrumentation/github.com/Shopify/sarama/otelsarama
 instrumentation/github.com/Shopify/sarama/otelsarama/example
 instrumentation/github.com/Shopify/sarama/otelsarama/test
@@ -46,16 +41,12 @@
 instrumentation/gopkg.in/macaron.v1/otelmacaron
 instrumentation/gopkg.in/macaron.v1/otelmacaron/example
 instrumentation/gopkg.in/macaron.v1/otelmacaron/test
-instrumentation/host
-instrumentation/host/example
 instrumentation/net/http/httptrace/otelhttptrace
 instrumentation/net/http/httptrace/otelhttptrace/example
 instrumentation/net/http/httptrace/otelhttptrace/test
 instrumentation/net/http/otelhttp
 instrumentation/net/http/otelhttp/example
 instrumentation/net/http/otelhttp/test
-instrumentation/runtime
-instrumentation/runtime/example
 propagators/opencensus
 propagators/opencensus/examples
 zpages
```

Is this expected?

**Comment by Aneurysm9** [comment]
Yes.  There were changes in the metrics API that prevent an immediate update of some of the modules in the `experimental-metrics` module set so we did not release new versions of those modules.  See https://github.com/open-telemetry/opentelemetry-go-contrib/issues/1478.  If no good solutions for the histogram expectation mismatch presented by the datadog and dogstatsd exporters are found we may need to EOL those exporters.

**Comment by pkwarren** [comment]
Is it safe to use `go.opentelemetry.io/contrib/instrumentation/runtime@v0.27.0` with other v0.28.0 otel-contrib modules and otel-go v1.3.0/0.26.0?

**Comment by MrAlias** [comment]
> Is it safe to use `go.opentelemetry.io/contrib/instrumentation/runtime@v0.27.0` with other v0.28.0 otel-contrib modules and otel-go v1.3.0/0.26.0?

If you are using a current and supported version of Go the module dependencies will be resolved independently, meaning you should not have an issue running those modules side-by-side.
