### ISSUE TITLE
Update CI to support integration tests

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-contrib#160]
In both the mongo and cassandra instrumentation the testing requires and actual database:

- https://github.com/open-telemetry/opentelemetry-go-contrib/blob/2baa89862fad76c1ed79eb74f36c9978c2a7a512/instrumentation/go.mongodb.org/mongo-driver/mongo_test.go#L33-L40
- https://github.com/open-telemetry/opentelemetry-go-contrib/pull/137#discussion_r458959469

Our current CI system does not stand any of these up so the testing is currently disabled. We should automate some form of testing to work with the CI system that supports these tests.

**Comment by reggiemcdonald** [comment]
I would be interested in getting the tests running for mongo and gocql!
