### ISSUE TITLE
Decouple instrumentation from default SDK

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-contrib#161]
Instrumentation needs to be lightweight when used. It should not have any large dependencies. However, there are multiple instrumentation packages that import the `go.opentelemetry.io/otel/sdk` package. Most common this is in examples or tests.

This dependency needs to be removed. It will likely depend on the resolution of https://github.com/open-telemetry/opentelemetry-go/issues/872.

**Comment by matej-g** [comment]
It seems now also with tracing utilities being available (https://github.com/open-telemetry/opentelemetry-go/pull/1111), nothing should be blocking this from `go.opentelemetry.io` side, right? If so I'd be happy to take it.
