### ISSUE TITLE
Update instrumentation naming conventions

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-contrib#164]
[Our instrumentation naming convention](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/master/instrumentation#packaging) is well structured to find appropriate instrumentation, but the duplication of the package name is guaranteed to cause collision with the package users are instrumenting.

### Options

1. Leave it as is and let the user deal with package naming overrides.
2. Add a suffix of `otel` to the declared `package` in the Go code, but leave the import naming (and directory structure) unchanged. This means that
   ```
   import "go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux"
   ```
   would be named
   ```
   package muxotel
   ```
3. Change the declared package name like (2), but also rename the final directory name (if it is the same as the package name) to have an `otel` suffix
   - `go.opentelemetry.io/contrib/instrumentation/runtime` -> `go.opentelemetry.io/contrib/instrumentation/runtimeotel`
   - `go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux` -> `go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/muxotel`
   - `go.opentelemetry.io/contrib/instrumentation/gopkg.in/macaron.v1` -> `go.opentelemetry.io/contrib/instrumentation/gopkg.in/macaron.v1` (doesn't change given the directory doesn't match the `macaron` package name).
4. Change the declared package name like (2), but also add an additional directory with the instrumented library package name  and a suffix of `otel`.
   - `go.opentelemetry.io/contrib/instrumentation/runtime` -> `go.opentelemetry.io/contrib/instrumentation/runtime/runtimeotel`
   - `go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux` -> `go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/muxotel`
   - `go.opentelemetry.io/contrib/instrumentation/gopkg.in/macaron.v1` -> `go.opentelemetry.io/contrib/instrumentation/gopkg.in/macaron.v1/macaronotel`

### Analysis/Recommendation

Option (1) treats this as a non-issue. From user the feedback we have received and based on the conversation in today's SIG meeting, this seems like an issue.

Option (2) benefits from slightly less verbosity in the import name, but has the downside that the import name will not match the package name. This name mismatch will be undesired by new users.

Option (3) modifies the import name possibly making it slightly less clear (if you were to do a text search for instance) of a discovery process. However, it is also slightly less verbose.

Option (4) is the most verbose.

With the primary goals being:

* Discoverability: It should be easy to search or explore the repo to find instrumentation.
* Usability: Cause the least amount of frustration to the end user or unexpected behaviour.

I think Option (4) is the correct choice. The downside of it being verbose and therefore impacting usability seems comparatively minor to the other usability issues of the other options. Especially if, as is common, tooling is used to actually write import names.

**Comment by MrAlias** [comment]
There might be a 3.a option that deals with "if it is the same as the package name" differently, but I think it still isn't the correct choice.

**Comment by Aneurysm9** [comment]
I like option 4.  Even though it is the most verbose I think it best supports discoverability and naming conflict avoidance.  I would, however, suggest moving "otel" from a suffix to a prefix.  `otelmux.Middleware()` reads better to me than `muxotel.Middleware()`, perhaps because it makes "otel" a true prefix of the entire reference rather than being stuck in the middle.

**Comment by johejo** [comment]
Question:
In Option 4, if the target module already has an import path of "foo/bar/barotel", what will it like?
I haven't seen a module like this, but it's worth considering.

**Comment by MrAlias** [comment]
> Question:
> In Option 4, if the target module already has an import path of "foo/bar/barotel", what will it be like?
> I haven't seen a module like this, but it's worth considering.

If there is a duplicate import name it would need to be resolved by the importer.

It seems like if that were the case for option (4) there would be no need to have instrumentation here as the library would have OTel support already.

**Comment by MrAlias** [comment]
> I like option 4. Even though it is the most verbose I think it best supports discoverability and naming conflict avoidance. I would, however, suggest moving "otel" from a suffix to a prefix. `otelmux.Middleware()` reads better to me than `muxotel.Middleware()`, perhaps because it makes "otel" a true prefix of the entire reference rather than being stuck in the middle.

I'm not opposed to prefix instead of suffix. The initial idea of a suffix was to follow the `*test` naming practice of standard library testing package. I'm not sure why the decision was made to use a suffix there, but I imagine we can choose our own style if we plan to remain consistent.

**Comment by MrAlias** [comment]
SIG meeting made a decision to go with:

Add a prefix of `otel` to the declared package in the Go code and also add an additional directory with the instrumented library package name. E.g.

* `go.opentelemetry.io/contrib/instrumentation/runtime` -> `go.opentelemetry.io/contrib/instrumentation/runtime/otelruntime`
* `go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux `-> `go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux`
* `go.opentelemetry.io/contrib/instrumentation/gopkg.in/macaron.v1` -> `go.opentelemetry.io/contrib/instrumentation/gopkg.in/macaron.v1/otelmacaron`

**Comment by newrelic-eheinlein** [comment]
I would be interested in working on this issue!
