### ISSUE TITLE
Setup vanity URL for this repo

### ISSUE THREAD

**Issue by krnowak** [open-telemetry/opentelemetry-go-contrib#17]
It should be `go.opentelemetry.io/contrib`, I think. With that set up, we will need to change `go.mod` files in the repo to replace `github.com/open-telemetry/opentelemetry-go-contrib` part to the vanity URL.

**Comment by lizthegrey** [comment]
I believe @rghetia is in charge of the appengine thing that does the redirect mapping.

**Comment by rghetia** [comment]
Done. https://github.com/census-ecosystem/opencensus-go-vanityurls/pull/10

<img width="150" alt="Screen Shot 2020-04-17 at 8 04 31 AM" src="https://user-images.githubusercontent.com/8052115/79583838-6e214780-8082-11ea-8445-87e1e6a12dab.png">

**Comment by rghetia** [comment]
Closed by mistake. go.mod changes are still required.

**Comment by krnowak** [comment]
Did the go.mod changes in #16.
