### ISSUE TITLE
Cannot install go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp

### ISSUE THREAD

**Issue by cedricf** [open-telemetry/opentelemetry-go-contrib#1919]
`go get` fails with:
```
go get: go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.29.0: stream error: stream ID 13; INTERNAL_ERROR
```
installing v1.4.0 also fails with:
```
go get: module go.opentelemetry.io/contrib@v1.4.0 found, but does not contain package go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp
```
Expected behaviour:
That the latest available version of the package is pulled down

My Go version info is as follows:
```
go version go1.16.2 darwin/amd64
```

**Comment by dmathieu** [comment]
I am able to properly get those packages. Could this be a connectivity issue on your end?

> go get -v go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.29.0
get "go.opentelemetry.io/contrib": found meta tag vcs.metaImport{Prefix:"go.opentelemetry.io/contrib", VCS:"git", RepoRoot:"https://github.com/open-telemetry/opentelemetry-go-contrib"} at //go.opentelemetry.io/contrib?go-get=1
get "go.opentelemetry.io/contrib/instrumentation": found meta tag vcs.metaImport{Prefix:"go.opentelemetry.io/contrib", VCS:"git", RepoRoot:"https://github.com/open-telemetry/opentelemetry-go-contrib"} at //go.opentelemetry.io/contrib/instrumentation?go-get=1
get "go.opentelemetry.io/contrib/instrumentation": verifying non-authoritative meta tag
get "go.opentelemetry.io/contrib/instrumentation/net/http": found meta tag vcs.metaImport{Prefix:"go.opentelemetry.io/contrib", VCS:"git", RepoRoot:"https://github.com/open-telemetry/opentelemetry-go-contrib"} at //go.opentelemetry.io/contrib/instrumentation/net/http?go-get=1
get "go.opentelemetry.io/contrib/instrumentation/net/http": verifying non-authoritative meta tag
get "go.opentelemetry.io/contrib/instrumentation/net": found meta tag vcs.metaImport{Prefix:"go.opentelemetry.io/contrib", VCS:"git", RepoRoot:"https://github.com/open-telemetry/opentelemetry-go-contrib"} at //go.opentelemetry.io/contrib/instrumentation/net?go-get=1
get "go.opentelemetry.io/contrib/instrumentation/net": verifying non-authoritative meta tag
get "go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp": found meta tag vcs.metaImport{Prefix:"go.opentelemetry.io/contrib", VCS:"git", RepoRoot:"https://github.com/open-telemetry/opentelemetry-go-contrib"} at //go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp?go-get=1
get "go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp": verifying non-authoritative meta tag
get "go.opentelemetry.io/otel": found meta tag vcs.metaImport{Prefix:"go.opentelemetry.io/otel", VCS:"git", RepoRoot:"https://github.com/open-telemetry/opentelemetry-go"} at //go.opentelemetry.io/otel?go-get=1
get "go.opentelemetry.io/otel/metric": found meta tag vcs.metaImport{Prefix:"go.opentelemetry.io/otel", VCS:"git", RepoRoot:"https://github.com/open-telemetry/opentelemetry-go"} at //go.opentelemetry.io/otel/metric?go-get=1
get "go.opentelemetry.io/otel/metric": verifying non-authoritative meta tag
get "go.opentelemetry.io/otel/trace": found meta tag vcs.metaImport{Prefix:"go.opentelemetry.io/otel", VCS:"git", RepoRoot:"https://github.com/open-telemetry/opentelemetry-go"} at //go.opentelemetry.io/otel/trace?go-get=1
get "go.opentelemetry.io/otel/trace": verifying non-authoritative meta tag
get "go.opentelemetry.io/otel/internal/metric": found meta tag vcs.metaImport{Prefix:"go.opentelemetry.io/otel", VCS:"git", RepoRoot:"https://github.com/open-telemetry/opentelemetry-go"} at //go.opentelemetry.io/otel/internal/metric?go-get=1
get "go.opentelemetry.io/otel/internal/metric": verifying non-authoritative meta tag

**Comment by cedricf** [comment]
I have just tried again and the package loads now.  Sorry, I would be surprised if this was a connectivity issue on my side, but it is working fine now.  
Sorry, for wasting your time.

**Comment by morigs** [comment]
I had the same problem when trying to install using `go mod tidy`.
It has successfully installed using `go get -u go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp`
