### ISSUE TITLE
grpc/http: support custom KeyValues when reporting metrics

### ISSUE THREAD

**Issue by derekperkins** [open-telemetry/opentelemetry-go-contrib#195]
We've been running OpenCensus for ~2 years and are excited to move to OpenTelemetry. The standard API has served us well, but our biggest issue with some of the wrapper packages like ocgrpc and ochttp are that they don't support custom KeyValues (TagKeys) when recording metrics. I can register my own views that include them, but because of the way that they wrap my server, I'm not passing a context that contains said values. I need this on a per request basis, to report specific error types, latency per kv, etc. 

Is that in scope for OpenTelemetry? Without it, I'm forced to copy and fork the implementation.

**Comment by derekperkins** [comment]
Any thoughts? I saw a related issue in the main ot-go repo.
https://github.com/open-telemetry/opentelemetry-go/issues/1051

**Comment by Aneurysm9** [comment]
My initial thought is perhaps to have the handler inject something into the request context that can be used to add labels:

```go
// in instrumentation
labeler := &Labeler{}
ctx = injectLabeler(ctx, labeler)
h.handler.ServeHTTP(w, r.WithContext(ctx))

setAfterServeAttributes(span, bw.read, rww.written, rww.statusCode, bw.err, rww.err)

// Add request metrics

labels := append(labeler.labels, semconv.HTTPServerMetricAttributesFromHTTPRequest(h.operation, r))
...
```

```go
// in handler
labeler := otelhttp.LabelerFromContext(r.Context())
labeler.Add(label.String("key", "value"))
```

I'll try to prototype something along these lines and see how it feels.

**Comment by derekperkins** [comment]
@Aneurysm9 thanks for the response, that looks like a much nicer api than the one I proposed. It's simple to use, minimal overhead, looks great!
