### ISSUE TITLE
Change grpc instrumentations to accept `trace.Provider` instead of `trace.Tracer`

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-go-contrib#196]
See https://github.com/open-telemetry/opentelemetry-go-contrib/blob/df4904080a5e92a40aa573a026b4108447471ec9/instrumentation/google.golang.org/grpc/interceptor.go#L65

Usually the name/version of the `trace.Tracer` is something that the instrumentation library should control, but we should allow configuring the `trace.Provider`.

**Comment by MrAlias** [comment]
Resolved by https://github.com/open-telemetry/opentelemetry-go-contrib/pull/373
