### ISSUE TITLE
Implement `grpc.StatsHandler` for grpc instrumentation

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-go-contrib#197]
See OpenCensus https://godoc.org/go.opencensus.io/plugin/ocgrpc

Much easier to use and implement, now:
```golang
s := grpc.NewServer(
		grpc.UnaryInterceptor(grpctrace.UnaryServerInterceptor(global.Tracer(""))),
		grpc.StreamInterceptor(grpctrace.StreamServerInterceptor(global.Tracer(""))),
	)
```
After:
```
s := grpc.NewServer(grpc.StatsHandler(&grpctrace.NewServerHandler(global.Tracer(""))))
```

**Comment by bakins** [comment]
I quickly implemented https://github.com/bakins/otel-grpc-statshandler as I ran into similar issues. Needs more testing, etc.

**Comment by fatsheep9146** [comment]
@MrAlias Could you assign this to me, if you do not have enough bandwidth?
Since I think #2840 now is slightly blocked by this issue, I think it is a proper time to solve this problem for now and then enrich more metric for grpc.

**Comment by vtolstov** [comment]
any news ?

**Comment by fatsheep9146** [comment]
> any news ?

@vtolstov #3002 is waiting to be merged to solve this issue
