### ISSUE TITLE
Remove replace on go.mod at next release

### ISSUE THREAD

**Issue by reggiemcdonald** [open-telemetry/opentelemetry-go-contrib#208]
The `net/http` instrumentation, and the (not yet merged) `astaxie/beego` instrumentation both use a `replace` in the go.mod to use the mock meter for unit tests. This is because `internal/metric` is not in the most recent release of contrib. 

This ticket is to remove the replace from the go mods at the next release.

**Comment by evantorrie** [comment]
As you observed, the `replace go.opentelemetry.io/contrib => ../../../..` directive in a submodule's `go.mod` is necessary only when the submodule's code depends on a new addition/change in the top-level `go.opentelemetry.io/contrib` module. 

Admittedly, that is likely to become more rare as the code base stabilizes, but https://github.com/open-telemetry/opentelemetry-go-contrib/issues/214#issuecomment-673747126 implies that this will indeed happen again soon with its suggestion of a constant `version` introduced into the "top-level repository".

Perhaps implementation of this ticket should be postponed to a GA release, and from then on, replaces directives introduced only when required for a particular module.

**Comment by MrAlias** [comment]
Closing, stale.
