### ISSUE TITLE
Release v0.10.1

### ISSUE THREAD

**Issue by lizthegrey** [open-telemetry/opentelemetry-go-contrib#212]
It'd be helpful to let -go-contrib evolve a little faster than -go, so that for instance people can migrate in advance to the moved othttp instrumentation instead of having things be temporarily broken between v0.11 of -go and -go-contrib being released. Thoughts?

**Comment by MrAlias** [comment]
Seems reasonable to me :+1:

**Comment by lizthegrey** [comment]
Not actually blocking for me, it turns out https://pkg.go.dev/mod/go.opentelemetry.io/contrib/instrumentation/net/http@v0.0.0-20200813041938-b948cd370862 will work fine, but ideally still it'd be tagged with v0.10.1

**Comment by MrAlias** [comment]
Looking to merge PRs that are ready and then get this out.
