### ISSUE TITLE
how about add an option for otelmongo: do not treat mongo.ErrNoDocuments   as error 

### ISSUE THREAD

**Issue by jixiuf** [open-telemetry/opentelemetry-go-contrib#2139]
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/go.mongodb.org/mongo-driver/mongo/otelmongo/mongo.go#L103

**Comment by Aneurysm9** [comment]
I think this is very similar to the discussion around whether to treat [HTTP 404 responses as errors](https://github.com/open-telemetry/opentelemetry-specification/pull/2309) on the client side. I think it is probably best to leave these as errors from the instrumentation as there is always the option to change the status in a later processing stage.

**Comment by MrAlias** [comment]
> I think this is very similar to the discussion around whether to treat [HTTP 404 responses as errors](https://github.com/open-telemetry/opentelemetry-specification/pull/2309) on the client side. I think it is probably best to leave these as errors from the instrumentation as there is always the option to change the status in a later processing stage.

Agreed. It is always possible for a user to parse the `err` value passed to `Finished` and not pass certain values if they do not consider them variables that need to be reflected in the span.
