### ISSUE TITLE
Instrumentation needs to include a version.

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-contrib#214]
`Tracer`s and `Meter`s both take instrumentation versions as an option. All instrumentation in this repo should included that. This will help in debugging and when a Views API is created could be used to disable or unify different versions of the same instrumentation running on the same server.

- A version should be defined for all instrumentation in this repository.
- All instrumentation needs to be updated to use this version as a `Meter` and `Tracer` instrumentation version.
- The [instrumentation guidelines](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/master/instrumentation/README.md) need to be updated to specify that a version should be set for instrumentation.

### Instrumentation Punch List

- [x] instrumentation/host
- [x] instrumentation/google.golang.org/grpc/otelgrpc
- [x] instrumentation/go.mongodb.org/mongo-driver/mongo/otelmongo
- [x] instrumentation/net/http/otelhttp
- [x] instrumentation/net/http/httptrace/otelhttptrace
- [x] instrumentation/runtime
- [x] instrumentation/github.com/labstack/echo/otelecho
- [x] instrumentation/github.com/bradfitz/gomemcache/memcache/otelmemcache
- [x] instrumentation/github.com/gin-gonic/gin/otelgin
- [x] instrumentation/github.com/gocql/gocql/otelgocql
- [x] instrumentation/github.com/emicklei/go-restful/otelrestful
- [x] instrumentation/github.com/Shopify/sarama/otelsarama
- [x] instrumentation/github.com/gorilla/mux/otelmux
- [x] instrumentation/github.com/astaxie/beego/otelbeego
- [x] instrumentation/gopkg.in/macaron.v1/otelmacaron

**Comment by MrAlias** [comment]
Reference example: https://github.com/open-telemetry/opentelemetry-go-contrib/pull/204/files#r470091488

**Comment by MrAlias** [comment]
From the SIG meeting:

All instrumentation in this repo MUST share the same version and it needs to match repository version. This will unify this repos approach and avoid confusion of how things are versioned. It will also alleviate needing to track which versions are compatible with version of `otel`.

This also means that a top-level repository version `const` should be created so all instrumentation can reference it.

**Comment by reggiemcdonald** [comment]
I could help out with adding versions to the existing instrumentation packages, if help is still needed on this?

**Comment by MrAlias** [comment]
This is likely done, an audit is needed to verify this.

**Comment by matej-g** [comment]
I noticed some of the missing ones while working on a different issue, took the liberty of creating #412 for the remaining ones

**Comment by matej-g** [comment]
With #412 merged all instrumentation modules should include version now and this issue has been fully resolved.
