### ISSUE TITLE
how about add an  prefix for span name  in otelmongo，I'd like to add a prefix "Mongo."

### ISSUE THREAD

**Issue by jixiuf** [open-telemetry/opentelemetry-go-contrib#2140]
_, span := m.cfg.Tracer.Start(ctx, "Mongo."+spanName, opts...)

https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/go.mongodb.org/mongo-driver/mongo/otelmongo/mongo.go#L70

**Comment by dmathieu** [comment]
net/http has an option [WithSpanNameFormatter](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/net/http/otelhttp/config.go#L175).
I suppose we could do the same for mongo.

**Comment by MrAlias** [comment]
Naming is going to be subjective, but I am hesitant to add options to the API that can be achieved with primitives in the SDK. We try to keep the scope of what generated the span in the [`instrumentation.Library`](https://github.com/open-telemetry/opentelemetry-go/blob/625d76daea7147c5f28a364cb77540d966615ff3/sdk/instrumentation/library.go#L24-L33). If you want to merge this information with a span name you can do this by writing your own [`SpanProcessor`](https://github.com/open-telemetry/opentelemetry-go/blob/625d76daea7147c5f28a364cb77540d966615ff3/sdk/trace/span_processor.go#L22-L61). The [`OnStart`](https://github.com/open-telemetry/opentelemetry-go/blob/625d76daea7147c5f28a364cb77540d966615ff3/sdk/trace/span_processor.go#L30-L32) can modify the passed span's name to what you want when it detects the span came from this instrumentation.

**Comment by jixiuf** [comment]
thanks.
