### ISSUE TITLE
Consider exporting the tracer map in go.opentelemetry.io/contrib/internal/trace

### ISSUE THREAD

**Issue by reggiemcdonald** [open-telemetry/opentelemetry-go-contrib#218]
The current mock trace provider stores a map of the tracers created, but it isnt exported:
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/818b3374b7c9f82bf0deb06e26cbad50155c5f7b/internal/trace/mock_tracer.go#L30-L33

As we shift to using `WithTraceProvider` options (#213), it would be helpful to export the tracer map in the provider struct of the mocktrace package (`go.opentelemetry.io/contrib/internal/trace`). 

As it stands, you cannot type cast the `trace.Tracer` returned from the mock provider to the concrete `mocktrace.Tracer` type. 
Thus, we cannot access any of the convenience functions such as `mocktrace.Tracer.EndedSpans()`

**Comment by MrAlias** [comment]
Closing, stale.
