### ISSUE TITLE
OtelEcho swallows the error and does not pass it to other middlewares

### ISSUE THREAD

**Issue by hcelaloner** [open-telemetry/opentelemetry-go-contrib#2209]
## Background

Hi, we were trying to use OpenTelemetry [echo middleware](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation/github.com/labstack/echo/otelecho) provided in this repository in our project. However, using it causes misfunction in other middlewares.  For instance, while trying we were using another middleware to send errors to our current apm tool and it stopped recording errors.

It seems that the current implementation of echo middleware swallows the error and does not pass it to other middleware (https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/github.com/labstack/echo/otelecho/echo.go#L101). 

## Proposed Solution

- Return the error received from the next middleware call.
- Also don't call the registered HTTP error handler since it is automatically called if the error received from the next middleware call is returned.

**Comment by hcelaloner** [comment]
Submitted a PR with the proposed solution but I guess with this solution middleware is not able to detect the correct HTTP status code returned since this time HTTP error handler is called later. So the only way to handle is to leave it as it is? If that is the case adding test cases may be a good idea? Or should we register it as the last middleware if we want to see capture in other middleware?

**Comment by markhildreth-gravity** [comment]
FYI, the Echo project had a [similar issue](https://github.com/labstack/echo/issues/2015#issuecomment-1437809133) with their Recover framework. They decided to [make a flag](https://github.com/labstack/echo/commit/1e575b7b56d7f1478d889bbd7464f124efe9bc1e) to allow the user to let the error drop through.
