### ISSUE TITLE
Create top-level README to explain what kinds of instrumentation are present

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go-contrib#222]
I feel that "runtime" by itself is problematic, it's too general.

Possible names:
- "plugins/runtimemetrics"
- "plugins/metrics/runtime"

I prefer the first option because it avoids a conflict with the builtin "runtime" package in Go.

**Comment by MrAlias** [comment]
This would break from our consistent instrumentation package naming scheme https://github.com/open-telemetry/opentelemetry-go-contrib/tree/master/instrumentation#packaging

The goal of the existing naming scheme is to prioritize clarity of what package is being instrumented and aid discoverability. Given this package instruments the Go `runtime` package, the name seems appropriate enough to me.

The telemetry the instrumentation produces should be apparent from the documentation (go-docs and README). It might be helpful if in the instrumentation README or the top level README if we had a table showing support in instrumentation. E.g.

| Instrumented Package | Metric | Trace | Logs |
| --------------------  | -------- | -------- | ------ |
| [`runtime`](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/master/instrumentation/runtime) | ✓ |  | |
| [`net/http`](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/master/instrumentation/net/http) |  | ✓ | |
...

**Comment by jmacd** [comment]
The top-level README sounds good. I will rename this issue.
