### ISSUE TITLE
Add Resource support in the Datadog exporter

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go-contrib#23]
Since release https://github.com/open-telemetry/opentelemetry-go/releases/tag/v0.4.3 the library has changed its exporter API to pass a `*resource.Resource` object through the pipeline. These are the static key:value labels that were configured with the SDK. They should be included as labels in any metric and span export.

There is an opportunity to compute a `[]string` for these once and re-use it. The exporter should compute this caching on the first call to Export.

@marwan-at-work FYI

**Comment by jmacd** [comment]
For an example in the dogstatsd exporter, https://github.com/open-telemetry/opentelemetry-go-contrib/pull/25

**Comment by marwan-at-work** [comment]
Thank you for all the info, I will add that to the Datadog exporter this week 👍

**Comment by MrAlias** [comment]
Closing, stale. The datadog exporter was remove in https://github.com/open-telemetry/opentelemetry-go-contrib/releases/tag/v1.5.0
