### ISSUE TITLE
make precommit fails on exporters/cortex/metric package

### ISSUE THREAD

**Issue by reggiemcdonald** [open-telemetry/opentelemetry-go-contrib#232]
Running `make` fails on master for me. The error given is an invalid type conversion here:
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/0d5bd34c447991225d7ab6eaf59a4570bb1163d0/exporters/metric/cortex/cortex_test.go#L73

It seems that `aggregation.Kind` is a string type, but here an integer is being cast

**Comment by reggiemcdonald** [comment]
closing - was a go issue

**Comment by MrAlias** [comment]
Did you test with Go 1.15 by chance? I imagine it might be the the same error resolved here https://github.com/open-telemetry/opentelemetry-go/pull/1064/commits/47b1fd8746f3c88280e2ce6fcdacd81f964067ad

Going to open an issue to track moving tests to Go 1.15 here as well.

**Comment by reggiemcdonald** [comment]
Its a developer version thats essentially at 1.15. So yea I'd say its related to the linked error
