### ISSUE TITLE
Update build to verify current and previous versions of Go

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-contrib#239]
[Similar to the main repository](https://github.com/open-telemetry/opentelemetry-go/blob/f995380e5848d2b9287f8b8e0608a4bda6f986d5/.circleci/config.yml#L2-L10) this repository needs to maintain compatibility with both the current version of Go and the previous version.

_Originally posted by @MrAlias in https://github.com/open-telemetry/opentelemetry-go-contrib/pull/236_

**Comment by KKelvinLo** [comment]
Hello! Can I take up this issue to work on?

**Comment by KKelvinLo** [comment]
Should this issue be closed?
