### ISSUE TITLE
go test  ./instrumentation/host fail

### ISSUE THREAD

**Issue by tttoad** [open-telemetry/opentelemetry-go-contrib#2575]
![image](https://user-images.githubusercontent.com/14021602/179224564-3932a833-0323-48bd-a4b8-8f127853a804.png)

OS: windows10/wsl-ubuntu18.04
go version: go version go1.18.2 linux/amd64

**Comment by MrAlias** [comment]
What version of opentelemetry-go-contrib are you running?

What is your CPU architecture (amd64, 386)?

How often does this happen? Every time you run it?

**Comment by tttoad** [comment]
@MrAlias 
CPU is amd64. 
Every time.
This will only happen in the WSL subsystem.
Works in windows 11, but windows 11/wsl (version 1) does not work.
Maybe it's a bug in the WSL.

**Comment by MrAlias** [comment]
@pellared can you reproduce this?

**Comment by tttoad** [comment]
I updated WSL1 to WSL2 and it worked.
I think there is something wrong with the WSL1.
Not related to test code.
This issue should be closed.
