### ISSUE TITLE
Rename or remove runtime.uptime metric from instrumentation/runtime package

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go-contrib#2625]
In #1549 added a "process." prefix to the metrics that had been prefixed "runtime.go" already., 
The "runtime.uptime" metric was not renamed, but it also did not have the "runtime.go" prefix.

In my opinion, `rutime.uptime` should be removed and OTel would ideally specify a resource attribute that would allow deriving the uptime at the moment of any data point, see https://github.com/open-telemetry/opentelemetry-specification/issues/1273. My preference is to remove "runtime.uptime".

An alternative is to rename this "process.runtime.go.uptime", since OTel hasn't specified a cross-lang process uptime metric presently.

**Comment by AkhigbeEromo** [comment]
Would like to work on this issue @jmacd @MrAlias

**Comment by MrAlias** [comment]
The uptime metric was deprecated in https://github.com/open-telemetry/opentelemetry-go-contrib/releases/tag/v1.29.0. Closing.
