### ISSUE TITLE
release cadence? (v1.10.0)

### ISSUE THREAD

**Issue by pfrydids** [open-telemetry/opentelemetry-go-contrib#2747]
Is there a release cadence for the go.opentelemetry.io/contrib module?

I am waiting on https://github.com/open-telemetry/opentelemetry-go-contrib/pull/2572 which was merged a few weeks ago.

I noticed that the [Release v1.10.0 milestone](https://github.com/open-telemetry/opentelemetry-go-contrib/milestone/4) issue has no related open issues.

**Comment by MrAlias** [comment]
Please see https://github.com/open-telemetry/opentelemetry-go/issues/3157, it is tracking the release.
