### ISSUE TITLE
Add integration testing to the runtime instrumenation

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-contrib#2757]
Integration testing for the `runtime` instrumentation was removed in https://github.com/open-telemetry/opentelemetry-go-contrib/pull/2756

When https://github.com/open-telemetry/opentelemetry-go/issues/3031 is resolved, a new `runtime/test` package need to be created and integration testing for the instrumentation added to it.

**Comment by jmacd** [comment]
> Note that I don't think we should restore these tests, instead write new ones as described in https://github.com/open-telemetry/opentelemetry-go-contrib/issues/2624 and https://github.com/open-telemetry/opentelemetry-go-contrib/issues/2625. I've drafted such tests in https://github.com/lightstep/otel-launcher-go/tree/main/lightstep/instrumentation/runtime.

**Comment by MrAlias** [comment]
Blocked by https://github.com/open-telemetry/opentelemetry-go/issues/3407

**Comment by MrAlias** [comment]
Unblocked. Use a manual-reader to collect expected metrics and the `metricdatatest` package to compare expected values (or just compare directly).

**Comment by MrAlias** [comment]
Blocked by:

- https://github.com/open-telemetry/opentelemetry-go-contrib/issues/2648
- https://github.com/open-telemetry/opentelemetry-go-contrib/issues/2625
- https://github.com/open-telemetry/opentelemetry-go-contrib/issues/2624
- https://github.com/open-telemetry/opentelemetry-go-contrib/issues/1341
- https://github.com/open-telemetry/opentelemetry-go-contrib/issues/368
- https://github.com/open-telemetry/opentelemetry-go-contrib/issues/316

**Comment by Victorsesan** [comment]
Can you assign this to me ?

**Comment by Victorsesan** [comment]
@dmathieu just wondering was https://github.com/open-telemetry/opentelemetry-go/issues/3031 completely resolved for this issue?

**Comment by dmathieu** [comment]
The [good first issue](https://github.com/open-telemetry/opentelemetry-go-contrib/labels/good%20first%20issue) tag has a few issues for newcomers.
Feel free to look at any open issue though.

**Comment by dmathieu** [comment]
Closing this, as I believe it has been done.
