### ISSUE TITLE
Decide on the directory structure of the plugins directory

### ISSUE THREAD

**Issue by krnowak** [open-telemetry/opentelemetry-go-contrib#28]
I was thinking how the plugins should be laid out. At first I was stripping the code hosting name, so I had `go.opentelemetry.io/contrib/plugins/gorilla/mux`. But I think that maybe it should just repeat the import path of the instrumented library, so basically ``go.opentelemetry.io/contrib/plugins/<IMPORT_PATH>`, like:

- `go.opentelemetry.io/contrib/plugins/github.com/gorilla/mux`
- `go.opentelemetry.io/contrib/plugins/gopkg.in/macaron.v1`
- `go.opentelemetry.io/contrib/plugins/database/sql`

**Comment by krnowak** [comment]
The result of this issue should be some documentation for the instrumentation writers about where to put the instrumentation.

**Comment by krnowak** [comment]
Another question is whether we want to differentiate between tracing instrumentation and metrics instrumentation. Whether these two should end up in different packages. IMO, no.

**Comment by Aneurysm9** [comment]
I think I would prefer consolidated trace and metrics instrumentation.  It should be easy for a developer to include an instrumentation plugin for their system of choice and get all the capabilities we have to offer.  It should also be easy for them to configure an instrumentation plugin to only provide traces or metrics, if desired.
