### ISSUE TITLE
Define an ownership model for packages that live in this repository 

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-contrib#2834]
This is a needed action for https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/3 to be hosted here.

**Comment by pellared** [comment]
This may be helpful https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1275 for setting up default reviewers

**Comment by Aneurysm9** [comment]
I thought we were going to use a separate repo for this?  Why the change?

**Comment by pdelewski** [comment]
There is an argument that [contrib](https://github.com/open-telemetry/opentelemetry-go-contrib) is a collection of tools and libraries used by people that want to use/learn about opentelemetry and may fit better to this kind of tool as it works on source level instead of runtime, however it depends on point of view as the only difference is point of hooking (source vs runtime)

**Comment by MrAlias** [comment]
- Codeowner file will need to be updated
   - Every Go module will need one or more unique user to be defined as an owner
   - The initial PR adding a module is required to also update the CODEOWNERS file with the explicit owners
   - Every go module will also need to have the approvers of the project listed as owners
- Repo permissions need to be updated
   - Every PR in a sub-dir will need approval from one of the specifically defined owner user
   - [stretch goal] Have the owners be able to merge PR
- Deprecation strategy
   - If the unique owners of the sub-dir are not able to continue on as owners (this need to be better defined) they are removed from the CODEOWNERS file
   - If there are not unique owners of a sub-dir, that modules is deprecated

Work to be done to adopt this:

- [ ] All existing modules need to be allocated to a owner or deprecated.

**Comment by MrAlias** [comment]
An approver/maintainer from this project would need to be a CODEOWNER of each module as well.

**Comment by MrAlias** [comment]
In collector contrib there is a labeling model that helps alert CODEOWNERS when PRs/Issues are added.

**Comment by MadVikingGod** [comment]
The inventory:

- [ ] CODEOWNERS
- [ ] detectors/aws/CODEOWNERS (or the following 4)
- [ ] detectors/aws/ec2/CODEOWNERS
- [ ] detectors/aws/ecs/CODEOWNERS
- [ ] detectors/aws/eks/CODEOWNERS
- [ ] detectors/aws/lambda/CODEOWNERS
- [ ] detectors/gcp/CODEOWNERS
- [ ] instrumentation/github.com/astaxie/beego/otelbeego/CODEOWNERS
- [ ] instrumentation/github.com/aws/aws-lambda-go/otellambda/CODEOWNERS
- [ ] instrumentation/github.com/aws/aws-sdk-go-v2/otelaws/CODEOWNERS
- [ ] instrumentation/github.com/bradfitz/gomemcache/memcache/otelmemcache/CODEOWNERS
- [ ] instrumentation/github.com/emicklei/go-restful/otelrestful/CODEOWNERS
- [ ] instrumentation/github.com/gin-gonic/gin/otelgin/CODEOWNERS
- [ ] instrumentation/github.com/go-kit/kit/otelkit/CODEOWNERS
- [ ] instrumentation/github.com/gocql/gocql/otelgocql/CODEOWNERS
- [ ] instrumentation/github.com/gorilla/mux/otelmux/CODEOWNERS
- [ ] instrumentation/github.com/labstack/echo/otelecho/CODEOWNERS
- [ ] instrumentation/github.com/Shopify/sarama/otelsarama/CODEOWNERS
- [ ] instrumentation/go.mongodb.org/mongo-driver/mongo/otelmongo/CODEOWNERS
- [ ] instrumentation/google.golang.org/grpc/otelgrpc/CODEOWNERS
- [ ] instrumentation/gopkg.in/macaron.v1/otelmacaron/CODEOWNERS
- [ ] instrumentation/host/CODEOWNERS
- [ ] instrumentation/net/http/httptrace/otelhttptrace/CODEOWNERS
- [ ] instrumentation/net/http/otelhttp/CODEOWNERS
- [ ] instrumentation/runtime/CODEOWNERS
- [ ] propagators/autoprop/CODEOWNERS
- [ ] propagators/aws/CODEOWNERS
- [ ] propagators/b3/CODEOWNERS
- [ ] propagators/jaeger/CODEOWNERS
- [ ] propagators/opencensus/CODEOWNERS
- [ ] propagators/ot/CODEOWNERS
- [ ] samplers/aws/xray/CODEOWNERS
- [ ] samplers/jaegerremote/CODEOWNERS
- [ ] samplers/probability/consistent/CODEOWNERS
- [ ] tools/CODEOWNERS (this could fall under the top level)
- [ ] zpages/CODEOWNERS

**Comment by MrAlias** [comment]
@open-telemetry/go-approvers please comment here if you would be willing to take on the ownership responsibility for an above module.

This will include you being required to approve PRs for that module and have the ultimate responsibility for an issue related to the module (you are not expected to complete all work there, just you will be expected to keep development moving at a _reasonable_ pace.).

**Comment by pellared** [comment]
I can take `propagators/b3/` and `instrumentation/github.com/Shopify/sarama/otelsarama/`

**Comment by MadVikingGod** [comment]
Before too many more people chime in.  There is the initial codeowners file in #3045.  You can add yourself as a change request to that PR, or wait until after it's merged and open a PR to accept ownership.

**Comment by pellared** [comment]
@yurishkuro [`propagators/jaeger`](https://pkg.go.dev/go.opentelemetry.io/contrib/propagators/jaeger) and [`samplers/jaegerremote`](https://pkg.go.dev/go.opentelemetry.io/contrib/samplers/jaegerremote) are not maintained. Are you OK of dropping support for them or would you find someone who could be a code owner of these modules?

**Comment by pellared** [comment]
@MrAlias [`propagators/ot`](https://pkg.go.dev/go.opentelemetry.io/contrib/propagators/ot) is used by [`propagators/autoprop`](https://pkg.go.dev/go.opentelemetry.io/contrib/propagators/autoprop). I think it would be better to keep `propagators/ot`. Would you be able to be codeowner of this module?

**Comment by pellared** [comment]
[`otelmongo`](https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/go.mongodb.org/mongo-driver/mongo/otelmongo) is a quite popular instrumentation library and we should ask if it could be moved to https://github.com/mongodb (similarly like for `otelsarama`). I decided to postpone the deprecation. I created https://jira.mongodb.org/browse/GODRIVER-2938

**Comment by pellared** [comment]
For HTTP instrumentation libraries, I think we should simply improve `otelhttp` so that it can be reused with other libraries. The question is if we should improve `otelhttp` before deprecating the libraries to provide an migration path for the users? Some part of it is in my head after looking at https://github.com/open-telemetry/opentelemetry-go-contrib/issues/4018, https://github.com/open-telemetry/opentelemetry-go-contrib/pull/4017. For now, I decided to postpone the deprecation.

**Comment by yurishkuro** [comment]
> @yurishkuro [propagators/jaeger](https://pkg.go.dev/go.opentelemetry.io/contrib/propagators/jaeger) and [samplers/jaegerremote](https://pkg.go.dev/go.opentelemetry.io/contrib/samplers/jaegerremote) are not maintained. Are you OK of dropping support for them or would you find someone who could be a code owner of these modules?

What does dropping support mean? 

`propagators/jaeger`: I expect this to be a very stable code that does not require maintenance (it's not like the format is changing). But support for the format is required by the Spec: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/api-propagators.md#propagators-distribution

`samplers/jaegerremote`: I'm ok to own it. It is also in the spec: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#jaegerremotesampler

**Comment by pellared** [comment]
> > @yurishkuro [propagators/jaeger](https://pkg.go.dev/go.opentelemetry.io/contrib/propagators/jaeger) and [samplers/jaegerremote](https://pkg.go.dev/go.opentelemetry.io/contrib/samplers/jaegerremote) are not maintained. Are you OK of dropping support for them or would you find someone who could be a code owner of these modules?
> 
> What does dropping support mean?

Deprecation in next release. Removal from codebase and OTel registry in subsequent release.

> `propagators/jaeger`: I expect this to be a very stable code that does not require maintenance (it's not like the format is changing). But support for the format is required by the Spec: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/api-propagators.md#propagators-distribution
>
> `samplers/jaegerremote`: I'm ok to own it. It is also in the spec: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#jaegerremotesampler

Then I will propose a PR to add you as code owner for both modules. Please approve them if you are OK with it and thanks for the collaboration ❤️
