### ISSUE TITLE
Build error with otelgrpc v0.36.4 - module requires Go 1.18

### ISSUE THREAD

**Issue by mwittig** [open-telemetry/opentelemetry-go-contrib#2894]
What version of Go and opentelemetry-go-contrib are you using? 

- `go1.17.9 darwin/arm64` and `otelgrpc v0.36.4`

What operating system and processor architecture are you using?

- `macOS 12.6 darwin/arm64`

What did you do?What did you expect to see? What did you see instead?

I am trying to build my project with `otelgrpc v0.36.4` which causes a build error as some source code used by the package requires go1.18. With `otelgrpc v0.36.3` everything works fine, though. So, it seem like the compatibility issue has been introduced with the current maintenance release of `otelgrpc`. Apparently the the issue is caused by the indirect dependency on `otel v1.11.1`

```
# go.opentelemetry.io/otel/internal/attribute
../../go/pkg/mod/go.opentelemetry.io/otel@v1.11.1/internal/attribute/attribute.go:26:6: missing function body
../../go/pkg/mod/go.opentelemetry.io/otel@v1.11.1/internal/attribute/attribute.go:26:16: syntax error: unexpected [, expecting (
../../go/pkg/mod/go.opentelemetry.io/otel@v1.11.1/internal/attribute/attribute.go:28:2: syntax error: non-declaration statement outside function body
../../go/pkg/mod/go.opentelemetry.io/otel@v1.11.1/internal/attribute/attribute.go:34:6: missing function body
../../go/pkg/mod/go.opentelemetry.io/otel@v1.11.1/internal/attribute/attribute.go:34:13: syntax error: unexpected [, expecting (
../../go/pkg/mod/go.opentelemetry.io/otel@v1.11.1/internal/attribute/attribute.go:39:6: zero redeclared in this block
        /Users/mwittig/go/pkg/mod/go.opentelemetry.io/otel@v1.11.1/internal/attribute/attribute.go:27:6: previous declaration
../../go/pkg/mod/go.opentelemetry.io/otel@v1.11.1/internal/attribute/attribute.go:40:2: syntax error: non-declaration statement outside function body
note: module requires Go 1.18
```

**Comment by dmathieu** [comment]
We follow the Go release model: https://go.dev/doc/devel/release#policy
Which means that only 1.18 and 1.19 are supported, not earlier versions. We dropped support for 1.17 here: https://github.com/open-telemetry/opentelemetry-go-contrib/pull/2785
