### ISSUE TITLE
otelhttptrace generates disjoint traces (4 traces instead of 1, only 1 with more than 1 span) - for a single request

### ISSUE THREAD

**Issue by ldemailly** [open-telemetry/opentelemetry-go-contrib#3046]
### Description

otelhttptrace generates disjoint traces (4 traces instead of 1, only 1 with more than 1 span) - for a single request

you would expect if you set up otelhttptrace.NewClientTrace for an http Request and "do" it to get a single trace with 6 spans instead you get 4 disconnected traces

<img width="751" alt="Screen Shot 2022-11-30 at 2 35 02 PM" src="https://user-images.githubusercontent.com/3664595/204922870-6df90c74-faea-4c38-82bf-c28d9d0df399.png">

Only getconn has spans

<img width="564" alt="Screen Shot 2022-11-30 at 2 35 26 PM" src="https://user-images.githubusercontent.com/3664595/204922931-bef4ad81-5040-4e94-9998-2607d3c5f9b1.png">

Note: the whole idea is to not have to change the transport

### Environment

- OS: MacOS but not likely to be OS specific
- Architecture: arm64 (but ditto)
- Go Version: go version go1.19.3 darwin/arm64
- opentelemetry-go version: 

	go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace v0.36.4
	go.opentelemetry.io/otel v1.11.1
	go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.11.1
	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.11.1
	go.opentelemetry.io/otel/sdk v1.11.1

### Steps To Reproduce

Also on https://github.com/fortio/fortiotel/blob/main/simple/otel_httptrace_simple.go (including go.mod there)

```golang
// Repro basic issue with otelhttptrace
// This generates 4 traces instead of 1 trace with all the spans

package main

import (
	"context"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/http/httptrace"

	"go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
)

// Simplified version of
// https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/otlp/otlptrace/otlptracehttp/example_test.go

// See traces using:
/*
 docker run -p 16686:16686 -p 4317:4317 jaegertracing/all-in-one:latest \
--collector.otlp.enabled=true --collector.otlp.grpc.host-port=:4317
*/

func installExportPipeline(ctx context.Context) (func(context.Context) error, error) {
	// Insecure needed for jaeger otel grpc endpoint by default/using all-in-one.
	// (and istio envoy will mtls secure it when not running local tests anyway)
	client := otlptracegrpc.NewClient(otlptracegrpc.WithInsecure())
	exporter, err := otlptrace.New(ctx, client)
	if err != nil {
		return nil, fmt.Errorf("creating OTLP trace exporter: %w", err)
	}

	tracerProvider := sdktrace.NewTracerProvider(
		sdktrace.WithBatcher(exporter),
	)
	otel.SetTracerProvider(tracerProvider)

	return tracerProvider.Shutdown, nil
}

func main() {
	ctx := context.Background()
	clientTrace := otelhttptrace.NewClientTrace(ctx)
	// Registers a tracer Provider globally.
	shutdown, err := installExportPipeline(ctx)
	if err != nil {
		log.Fatalf("Error setting up export pipeline: %v", err)
	}
	log.Printf("OTEL export pipeline setup successfully")

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, "http://www.google.com/", nil)
	if err != nil {
		log.Fatalf("Error creating request: %v", err)
	}
	req = req.WithContext(httptrace.WithClientTrace(req.Context(), clientTrace))
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		log.Fatalf("Error executing request: %v", err)
	}
	_, err = io.ReadAll(resp.Body)
	if err != nil {
		log.Fatalf("Error reading response body: %v", err)
	}
	_ = resp.Body.Close()
	if err := shutdown(context.Background()); err != nil {
		log.Fatalf("Error shutting down up export pipeline: %v", err)
	}
	log.Printf("OTEL export pipeline shut down successfully")
}
```

run, observe traces - for instance with jaeger started before using:
```
 docker run -p 16686:16686 -p 4317:4317 jaegertracing/all-in-one:latest \
--collector.otlp.enabled=true --collector.otlp.grpc.host-port=:4317
```

output:
```
$ go run .
2022/11/30 14:39:21 OTEL export pipeline setup successfully
2022/11/30 14:39:21 OTLP partial success: empty message (0 spans rejected)
2022/11/30 14:39:21 OTEL export pipeline shut down successfully
```

### Expected behavior

1 trace, 6 spans

ps: maybe by simplifying the setup I simplified it too much?

**Comment by ldemailly** [comment]
updated go.mod to latest and still same issue - just that it takes a bit longer to shutdown and that
```
2022/11/30 14:39:21 OTLP partial success: empty message (0 spans rejected)
```
is gone:

```
$ go run .
2022/12/06 17:10:51 OTEL export pipeline setup successfully
2022/12/06 17:10:51 OTEL export pipeline shut down successfully
```

**Comment by dmathieu** [comment]
I'm thinking this may be a shortcoming of the [net/http/httptrace](https://pkg.go.dev/net/http/httptrace) implementation. It doesn't allow running code on "request start", which should be the root span.

Also, because it doesn't really use context, we have to implement our own store and way to retrieve it. But doing so means anything creating a new context with a parent span will not be propagated to our store.
So using the otelhttp client/transport to create a root span doesn't work either (the HTTP span doesn't have any of the httptrace spans, because the transport creates a new context which isn't updated within the tracer client).

**Comment by ldemailly** [comment]
Thanks for the response.

How come it manages to make span for getconn/dns/connect but not the overall request?

but yeah I see the api doesn't pass back the context (which for go api... is funny)

does it mean I have to use it in conjunction with a transport / the other go http trace? are the two complementing one another?

**Comment by dmathieu** [comment]
httptrace has no callback for the request being started (unless we consider "getconn" is the beginning of the request), that's why there is no span for the overall request.
Yes, it would need to be used in conjonction with something which creates a root span when the request is started. Unfortunately, a transport won't work, because it will need to update/change its context after the client tracer has stored one.

**Comment by ldemailly** [comment]
what's wrong with using getconn as the start?

**Comment by dmathieu** [comment]
It's not explicitly the start of the request. A lot happens between the start of a round trip, and the default transport acquiring a connection.
https://github.com/golang/go/blob/master/src/net/http/transport.go#L512-L590

Also, it would mean `GetConn` encompasses all other spans. That's not accurate. A span starts at GetConn, and ends at GotConn (the time taken to retrieve the connection).
But writing headers (for example) is not part of acquiring a connection, and therefore has no reason to be a child of that span.

**Comment by ldemailly** [comment]
> That's not accurate

Well maybe it's not perfect but I'm looking for any practical way to get a trace with the spans; right now it doesn't seem very useful in itself - what would make it work (create the original span/trace in the context first? before `Do`?)

**Comment by ldemailly** [comment]
It does work if adding a span but my goal was to instrument a library that only supports client trace

```golang
        // calling this first
	ctx, span := otel.Tracer("github.com/fortio/fortiotel").Start(ctx, "main")
        // then this will add spans
	clientTrace := otelhttptrace.NewClientTrace(ctx)
```

<img width="698" alt="Screenshot 2022-12-10 at 12 47 01 PM" src="https://user-images.githubusercontent.com/3664595/206874647-755c9657-1844-4287-af88-4cb7c95cc178.png">

**Comment by ldemailly** [comment]
but it doesn't actually put anything in the request headers either

**Comment by ldemailly** [comment]
If I use otelhttp in conjunction, it sort of helps... except for
https://github.com/open-telemetry/opentelemetry-go-contrib/issues/399#issuecomment-1362174190

**Comment by ldemailly** [comment]
fixed thanks to https://github.com/open-telemetry/opentelemetry-go-contrib/issues/399#issuecomment-1564736272 doing https://github.com/fortio/fortiotel/commit/3fb1155c865f91931042b0085df7263a4fd2ca51
