### ISSUE TITLE
go.opentelemetry.io/contrib/instrumentation/runtime

### ISSUE THREAD

**Issue by hstoresin** [open-telemetry/opentelemetry-go-contrib#3087]
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/ad04d9c71cb8974374ba8e3ee454fdaaddc3e345/instrumentation/runtime/runtime.go#L78

**Comment by hstoresin** [comment]
> https://github.com/open-telemetry/opentelemetry-go-contrib/blob/ad04d9c71cb8974374ba8e3ee454fdaaddc3e345/instrumentation/runtime/runtime.go#L78

https://github.com/open-telemetry/opentelemetry-go-contrib/issues/3087#issue-1497662783

**Comment by dmathieu** [comment]
Closing this, as it's not reporting anything. Please describe an actual problem when you open an issue.
