### ISSUE TITLE
Merge the mock tracer into the otel-go's mock tracer.

### ISSUE THREAD

**Issue by krnowak** [open-telemetry/opentelemetry-go-contrib#31]
The mock tracer in `internal/trace` is a modified copy of the mock tracer in otel-go. When we decide that our copy of mock tracer meets the needs of the instrumentation testing code (so the mock tracer stabilized) then it would be good to reduce the code duplication and bring the changes back to otel-go.

**Comment by matej-g** [comment]
Would take this toget with #385
