### ISSUE TITLE
Go custom tracer name

### ISSUE THREAD

**Issue by TrayserCassa** [open-telemetry/opentelemetry-go-contrib#3110]
We used opentracing in the past and switched to opentelemetry. We use grpc and the aws instrumentation and found out, that we can't customize the tracer name. I think we should set this with an option, because if I look into Datadog the package name is so long that it is not very helpful at all.
What do you think?

**Comment by dmathieu** [comment]
That does seem like a nice addition.

**Comment by TrayserCassa** [comment]
To be fair, as I read more about creating your own instrumentation they tell you to use the traceprovider and not expose the tracer. I like the idear from temporal a bit more. They let you name the tracer if you want to. 
Anyway..
I didn't find a package where they allow the renaming, so I think it won't be merged because it's not the standart right?

**Comment by MrAlias** [comment]
Our instrumentation follows [the OpenTelemetry guidelines](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#get-a-tracer)

> `name` (required): This name SHOULD uniquely identify the instrumentation scope, such as the instrumentation library (e.g. `io.opentelemetry.contrib.mongodb`), package, module or class name.

Allowing OpenTelemetry supported instrumentation to deviate from this is not something we should support.

Allowing an operator of an SDK to overwrite a scope name in general was something the specification had considered, but I'm not sure how far it got. I would recommend asking in [# otel-specification](https://cloud-native.slack.com/archives/C01N7PP1THC) or with an issue/discussion the specification repository.

**Comment by TrayserCassa** [comment]
We now stick with it and remap the name field in Datadog to have a readable name. I will close this issue, because this should then changed by the specification as @MrAlias mentioned
