### ISSUE TITLE
[otelgrpc] gRPC ServerInterceptor error handling

### ISSUE THREAD

**Issue by zraining** [open-telemetry/opentelemetry-go-contrib#3122]
Hi all,

I am facing a problem is that any GRPC request with an error response is considered an error trace, whatever it is NotFoundError or InternalError, an error will be tagged true. Since we had some normal business to return NotFound(rpc.grpc.status_code=5), this caused us to have high error rate in our observability dashboard. Here is an example of a related interceptor - [UnaryServerInterceptor](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/google.golang.org/grpc/otelgrpc/interceptor.go#L353)

I compared few implementation of http middleware, and they will determine whether it is an error call based on the HTTP status code. For example, 4xx is not considered a server-side error.  e.g. [otelgin_middleware](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/github.com/gin-gonic/gin/otelgin/gintrace.go#L91)

My question is whether this is intentional or can be improved? I am looking forward to your reply and thank you in advance.

**Comment by MrAlias** [comment]
This is something [defined by the OpenTelemetry specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/rpc.md#grpc-status). Our implementation conforms with this definition.

**Comment by zraining** [comment]
Understood, thank you @MrAlias
