### ISSUE TITLE
Request to Add Instrumentation for otelhttp

### ISSUE THREAD

**Issue by apal60** [open-telemetry/opentelemetry-go-contrib#3123]
Hello Team,
         I am getting this error. it looks package mismatch. Could you please check this?

 go.opentelemetry.io/otel/semconv: module go.opentelemetry.io/otel@latest found (v1.11.2), but does not contain package go.opentelemetry.io/otel/semconv
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp tested by
        go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.test imports
        go.opentelemetry.io/otel/oteltest imports
        go.opentelemetry.io/otel/metric/registry: module go.opentelemetry.io/otel/metric@latest found (v0.34.0), but does not contain package go.opentelemetry.io/otel/metric/registry

**Package Link**: go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp

**Comment by Aneurysm9** [comment]
If you are updating from an old version of the SDK you will need to adjust your imports for `go.opentelemetry.io/otel/semconv` to something like `go.opentelemetry.io/otel/semconv/v1.12.0`.  See https://github.com/open-telemetry/opentelemetry-go/tree/main/semconv for the available semconv packages if you require a different version.
