### ISSUE TITLE
How Remote sampling works without jaeger agent samping port 5778

### ISSUE THREAD

**Issue by Narenderbhcu** [open-telemetry/opentelemetry-go-contrib#3132]
Hi, as per below link, both Jaeger Agent and OpenTelemetry Collector implement the Jaeger sampling service endpoint.

[https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/samplers/jaegerremote]

jaegerRemoteSampler := jaegerremote.New(
		"your-service-name",
		**jaegerremote.WithSamplingServerURL("http://{sampling_service_host_name}:5778"),**
		jaegerremote.WithSamplingRefreshInterval(10*time.Second),
		jaegerremote.WithInitialSampler(trace.TraceIDRatioBased(0.5)),
	)

	tp := trace.NewTracerProvider(
		trace.WithSampler(jaegerRemoteSampler),
		...
	)
	otel.SetTracerProvider(tp)
I am trying to use opentelemetry collector sampling port instead of jaeger agent port "http://{sampling_service_host_name}:5778", but I am unable to fetch sampling strategy information from the backend.
Tried with 
**jaegerremote.WithSamplingServerURL("http://{sampling_service_host_name}:4317"),** and **jaegerremote.WithSamplingServerURL("http://{sampling_service_host_name}:4318"),** 

but not working, please let me know how remote sampling work using opentelemetry collector sampling service endpoint, if share any reference if you have.

**Comment by MrAlias** [comment]
Please see #3147, it should help clarify Jaeger endpoints.

Closing as #3147 looks to have resolved this. Please reopen if this is not the case.
