### ISSUE TITLE
Add metrics for transport layer in instrumentation net/http

### ISSUE THREAD

**Issue by kw510** [open-telemetry/opentelemetry-go-contrib#3134]
Metrics are provided in the handler of net/http, however they are not provided in the transport layer. This would be super useful to monitor outgoing requests.

https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/net/http/otelhttp/transport.go

**Comment by rangzen** [comment]
I invite you to follow #3765 to avoid duplicating the actual problem when resolving this issue.

**Comment by Sovietaced** [comment]
@MrAlias Is this an issue you would be open to having a community contribution for?

**Comment by jlordiales** [comment]
@Sovietaced there's already an open PR for this: https://github.com/open-telemetry/opentelemetry-go-contrib/pull/3769

**Comment by Sovietaced** [comment]
Thanks @ jlordiales

I will focus my efforts there.
