### ISSUE TITLE
otelgrpc: performance issue about otlpreceiver invoke proto.Size slow path

### ISSUE THREAD

**Issue by hanjm** [open-telemetry/opentelemetry-go-contrib#3165]
The opentelemetry collector otlpreceiver consume lots of cpu for proto.Size, marshal to buffer, get buffer size.

related https://github.com/open-telemetry/opentelemetry-collector/issues/6947

I think it shoud try get size from asserting interface `Size() int`, then try to use proto.Size

**Comment by bogdandrutu** [comment]
A possible better option is to actually implement `stats.Handler` (which was designed for this) instead of unary/streaming interceptors. The stats handlers have all the lengths pre-calculated and available.

**Comment by bogdandrutu** [comment]
See OpenCensus https://github.com/census-instrumentation/opencensus-go/blob/v0.24.0/plugin/ocgrpc/server.go#LL32C4-L32C4

**Comment by Aneurysm9** [comment]
I have created https://github.com/open-telemetry/opentelemetry-go-contrib/pull/3168 to remove the attribute for the time being.  I agree that the `stats.Handler` interface looks like it is the correct way to go in the longer term, but I do not know when such an implementation can be created.
