### ISSUE TITLE
aws ecs detector panics in AWS govcloud

### ISSUE THREAD

**Issue by ahobson** [open-telemetry/opentelemetry-go-contrib#3166]
In [AWS GovCloud, ARNs do not begin with `arn:aws:`](https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-arns.html).

That causes a panic at https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/detectors/aws/ecs/ecs.go#L165 where it assumes it will always find one submatch.

Proposal: Use regular expressions of the form `arn:aws[^:]+:ecs:...`

If that is acceptable, I can create a pull request

**Comment by Aneurysm9** [comment]
Fun™!  

I think that is workable, but probably needs to capture the partition as ARNs are reconstructed from component parts later:

https://github.com/open-telemetry/opentelemetry-go-contrib/blob/4b49f0657677d261366896273047df5e7e0594a6/detectors/aws/ecs/ecs.go#L168-L173

Alternately, would splitting on `:` and taking elements positionally work?  It looks like that's all the regex is doing anyways.

**Comment by rogeruiz** [comment]
I think splitting on `:` would work here. The ARN difference between commercial and GovCloud is `arn:aws:` versus `arn:aws-us-gov`. My only concern would be the S3 ARN has triple `:` colons in their name, but since we're only targeting `:log-group:` here we should be okay? 

I also wanted to add that the regex would also work here.

**Comment by ahobson** [comment]
Pull Request created: https://github.com/open-telemetry/opentelemetry-go-contrib/pull/3167 

After I created my PR, I saw https://github.com/open-telemetry/opentelemetry-go-contrib/pull/3092 doing almost the exact same thing

**Comment by ahobson** [comment]
CLA has been signed

**Comment by ahobson** [comment]
Hi! Is there anything else I can do to help this PR get merged?

**Comment by ahobson** [comment]
Hi! I've updated my branch to the latest from main and re-run the linters and tests locally and it all passes. Is there anything I can do to help get this merged in?
