### ISSUE TITLE
otelgrpc: Consider using `stats.Handler` instead of interceptor

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-go-contrib#3169]
See [comment](https://github.com/open-telemetry/opentelemetry-go-contrib/issues/3165#issuecomment-1386010160) on #3165.

**Comment by dashpole** [comment]
+1.  This was something that came up when discussing instrumentation with the gRPC-go team at Google.

**Comment by MrAlias** [comment]
This looks like a duplicate of https://github.com/open-telemetry/opentelemetry-go-contrib/issues/197
