### ISSUE TITLE
Module fails importing from `launcher` package

### ISSUE THREAD

**Issue by blixenkrone** [open-telemetry/opentelemetry-go-contrib#3177]
Hello!
I'm facing a module import issue when using this package with `github.com/honeycombio/honeycomb-opentelemetry-go@v0.4.1` (latest).

Latest working module imports are:
```go.mod
github.com/honeycombio/honeycomb-opentelemetry-go v0.3.0
github.com/honeycombio/opentelemetry-go-contrib/launcher v0.0.0-20221031150637-a3c60ed98d54
```

Versions failing are:
```go.mod
github.com/honeycombio/honeycomb-opentelemetry-go v0.4.1
github.com/honeycombio/opentelemetry-go-contrib/launcher v0.0.0-20221031150637-a3c60ed98d54
```	

- What version of Go and opentelemetry-go-contrib are you using?
`go version go1.19.5 darwin/arm64`
`v0.4.1`

- What operating system and processor architecture are you using?
MacOS 13.1
M1
- What did you do?
Run $ go mod tidy
- What did you expect to see?
```
Tidying code...
all modules verified
```
- What did you see instead?
```
Tidying code...
go: finding module for package github.com/honeycombio/opentelemetry-go-contrib/launcher
github.com/clicksandmortar/jet-integration/cmd/jetintegration/gen imports
        github.com/honeycombio/opentelemetry-go-contrib/launcher: module github.com/honeycombio/opentelemetry-go-contrib@latest found (v1.11.1), but does not contain package github.com/honeycombio/opentelemetry-go-contrib/launcher
```

**Comment by Aneurysm9** [comment]
This issue should be reported at github.com/honeycombio/honeycomb-opentelemetry-go.  Unfortunately, we are unable to provide support for third-party developed tools and libraries.
