### ISSUE TITLE
Cant build 0.37.0 (c.meter.SyncInt64 undefined)

### ISSUE THREAD

**Issue by opengs** [open-telemetry/opentelemetry-go-contrib#3344]
Cant build a project with `v0.37.0` dependency.

This is the error I have while doing `go build -v`:
```
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc
# go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc
/src/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.37.0/config.go:75:40: c.meter.SyncInt64 undefined (type metric.Meter has no field or method SyncInt64)
```

Most probably, it was fixed by #3170 . Maybe with a new release, it will be fixed. Waiting for #3190

**Comment by opengs** [comment]
I will check it with new version later today

**Comment by Aneurysm9** [comment]
Compatible versions of modules from this repo [have been released](https://github.com/open-telemetry/opentelemetry-go-contrib/releases/tag/v1.13.0).

**Comment by opengs** [comment]
Everything works. Thanks!
