### ISSUE TITLE
0.38 release breaks with latest go.opentelemetry.io/otel/metric 

### ISSUE THREAD

**Issue by shane-kerr** [open-telemetry/opentelemetry-go-contrib#3348]
I'm using the latest `go.opentelemetry.io/otel/metric`, 0.35, which was released last week:

https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.12.0

From that release:
> Metric instruments to go.opentelemetry.io/otel/metric/instrument. These instruments are use as replacements of the depreacted go.opentelemetry.io/otel/metric/instrument/{asyncfloat64,asyncint64,syncfloat64,syncint64} packages.(https://github.com/open-telemetry/opentelemetry-go/pull/3575, https://github.com/open-telemetry/opentelemetry-go/pull/3586)

At least two of the contrib libraries break:

[go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc](https://github.com/open-telemetry/opentelemetry-go-contrib)
[go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp](https://github.com/open-telemetry/opentelemetry-go-contrib)

```
# go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc
/home/skerr/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.37.0/config.go:75:40: c.meter.SyncInt64 undefined (type metric.Meter has no field or method SyncInt64)
make: *** [Makefile:7: build] Error 2
```

```
# go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp
/home/skerr/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.37.0/handler.go:105:38: h.meter.SyncInt64 undefined (type metric.Meter has no field or method SyncInt64)
/home/skerr/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.37.0/handler.go:108:39: h.meter.SyncInt64 undefined (type metric.Meter has no field or method SyncInt64)
/home/skerr/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.37.0/handler.go:111:39: h.meter.SyncFloat64 undefined (type metric.Meter has no field or method SyncFloat64)
make: *** [Makefile:7: build] Error 2
```

**Comment by MrAlias** [comment]
Please use the latest contrib release: https://github.com/open-telemetry/opentelemetry-go-contrib/releases/tag/v1.13.0

Your issues should be fixed with this upgrade. Please reopen if not.
