### ISSUE TITLE
failed resource new; cannot merge resource due to conflicting Schema URL

### ISSUE THREAD

**Issue by Jbaukens** [open-telemetry/opentelemetry-go-contrib#3349]
Hello, 

I am getting the following error since i upgraded to a newer version

> res, err := resource.Merge(
		resource.Default(),
		resource.NewWithAttributes(
			semconv.SchemaURL,
			semconv.ServiceNameKey.String("name"),
		),
	)
	if err != nil {
		return fmt.Errorf("failed resource new; %w", err)
	}

Is there any change that could have broken this function that worked previously ?

go.opentelemetry.io/contrib/instrumentation/github.com/labstack/echo/otelecho v0.38.0
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.38.0
go.opentelemetry.io/otel v1.12.0
go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc v0.35.0
go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.12.0
go.opentelemetry.io/otel/metric v0.35.0
go.opentelemetry.io/otel/sdk v1.12.0
go.opentelemetry.io/otel/sdk/metric v0.35.0
go.opentelemetry.io/otel/trace v1.12.0

Thanks in advance

**Comment by MrAlias** [comment]
Which version of `semconv` are you using?

[The default resource uses `v1.17.0`](https://github.com/open-telemetry/opentelemetry-go/blob/6cb5718eaaed5c408c3bf4ad1aecee5c20ccdaa9/sdk/resource/builtin.go#L25). You should upgrade to that version to ensure compatibility.

**Comment by Jbaukens** [comment]
@MrAlias Thanks for the response, that version resolved the issue, i was still using 1.12.0 as its being marked as latest version on https://pkg.go.dev/go.opentelemetry.io/otel/semconv
