### ISSUE TITLE
[Prometheus Remote Write Exporter for Cortex] Add configuration option for selectors

### ISSUE THREAD

**Issue by ercl** [open-telemetry/opentelemetry-go-contrib#338]
Currently, the Prometheus Remote Write Exporter for Cortex defaults to using a Histogram selector. There should a be configuration option as mentioned in issue [#1139](https://github.com/open-telemetry/opentelemetry-go/issues/1139#issuecomment-690774659) (otel-go repo) so users can choose which selector they would like to use.

**Comment by MrAlias** [comment]
Closing, stale. The cortex exporter and example were remove in https://github.com/open-telemetry/opentelemetry-go-contrib/releases/tag/v1.5.0
