### ISSUE TITLE
[database/sql] Refactor ocsql for opentelemetry

### ISSUE THREAD

**Issue by j2gg0s** [open-telemetry/opentelemetry-go-contrib#349]
Our project trying to migrate from opencensus to opentelemtry.
So we fork ocsql and refactor it for opentelemetry in https://github.com/j2gg0s/otsql .

Opentelmetry has any plan about database/sql ?

**Comment by j2gg0s** [comment]
Related with #5

**Comment by MrAlias** [comment]
#5 captures the effort around this.
