### ISSUE TITLE
macaron instrumentation is missing v0.11 tag

### ISSUE THREAD

**Issue by vmihailenco** [open-telemetry/opentelemetry-go-contrib#352]
```bash
go get go.opentelemetry.io/contrib/instrumentation/macaron
go: downloading go.opentelemetry.io/contrib/instrumentation/macaron v0.6.1
pkg/mod/go.opentelemetry.io/contrib@v0.6.1/internal/trace/http.go:26:2: module go.opentelemetry.io/otel@latest found (v0.11.0), but does not contain package go.opentelemetry.io/otel/api/kv
```

**Comment by Aneurysm9** [comment]
It looks like that instrumentation was moved to `instrumentation/gopkg.in/macron.v1` in #92 but the module declaration in `go.mod` was not updated.  Using the old import path is giving a very old version of the module.

**Comment by amanbrar1999** [comment]
Is this issue free to pick up? @Aneurysm9  - cc @alolita

**Comment by MrAlias** [comment]
Closed by #356

**Comment by vmihailenco** [comment]
pkg.go.dev still says

```
“go.opentelemetry.io/contrib/instrumentation/gopkg.in/macaron.v1” is not a valid package or module. Were you looking for “go.opentelemetry.io/contrib/instrumentation/macaron”?
```

Did you tag fixed version?

**Comment by amanbrar1999** [comment]
Does this just require a git tag to be pushed called something like `instrumentation/gopkg.in/macaron.v1/v0.9.1`?
I don't have permission to push tags

**Comment by Aneurysm9** [comment]
Yes, this will require that we make a new release.  I intend to do this tonight or tomorrow, depending on how many outstanding PRs we can resolve today.
