### ISSUE TITLE
Sync DynamoDB instrumentation attributes with Python instrumentation

### ISSUE THREAD

**Issue by SenorMooMoo** [open-telemetry/opentelemetry-go-contrib#3521]
The current instrumentation of DynamoDB does not set the same attributes:

- Span name is different, does not include the operation like in Python (DynamoDB.GetItem vs DynamoDB)
- rpc.method is set to aws.operation in Go
- rpc.service is set to aws.service in Go

**Comment by dmathieu** [comment]
I haven't investigated this yet. But we should not "sync with python".
We should sync with the specification, if we don't yet: https://github.com/open-telemetry/opentelemetry-specification/blob/66f8c4c884d75ed3882af4f31ab036271bdd2a94/specification/trace/semantic_conventions/instrumentation/aws-sdk.md

**Comment by dmathieu** [comment]
It appears the span name will be fixed with #3582.
