### ISSUE TITLE
Stop setting HTTP status text

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-contrib#357]
In the HTTP instrumentation we need to not set the status text (they are inferable from the status code). This is to conform to https://github.com/open-telemetry/opentelemetry-specification/pull/972

**Comment by matej-g** [comment]
I had a look and it seems after https://github.com/open-telemetry/opentelemetry-go/pull/1194 no further action is necessary in the `contrib` repository. The method `HTTPAttributesFromHTTPStatusCode` from `go.opentelemetry.io/otel/semconv` used within HTTP instrumentation packages no longer includes status text attribute.

Is this correct?

**Comment by Aneurysm9** [comment]
> I had a look and it seems after [open-telemetry/opentelemetry-go#1194](https://github.com/open-telemetry/opentelemetry-go/pull/1194) no further action is necessary in the `contrib` repository. The method `HTTPAttributesFromHTTPStatusCode` from `go.opentelemetry.io/otel/semconv` used within HTTP instrumentation packages no longer includes status text attribute.
> 
> Is this correct?

That sounds correct.  I believe the `otelhttp` instrumentation delegated to the `semconv` package for the most part, so resolving the issue there should extend to `otelhttp` as well.

**Comment by MrAlias** [comment]
Resolved by https://github.com/open-telemetry/opentelemetry-go/pull/1194 and subsequent updates here.
