### ISSUE TITLE
[metrics] prometheus remote write exporter

### ISSUE THREAD

**Issue by liguozhong** [open-telemetry/opentelemetry-go-contrib#360]
https://github.com/open-telemetry/opentelemetry-go-contrib/tree/master/exporters/metric/cortex

https://github.com/open-telemetry/opentelemetry-go/tree/master/exporters

Please add cortex exporter to this project.

![image](https://user-images.githubusercontent.com/9583245/93978545-bb7eaf00-fdae-11ea-9005-4ad68b83733a.png)

**Comment by Aneurysm9** [comment]
I have moved this issue to the https://github.com/open-telemetry/opentelemetry-go-contrib repository.

The exporter, while named "cortex" is indeed intended to support the Prometheus remote write protocol generally.  This is called out at the [top of its `README.md`](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/master/exporters/metric/cortex/README.md)

The code in the screenshot you have linked does not align with [the code from the repository](https://github.com/open-telemetry/opentelemetry-go-contrib/blame/master/exporters/metric/cortex/cortex.go#L195).  If there are additional details you can provide regarding changes to the Prometheus remote write protocol and how we can ensure compatibility, we're happy to do what we can to help.

**Comment by liguozhong** [comment]
> I have moved this issue to the https://github.com/open-telemetry/opentelemetry-go-contrib repository.
> 
> The exporter, while named "cortex" is indeed intended to support the Prometheus remote write protocol generally. This is called out at the [top of its `README.md`](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/master/exporters/metric/cortex/README.md)
> 
> The code in the screenshot you have linked does not align with [the code from the repository](https://github.com/open-telemetry/opentelemetry-go-contrib/blame/master/exporters/metric/cortex/cortex.go#L195). If there are additional details you can provide regarding changes to the Prometheus remote write protocol and how we can ensure compatibility, we're happy to do what we can to help.

[metrics] cortex exporter: Upgrade Prometheus 2.21.0 dependency #365

**Comment by MrAlias** [comment]
Closing, stale. The cortex exporter and example were remove in https://github.com/open-telemetry/opentelemetry-go-contrib/releases/tag/v1.5.0
