### ISSUE TITLE
Error handler triggered twice for echo

### ISSUE THREAD

**Issue by stanleynguyen** [open-telemetry/opentelemetry-go-contrib#364]
Calling `c.Error`
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/b313ddb2989e21338560e24b9e9478c563017d20/instrumentation/github.com/labstack/echo/otelecho/echo.go#L84
and returning err from a middleware 
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/b313ddb2989e21338560e24b9e9478c563017d20/instrumentation/github.com/labstack/echo/otelecho/echo.go#L92
will trigger error handling twice.

I'm proposing to return nil instead

**Comment by stanleynguyen** [comment]
I will submit  PR if there's no suggestion otherwise

**Comment by MrAlias** [comment]
SGTM :+1:
