### ISSUE TITLE
otelgrpc: add WithSpanOptions

### ISSUE THREAD

**Issue by VazMike** [open-telemetry/opentelemetry-go-contrib#3683]
`otelgrpc` interceptors make spans, but those spans are not configurable. `otelhttp` has `WithSpanOptions` function which can be used to configure spans in otelhttp middleware both for transport and handler. `otelgrpc` interceptors ought to have the same functionality.

**Comment by dubonzi** [comment]
Went ahead and made a PR for this one, if you want to take a look.

**Comment by VazMike** [comment]
Thanks, it looks good.
