### ISSUE TITLE
Macaron plugin span name generator needed

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go-contrib#37]
See the original comment: 
https://github.com/open-telemetry/opentelemetry-go-contrib/pull/20/files#r419518073

This could be addressed with upstream changes to expose route information, but for now the plugin will generate span names with high cardinality.

**Comment by pellared** [comment]
This instrumentation library has been removed. See https://github.com/open-telemetry/opentelemetry-go-contrib/issues/5552
