### ISSUE TITLE
http.server.duration metric includes high cardinality attr: http.client_ip

### ISSUE THREAD

**Issue by vmihailenco** [open-telemetry/opentelemetry-go-contrib#3765]
Meaning that there are as many timeseries as you have visitors. Other http.server.* metrics have the same problem.

Those metrics also include such attrs as http.user_agent, net.sock.peer.addr, net.sock.peer.port, which should also be removed.

**Comment by rangzen** [comment]
For reference, https://grafana.com/blog/2022/02/15/what-are-cardinality-spikes-and-why-do-they-matter/

**Comment by rangzen** [comment]
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/net/http/otelhttp/handler.go#L102

**Comment by rangzen** [comment]
Wrong attributes: https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/net/http/otelhttp/handler.go#L217

**Comment by dmathieu** [comment]
We should split the `httpconv` methods to handle traces and metrics differently. Metrics need low cardinality, while the entire point of traces is to have high cardinality.
If we just remove the attributes, that will cause trace issues such as #3743.

**Comment by rangzen** [comment]
The correct attributes already exist, cf. #3182, and the last comment by @mlaflamm.

Before this commit, attributes were:
```
attributes := append(labeler.Get(), semconv.HTTPServerMetricAttributesFromHTTPRequest(h.operation, r)...)		￼
```

**Comment by youngbupark** [comment]
+1 This results in the high cardinality of request metrics and memory leak in my project. Currently, I am adding the workaround to set req.RemoteAddr to empty before calling otelhttp middleware. But, I hope it will be fixed in the next release.

**Comment by zsgilber** [comment]
Hi all, can we get an acknowledgement that this a real bug, and specifically that this current implementation of the metrics does not match the specification, which restricts those high cardinality attributes to just HTTP clients:

![image](https://github.com/open-telemetry/opentelemetry-go-contrib/assets/16533438/9ab10d49-65ef-4549-99c7-104b78b0c882)

**Comment by hasheddan** [comment]
Ran into this issue, which I imagine most folks are going to hit when upgrading. It is also applicable to `otelgrpc` (https://github.com/open-telemetry/opentelemetry-go-contrib/issues/3071). The cleanest solution I found in the short-term was to utilize views to filter out the high-cardinality attributes. Interestingly the `otel-collector` folks hit this same issue with its internal metrics. They employed a similar strategy: https://github.com/open-telemetry/opentelemetry-collector/pull/7543

**Comment by youngbupark** [comment]
> Another workaround is to get back to `go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.37.0`...

It won't work for my case. The older one doesn't emit status code I need to use. I am filtering out req.RemoteAddr now.

**Comment by davendu** [comment]
This is causing issues in our production environment. Our service is not reporting metrics due to the gRPC message too large. I converted the oversized gRPC message into JSON and found `otelhttp` 0.41.1 is [too heavy](https://github.com/open-telemetry/opentelemetry-go-contrib/assets/58910463/fdecdd82-8297-48d7-8680-06b38c689805).

It seems `http.server.request_content_length`, `http.server.response_content_length` and `http.server.duration` metrics are [recording user agent and ip & port info as attributes](https://github.com/open-telemetry/opentelemetry-go-contrib/assets/58910463/4bf98147-b137-4835-b63f-7c6e66afc6fd). It will cause pretty high cardinality, becuase each new attribute requires a whole new bucket, enriching the telemetry message.

Should we consider using a new set of attributes and limit cardinality for metrics?

https://github.com/open-telemetry/opentelemetry-go-contrib/blob/65caeb1a1392ef5d76fb39ada2acce74c3fe7341/instrumentation/net/http/otelhttp/handler.go#L226-L233

**Comment by krak3n** [comment]
We've had to implement our own middleware to remove these labels from metrics. There needs to be a clear distinction between attributes that are not safe for metrics but are fine for tracing.

**Comment by krak3n** [comment]
Thanks @dmathieu

We recently upgraded to the latest metric SDK versions (was a pain 😅) and have started using views. It seems the Go Metric SDK  does support a attribute filter function you can apply to a view:

https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric#Stream
https://pkg.go.dev/go.opentelemetry.io/otel/attribute#Filter

So this should already be possible to achieve and does seem like a nice solution, thanks for the hint 🙌

**Comment by jlordiales** [comment]
is this still considered an issue with the instrumentation library? Or with the way the `semconv` package defines client/server attributes?

The spec makes a clear distinction between metric and traces attributes so it feels this instrumentation should as well?

**Comment by dprotaso** [comment]
I believe this is fixed by https://github.com/open-telemetry/opentelemetry-go-contrib/pull/4277 ?

**Comment by dmathieu** [comment]
Yes.
