### ISSUE TITLE
Incompatible with with otel/metric@v0.37.0

### ISSUE THREAD

**Issue by xstephen95x** [open-telemetry/opentelemetry-go-contrib#3818]
### Description

Compilation and static checks will fail when using 
```go
"go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"
```
with
```go
go.opentelemetry.io/otel/metric v0.37.0
```

Due to a change in exported types between `v0.36.0` and `v0.37.0`

### Environment
In all environments

### Steps To Reproduce
Create a go mod file with:
```
go.opentelemetry.io/otel/metric v0.37.0
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.39.0
```
And call an interceptor function such as:
```go
_ = otelgrpc.StreamServerInterceptor(...)
```

### Expected behavior

This should compile, but it actually fails on line:
```
if c.rpcServerDuration, err = c.meter.Int64Histogram("rpc.server.duration", instrument.WithUnit(unit.Milliseconds)); err != nil {
```
as in v0.37.0, the expected parameter type of `instrument.WithUnit()` changes from a `unit.Unit` to a `string`.

This may be fixed in future versions of `otel/metric`, but a simple cast to `string()` also fixes the issue in this library.

**Comment by MrAlias** [comment]
Please use the latest version of the grpc instrumentation: https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.41.1

We do our best to match compatibility of the unstable modules, meaning v0.41.1 should be compatible with the v0.38.1 version of the otel metric API. We do not make any guarantee of compatibility outside of this best effort.

**Comment by xstephen95x** [comment]
Cool, thats fine. Just thought I would mention this here incase others were running into the same issue. 
Latest versions seem to fix the issue. Thank you for your time.
