### ISSUE TITLE
Consider using trace and meter test helpers from the OTEL repository

### ISSUE THREAD

**Issue by matej-g** [open-telemetry/opentelemetry-go-contrib#385]
The `contrib` repository currently implements it's own set of trace / meter test helpers in the `internal` directory. However, these helper are functionally mostly identical to the helpers which are presently already available in the `otel` repository and can be exported for use in the `contrib` repository.

Specifically, this would mean replacing
- `go.opentelemetry.io/contrib/internal/metric`
- `go.opentelemetry.io/contrib/internal/trace`

by 
- `go.opentelemetry.io/otel/api/metric/metrictest`
- `go.opentelemetry.io/otel/api/trace/tracetest`

respectively.

This will ensure having unified approach to test helpers and deduplication of code between `contrib` and `otel` repositories.

**Comment by matej-g** [comment]
So I think possibly this and the issues mentioned above (https://github.com/open-telemetry/opentelemetry-go-contrib/issues/385#issuecomment-704378772) can now be resolved in one go - seeing that those 2 issues are marked with p2 priority label.

What do you think @MrAlias? If you agree, I can take this.

**Comment by MrAlias** [comment]
> What do you think @MrAlias? If you agree, I can take this.

That sounds correct to me :+1:

**Comment by MrAlias** [comment]
@matej-g looks like I can only assign this issue to you as you are not a part of the OpenTelemetry Org (yet, you should [become a member](https://github.com/open-telemetry/community/blob/master/community-membership.md#member) :smile:). If you want, you can also comment on those issues and I'll be able to assign them to you.

**Comment by matej-g** [comment]
> @matej-g looks like I can only assign this issue to you as you are not a part of the OpenTelemetry Org (yet, you should [become a member](https://github.com/open-telemetry/community/blob/master/community-membership.md#member) 😄). If you want, you can also comment on those issues and I'll be able to assign them to you.

I'll comment on those, and look into that membership doc 🙂
