### ISSUE TITLE
otelgrpc: Allow adding custom attributes to otelgrpc metrics

### ISSUE THREAD

**Issue by inigohu** [open-telemetry/opentelemetry-go-contrib#3894]
### Problem Statement

The `otelgrpc` instrumentation does not allow adding custom attributes to the metrics.

### Proposed Solution

The `otelhttp` instrumentation, for example, provides a [labeler](https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp#Labeler) for adding custom attributes.

**Comment by rehanpfmr** [comment]
@inigohu @MrAlias 
Does this need to be updated on all instrumentations?
Let me know instrumentations which can be updated, I can take it.

**Comment by inigohu** [comment]
I see that the new `otelgrpc.StatsHandler` has been implemented. Would it be possible to include this feature? Maybe make [gRPCContextKey](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/3cecdcf33c4701a3abd8557d38ffde090a23b696/instrumentation/google.golang.org/grpc/otelgrpc/stats_handler.go#L34C2-L34C2) and [gRPCContext](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/3cecdcf33c4701a3abd8557d38ffde090a23b696/instrumentation/google.golang.org/grpc/otelgrpc/stats_handler.go#L36) public to pass custom attributes? WDYT @pellared

**Comment by upalinski** [comment]
Any updates on this? Had to copy-paste stats handler and allow custom attributes to be passed outside.

**Comment by pellared** [comment]
@upalinski Can you submit a PR? If so then  please make sure to include unit tests and sign EasyCLA.

**Comment by dmathieu** [comment]
I believe a similar approach to what's being done in net/http (the Labeler mentioned in the issue's description) would be fine, if you want to open a PR.

**Comment by duongcongtoai** [comment]
Hi, is there any update on this :D it is really useful for our usecase to tag extra labels to our grpc traffic

**Comment by inigohu** [comment]
Hi @dmathieu, I've opened a [PR](https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5133) if you want to take a look at it.
