### ISSUE TITLE
Instrumentation Should Not Set Global Defaults

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-contrib#392]
When instrumentation sets propagator defaults for the `global` package there is bound to be contention between concurrently run instrumentation. For example,

https://github.com/open-telemetry/opentelemetry-go-contrib/pull/391/files#diff-be6acc7451ab598bc6c0bbc0e02f8e4bR44-R45

and

https://github.com/open-telemetry/opentelemetry-go-contrib/pull/391/files#diff-8b8f618e742f8a44395347c761025034R70

Instrumentation should scope its use of propagators to a locally defined value and possible reverting to the global set value as a default.

**Comment by MrAlias** [comment]
On a closer read, this is only being done in tests and examples. Please disregard.

**Comment by Aneurysm9** [comment]
> On a closer read, this is only being done in tests and examples. Please disregard.

Still a fair point on the test at least.  I'm pushing up a change to avoid that.
