### ISSUE TITLE
Datadog exporter for tracing

### ISSUE THREAD

**Issue by HowJMay** [open-telemetry/opentelemetry-go-contrib#397]
The metric exporter of Datadog has been implemented in https://github.com/open-telemetry/opentelemetry-go-contrib/blob/0a44db8d6161e040c9ee785bd0d0fbc5fa13056a/exporters/metric/datadog/datadog.go#L37.
However, it is lack of an exporter for tracer. Will it be implemented in the future? Or there has been a way to connect opentelemetry tracer with Datadog?

**Comment by Aneurysm9** [comment]
I am not currently aware of a Datadog trace exporter for the OTel Go SDK.  Many vendors have implemented exporters outside of this repo, but I don't believe Datadog has one yet.

**Comment by askingcat** [comment]
Indeed, Datadog does not seem to currently have an exporter, yet.

I found a [basic implementation](https://github.com/krak3n/opentelemetry-go-datadog) - missing a few things and being not updated for 6 months - which seems to be copied from/based on [the official OpenCensus exporter](https://github.com/DataDog/opencensus-go-exporter-datadog).

I might be able - if time allows - to contribute an exporter based on the two above ones in the next days or weeks.

**Comment by MrAlias** [comment]
@HowJMay thanks for opening this issue, I imagine others want to know the answer to this as well. Unfortunately, this project is not intended host vendor exporters. There are some special circumstances, but a DataDaog trace exporter will need to be hosted some place other than this repository.
