### ISSUE TITLE
AWS Resource detector fails with an error if metadata not available

### ISSUE THREAD

**Issue by dackroyd** [open-telemetry/opentelemetry-go-contrib#398]
If the instance metadata is not available, no resource and an `unavailable EC2 client` error will be returned

https://github.com/open-telemetry/opentelemetry-go-contrib/blob/7e7d779/detectors/aws/aws.go#L42-L45

```
client := ec2metadata.New(session)
if !client.Available() {
	return nil, errors.New("unavailable EC2 client")
}
```

This is counter to the documented behaviour for resources which should be:

> Note the failure to detect any resource information MUST NOT be considered an error, whereas an error that occurs during an attempt to detect resource information SHOULD be considered an error.

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resource/sdk.md#detecting-resource-information-from-the-environment

A similar issue was raised (and fixed) with the ENV var detection in the main OTel library: https://github.com/open-telemetry/opentelemetry-go/issues/1114 / https://github.com/open-telemetry/opentelemetry-go/pull/1170

The GCP resource in this contrib library appears to implement detection correctly, returning no error:

https://github.com/open-telemetry/opentelemetry-go-contrib/blob/7e7d779/detectors/gcp/gce.go#L38-L40
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/master/detectors/gcp/gce.go#L102-L104

```
if !metadata.OnGCE() {
	return nil, nil
}
```

```
if _, undefined := err.(metadata.NotDefinedError); undefined {
	return false
}
```

**Comment by MrAlias** [comment]
Instead of

```
if _, undefined := err.(metadata.NotDefinedError); undefined {
	return false
}
```

I would use the new `errors` package functionality:

```
if errors.Is(err, metadata.NotDefinedError)
	return false
}
```

Otherwise, this looks like a good fix. Thanks for opening it.

**Comment by dackroyd** [comment]
To clarify, the code snippets I included are the _existing_ code for the aws and gce detectors: none of that was suggested fix. The `err.(metadata.NotDefinedError)` is the current code in the gce detector

**Comment by dackroyd** [comment]
As for a suggested fix, this might be appropriate:

```
client := ec2metadata.New(session)
if !client.Available() {
	return nil, nil
}
```

**Comment by MrAlias** [comment]
Ah, my mistake @dackroyd!

Would you be willing to put together a PR with this?

**Comment by dackroyd** [comment]
I'd be happy to push that change 👍

**Comment by MrAlias** [comment]
> I'd be happy to push that change

Awesome, thanks for the help! :smile:
