### ISSUE TITLE
otelhttptrace.NewClientTrace does not nest spans properly with otelhttp.NewTransport

### ISSUE THREAD

**Issue by seh** [open-telemetry/opentelemetry-go-contrib#399]
We have at least two facilities in this repository for producing trace spans from HTTP requests:
- [`otelhttptrace.NewClientTrace`](https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace#NewClientTrace) (or the wrapper function [`W3C`](url))  
  Interacts with `net/http/httptrace.WithClientTrace`.
- [`otelhttp.NewTransport`](https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp#NewTransport)
  Interacts with [`net/http.Client`](https://golang.org/pkg/net/http/#Client) via the [`RoundTripper`](https://golang.org/pkg/net/http/#RoundTripper) interface.

It's appealing to use these two together, but the resulting spans don't nest properly, per the following example:

<img width="885" alt="Honeycomb Spans (siblings)" src="https://user-images.githubusercontent.com/175841/95899262-4aec0200-0d5e-11eb-8ecf-ef388ce8ee05.png">

In this image, note how the span named “GET” is created by `otelhttptrace.W3C`. The next set of six spans are created by `otelhttp.NewTransport`. Best would be if those latter six spans were nested under the "GET" span. The offsets and durations suggest the intended subsumption, but the hierarchy evident in the tree lines says otherwise.

The trouble is that `otelhttptrace.W3C` requires a parent `Context` to be supplied that winds up being unrelated to the `Context` used by the `RoundTripper` created by `otelhttp.NewTransport`.

Should these two libraries work better together? Are we only supposed to use one or the other, but not both at the same time?

**Comment by MrAlias** [comment]
@seh do you have code that you can post that reproduces the above trace?

**Comment by seh** [comment]
Yes, please see [the _example/client/client.go_ file](https://github.com/honeycombio/opentelemetry-exporter-go/blob/8837c0058a34af59cdf265855c6565118017be2d/example/client/client.go) as part of honeycombio/opentelemetry-exporter-go#95.

**Comment by ldemailly** [comment]
I just stepped on the same problem - any solution/suggestions/workarounds?

https://github.com/fortio/fortiotel/blob/main/simple/otel_httptrace_simple.go

<img width="379" alt="Screen Shot 2022-12-21 at 2 16 38 PM" src="https://user-images.githubusercontent.com/3664595/209012999-4beb7ed8-52e5-48f1-9bdb-69e4b533ecc3.png">

**Comment by Alkorin** [comment]
I did that in my code:

```
	otelhttp.NewTransport(
		http.DefaultClient.Transport,
		otelhttp.WithClientTrace(func(ctx context.Context) *httptrace.ClientTrace {
			return otelhttptrace.NewClientTrace(ctx)
		}),
	)
```

It fixes the issue

**Comment by ldemailly** [comment]
Thanks @Alkorin - this indeed fixed the issue - just need to be documented then I guess

https://github.com/fortio/fortiotel/commit/3fb1155c865f91931042b0085df7263a4fd2ca51

**Comment by seh** [comment]
> It fixes the issue

Could this be simplified?
```go
otelhttp.NewTransport(
	http.DefaultTransport,
	otelhttp.WithClientTrace(otelhttptrace.NewClientTrace))
```

**Comment by dmathieu** [comment]
It definitely can. I don't how I missed that. Do you want to open a fix?

**Comment by seh** [comment]
> Do you want to open a fix?

Yes, I'll do so now.
