### ISSUE TITLE
autoexport: Support `none` as exporter

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-contrib#4013]
Is there a no-op exporter we can use with autoexport?

_Originally posted by @james-callahan in https://github.com/open-telemetry/opentelemetry-go-contrib/issues/2753#issuecomment-1592139673_

**Comment by pellared** [comment]
@MikeGoldsmith Do you want to work on it?

**Comment by pellared** [comment]
How do you prefer `func NewSpanExporter(ctx context.Context, opts ...Option) (trace.SpanExporter, error) {` to behave when user selects `none`?

I see following possibilities

## Option A - return a NOOP exporter

Pros:

1. Ease of use by the user - no special handling
1. This would align with the behavior of `autoprop.NewTextMapPropagator`

Cons:

1. Performance downgrade. If `none` is selected then there may be no need to even setup a metrics provider. How the user would know that a "None" (noop) exporter was returned. MITIGATION: We cn add a `IsNone` function so that the user could handle the special case when `none` is selected.

## Option B - `return nil, nil`

Pros:

1. Easy to implement

Cons:

1. It is bug prone for the user. It may be easy for the user to configure a `nil` exporter as  `return nil, nil` is not very popular (but it happens). Users may not read the documentation and not handle this case.
2. It requires handling a `if exp == nil` case

## Option C - `return nil, ErrNone`

Pros:

1. Looks idiomatic
2. If user does not handle the exporter `err == ErrNone` he will handle it like an error. It is less bug prone than option A.

Cons:

1. This is not really an error.
2. The error handling code may look worse than for option A. In most cases setting a NOOP exporter should be good enought.


I am leaning towards Option A. @open-telemetry/go-approvers, WDYT?

**Comment by dashpole** [comment]
I prefer A as well.
