### ISSUE TITLE
otelhttp: Transport.spanStartOptions should be a `func(ctx context.Context) []trace.SpanStartOption`

### ISSUE THREAD

**Issue by mlcdf** [open-telemetry/opentelemetry-go-contrib#4015]
### Problem Statement

Hello folks :)

I have a few information stored into the request context (like request IDs) and I can't add them to the attributes in SpanOptions since I don't have access to the request context when creating a new Transport.

https://github.com/open-telemetry/opentelemetry-go-contrib/blob/849072ef827b4abab754253e1e63e7b410a31084/instrumentation/net/http/otelhttp/transport.go#L37

IE, the code below won't work because ctx is not defined (and can't be).
```
otelhttp.NewTransport(next, otelhttp.WithSpanOptions(
	trace.WithAttributes(
		attribute.Key(gwheaders.RegionHeader).String(region.FromContext(ctx)),
                ...
	),
)
```

### Proposed Solution

Follow the footsteps of `Transport.clientTrace`:
- change `spanStartOptions` from `[]trace.SpanStartOption` to `func(ctx context.Context) []trace.SpanStartOption`
- change the signature for the `WithSpanOptions` func accordingly
- call this function in `Roundtrip`

```
otelhttp.NewTransport(next, otelhttp.WithSpanOptions(
	func(ctx context.Context) []trace.SpanStartOption {
		trace.WithAttributes(
			attribute.Key(gwheaders.RegionHeader).String(region.FromContext(ctx))
		),
	}),
)
```

#### Alternatives

Haven't found one.

#### Prior Art

Already done the following fields of the same struct:
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/849072ef827b4abab754253e1e63e7b410a31084/instrumentation/net/http/otelhttp/transport.go#L39
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/849072ef827b4abab754253e1e63e7b410a31084/instrumentation/net/http/otelhttp/transport.go#L40

### Additional Context

I can work on a PR :)

**Comment by dmathieu** [comment]
It looks like you're looking for the `WithSpanOptions` config:
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/net/http/otelhttp/config.go#L138

**Comment by dmathieu** [comment]
I feel like reusing WithSpanOptions isn't a bit too specific here. There are many things folks may want to do on a span/request after it started.
Right now, the best/only way to do this is with an Handler on top of the otelhttp one.

How about something more generic, like:

```golang
otelhttp.NewTransport(next, otelhttp.WithSpanAndRequest(func(ctx context.context, span trace.Span, req *http.Request) {
	span.SetAttributes(
		attribute.Key(gwheaders.RegionHeader).String(region.FromContext(ctx)),
	)
}))
```

The method name seems wrong. But I don't have anything better yet.

**Comment by mlcdf** [comment]
Ooooh right! I hadn't thought about wrapping the Transport/Handler to add attributes from there!

```go
// The RoundTripperFunc type is an adapter to allow the use of ordinary
// functions as RoundTrippers. If f is a function with the appropriate
// signature, RountTripperFunc(f) is a RoundTripper that calls f.
type RoundTripperFunc func(req *http.Request) (*http.Response, error)

// RoundTrip implements the RoundTripper interface.
func (rt RoundTripperFunc) RoundTrip(r *http.Request) (*http.Response, error) {
	return rt(r)
}

var _ http.RoundTripper = (*RoundTripperFunc)(nil)

func WithTracing(next http.RoundTripper) http.RoundTripper {
	rt := RoundTripperFunc(func(req *http.Request) (*http.Response, error) {
		ctx := req.Context()
		span := trace.SpanFromContext(ctx)

		span.SetAttributes(
			attribute.Key(gwheaders.RegionHeader).String(region.FromContext(ctx)),
		)

		req = req.WithContext(ctx)
		return next.RoundTrip(req)
	})

	return otelhttp.NewTransport(rt)
}

```

I tested this, it works great.

I like your proposal (don't have a better name either). But since I found a workaround, I'm not really in the need for this

**Comment by mlcdf** [comment]
I'm closing this, I think the workaround is actually pretty decent.
