### ISSUE TITLE
net/http client instrumentation - child span(s) not being created

### ISSUE THREAD

**Issue by Kaushal28** [open-telemetry/opentelemetry-go-contrib#4046]
I have a `net/http` client that makes API calls to third party APIs and I want to instrument it. I have created a parent span and I am using its context similar to the client example given in `otelhttp` (https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/net/http/otelhttp/example/client/client.go#L69)

```Go

client := &http.Client{Timeout: time.Second * 2, Transport: otelhttp.NewTransport(http.DefaultTransport)}

req, err := http.NewRequestWithContext(ctx, "GET", node+"/ping", http.NoBody)  // ctx has parent span.
if err != nil {...}

resp, err := client.Do(req)
if err != nil {...}
```

But I am not getting any child spans created by the `otelhttp` for the `GET` request I am performing. I am only seeing the span that I created (parent).

What am I missing here? Thanks.

**Comment by dmathieu** [comment]
Do you have a full running example, including SDK setup? (maybe exporting data to stdout, so it can be used for debug more easily).

**Comment by Kaushal28** [comment]
@dmathieu I figured out the root cause. It happens when I don't read the response. So in this example, if you comment out the lines 87 and 88(https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/net/http/otelhttp/example/client/client.go#L87), it won't create a `HTTP GET` child span. I tried reproducing it in my local using this example.

**Comment by dmathieu** [comment]
Well, you don't have to read it. But you must close it.

> The client must close the response body when finished with it:

https://pkg.go.dev/net/http#pkg-overview
