### ISSUE TITLE
Remove otelbeego

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-contrib#4059]
### Problem Statement

The https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation/github.com/astaxie/beego/otelbeego instrumentation library instruments https://pkg.go.dev/github.com/astaxie/beego library that is no longer maintained (old version with security vulns.

The latest version of `beego` already has some OTel support e.g. https://pkg.go.dev/github.com/beego/beego/v2@v2.1.0/client/httplib/filter/opentelemetry and https://pkg.go.dev/github.com/beego/beego/v2/client/orm/filter/opentelemetry

There was already an issue to add OTel instrumentation into beego: https://github.com/beego/beego/issues/4945. This approach would be more inline with our current recommendation.

### Proposed Solution

Deprecate https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation/github.com/astaxie/beego/otelbeego in next release.

Afterwards, as part of a subsequent release, remove the module from codebase and from the OTel Registry (https://opentelemetry.io/ecosystem/registry/adding/)

**Comment by MrAlias** [comment]
Given we never had anyone raise their hand to dedicate themselves as a maintainer: https://github.com/open-telemetry/opentelemetry-go-contrib/blob/9437f9bf6a302c0d4728e9047894ba7c1de3bb72/CODEOWNERS#L30

This seems appropriate to me :+1:

**Comment by dmathieu** [comment]
👍 
And close https://github.com/open-telemetry/opentelemetry-go-contrib/pull/1525

**Comment by pellared** [comment]
Closing per https://github.com/open-telemetry/opentelemetry-go-contrib/pull/4295
