### ISSUE TITLE
autoexport: Improve package documentation

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-contrib#4102]
The documentation does not tell what env vars are supported, what are the defaults etc.

PS. The Go module is not released yet: https://pkg.go.dev/go.opentelemetry.io/contrib/exporters/autoexport

**Comment by MrAlias** [comment]
> PS. The Go module is not released yet: https://pkg.go.dev/github.com/honeycombio/opentelemetry-go-contrib/exporters/autoexport

That's the Honeycomb package. Did you mean thisttps://pkg.go.dev/go.opentelemetry.io/contrib/exporters/autoexport>
