### ISSUE TITLE
autoexport: Add metrics support

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-contrib#4131]
Make sure to support `OTEL_METRICS_EXPORTER` and handle `none`, `otlp`, ~~`prometheus`~~.

Reference https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/sdk-environment-variables.md#exporter-selection

**Comment by punya** [comment]
Is someone working on this, or is it open for a contribution?

**Comment by MrAlias** [comment]
It is open for contribution. Should I assign it to you @punya?
