### ISSUE TITLE
otelhttp instrument constantly producing errors

### ISSUE THREAD

**Issue by dustyhorizon** [open-telemetry/opentelemetry-go-contrib#417]
I am currently using the otelhttp instrument following the example at https://github.com/open-telemetry/opentelemetry-go-contrib/blob/master/instrumentation/net/http/otelhttp/example/server/server.go

However, whenever a trace happens, a warning / non-fatal error keeps appearing in my logs

`rpc error: code = Internal desc = grpc: error unmarshalling request: proto: StringKeyValue: wiretype end group for non-group`

I am using the otel exporter and the otel collector is running v0.13.1 but this message was there since v0.12.0

**Comment by Aneurysm9** [comment]
Can you construct a minimal reproduction?  Is that error at the collector or the exporter side?  It looks like it would be collector-side since no protobuf unmarshalling would be happening in the `otelhttp` instrumentation or even the SDK's `otlp` exporter.  If we're constructing and sending malformed OTLP a minimal reproduction, ideally without the `otelhttp` instrumentation, would help understand the issue better.

**Comment by dustyhorizon** [comment]
In my application I am also using the otelgrpc client interceptors as this application also acts as a gRPC client to my other internal services.

I flagged otelhttp because prior to its addition, no such warnings were found.

OTELHttp is implemented as a middleware in my application as such
`http.Handle("/graphql", otelhttp.NewHandler(graphqlHandler, "/graphql"))`

I am using the otel exporter following the example shown in https://github.com/open-telemetry/opentelemetry-go-contrib/blob/master/instrumentation/net/http/otelhttp/example/server/server.go instead of the stdout exporter

Apologies but I do not have a simple reproducible code right now

**Comment by MrAlias** [comment]
This is likely related to the backwards incompatibilities of the v0.5.0 release of the OTLP used by the OTLP exporter. We have merged changes in the opentelemetry-go project to upgrade but have not released them yet.

**Comment by dustyhorizon** [comment]
closing this the error is not popping up after upgrading to v0.14.0
