### ISSUE TITLE
otelhttp is not concurrent-safe

### ISSUE THREAD

**Issue by Kaushal28** [open-telemetry/opentelemetry-go-contrib#4200]
### Description

I want to enable tracing for `net/http`. So for `http` client, I am setting the transport as following:

```go
client.Transport = otelhttp.NewTransport(http.DefaultTransport)
```

Also, I have set the following at application level (I think otel sets `TextMapPropagator` at global level, so that should not be the issue anyways).

```go
otel.SetTextMapPropagator(propagation.NewCompositeTextMapPropagator(propagation.TraceContext{}, propagation.Baggage{}))
```

All the things are exactly similar to this example: https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/net/http/otelhttp/example/client/client.go

In my code, there might be concurrent calls that accesses this `client` from separate go routines.

It's working fine when no concurrency involved. But I am getting the following fatal errors in case of concurrency:

```
fatal error: concurrent map writes

goroutine 4646 [running]:
net/textproto.MIMEHeader.Set(...)
        /usr/local/go/src/net/textproto/header.go:22
net/http.Header.Set(...)
        /usr/local/go/src/net/http/header.go:40
go.opentelemetry.io/otel/propagation.HeaderCarrier.Set(0x21aa16f?, {0x21a8720?, 0xc000cf89c8?}, {0xc0003fa680, 0x37})
        /src/vendor/go.opentelemetry.io/otel/propagation/propagation.go:79 +0x97
go.opentelemetry.io/otel/propagation.TraceContext.Inject({}, {0x24be1f0?, 0xc00125b680?}, {0x24bd400, 0xc0014f4d50})
        /src/vendor/go.opentelemetry.io/otel/propagation/trace_context.go:65 +0x41c
go.opentelemetry.io/otel/propagation.compositeTextMapPropagator.Inject(...)
        /src/vendor/go.opentelemetry.io/otel/propagation/propagation.go:117
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Transport).RoundTrip(0xc000c5fb90, 0xc000c4d800)
        /src/vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/transport.go:114 +0x5c3
net/http.send(0xc000c4d800, {0x24a3da0, 0xc000c5fb90}, {0x8?, 0x211c0a0?, 0x0?})
        /usr/local/go/src/net/http/client.go:252 +0x5f7
net/http.(*Client).send(0xc00125b5c0, 0xc000c4d800, {0xc0006ecfc0?, 0x453c76?, 0x0?})
        /usr/local/go/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc00125b5c0, 0xc000c4d800)
        /usr/local/go/src/net/http/client.go:716 +0x8fb
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:582
```

This seems to be because of this in `propagation.go:79`:

```go
func (hc HeaderCarrier) Set(key string, value string) {
	http.Header(hc).Set(key, value)
}
```

There is some similar mention here as well: https://github.com/open-telemetry/opentelemetry-go-contrib/issues/3893

So is this an issue in how I am setting up the transport in my HTTP clients or in open telemetry code mentioned above (maybe a lock is required there)?

### Environment

- OS: Ubuntu
- Architecture: x86,
- Go Version: 1.20.5
- `go.opentelemetry.io/contrib` version: `go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.42.0`
### Expected behavior

It should work when ran concurrently.

@pellared @dmathieu

**Comment by dmathieu** [comment]
I've been giving this a try with the following test:

```golang
func TestClientConcurrentSafe(t *testing.T) {
	sr := tracetest.NewSpanRecorder()
	otel.SetTextMapPropagator(propagation.NewCompositeTextMapPropagator(propagation.TraceContext{}, propagation.Baggage{}))
	provider := trace.NewTracerProvider(trace.WithSpanProcessor(sr))

	tracer := provider.Tracer("")
	ctx, span := tracer.Start(context.Background(), "http requests")

	content := []byte("Hello, world!")

	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if _, err := w.Write(content); err != nil {
			t.Fatal(err)
		}
	}))
	defer ts.Close()

	var wg sync.WaitGroup
	for i := 1; i <= 5; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			res, err := otelhttp.Get(ctx, ts.URL)
			assert.NoError(t, err)
			res.Body.Close()
		}()
	}
	wg.Wait()

	span.End()

	spans := sr.Ended()
	require.Equal(t, 6, len(spans))
}
```

(with and without the `SetTextMapPropagator` on line 2)

And I'm not seeing any race condition.

```
go test -v ./... -race -run TestClientConcurrentSafe
=== RUN   TestClientConcurrentSafe
--- PASS: TestClientConcurrentSafe (0.00s)
PASS
ok      go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/test      2.159s
```

**Comment by MrAlias** [comment]
@Kaushal28 can you please provide a minimal example of code that reproduces the panic you were seeing?

**Comment by dmathieu** [comment]
Ping @Kaushal28 for reproduction case

**Comment by Kaushal28** [comment]
@dmathieu Sorry for late reply. Apparently I just found that otel accesses headers object, and I had common headers object between multiple goroutines. So this is not an issue in otel. Thanks for all the support.
