### ISSUE TITLE
Update all resource detectors use of semconv

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-contrib#4264]
Match what is released with v1.17.0 of the core repo.

- [x] `go.opentelemetry.io/contrib/detectors/gcp`
  - https://github.com/open-telemetry/opentelemetry-go-contrib/pull/4263
- [x] `go.opentelemetry.io/contrib/detectors/aws/ec2`
  - https://github.com/open-telemetry/opentelemetry-go-contrib/pull/4265
- [x] `go.opentelemetry.io/contrib/detectors/aws/ecs`
  - https://github.com/open-telemetry/opentelemetry-go-contrib/pull/4265
- [x] `go.opentelemetry.io/contrib/detectors/aws/eks`
  - https://github.com/open-telemetry/opentelemetry-go-contrib/pull/4265
- [x] `go.opentelemetry.io/contrib/detectors/aws/lambda`
  - https://github.com/open-telemetry/opentelemetry-go-contrib/pull/4265

**Comment by MrAlias** [comment]
@dashpole is going to update GCP after https://github.com/open-telemetry/opentelemetry-go-contrib/pull/4198#pullrequestreview-1605278638

**Comment by pkwarren** [comment]
NOTE: The GCP detector was updated in https://github.com/open-telemetry/opentelemetry-go-contrib/pull/4263. We hit resource merge issues on upgrade to opentelemetry-go and needed to pin that version (or later). Is a new release planned to make it easier for users to upgrade to a compatible version of opentelemetry-go-contrib?

**Comment by MrAlias** [comment]
done

**Comment by pkwarren** [comment]
Thank you!
