### ISSUE TITLE
otelgin.Middleware seems not extract request header "tracestate" and make itself as a child span

### ISSUE THREAD

**Issue by mong0520** [open-telemetry/opentelemetry-go-contrib#4279]
### Description
I am doing a simple lab to demonstrate how cross services tracing works.
In this scenario, I have a API-Gateway(kong) setup and a hello-world API which is served by GIN as the upstream of that gateway.
```
api-gw ----> my_service (gin)
```

In api-gateway, I integrate OpenTelemetry and pretty sure the gateway carries the request header '**Tracestate**' with the the `my_service`.

There is the code slice from `my_service`
```go
func installExportPipeline(ctx context.Context) (func(context.Context) error, error) {
	client := otlptracehttp.NewClient(otlptracehttp.WithEndpoint(my_endpoint))
	exporter, err := otlptrace.New(ctx, client)
	if err != nil {
		return nil, fmt.Errorf("creating OTLP trace exporter: %w", err)
	}

	tracerProvider := sdktrace.NewTracerProvider(
		sdktrace.WithBatcher(exporter),
		sdktrace.WithResource(newResource()),
	)
	otel.SetTracerProvider(tracerProvider)

	return tracerProvider.Shutdown, nil
}
...(skip)
shutdown, err := installExportPipeline(ctx)
...(skip)
router := gin.New()
router.Use(otelgin.Middleware("eventhook"))
router.GET("/hello", func(c *gin.Context) {
    // return simple text
})
```

However, after I checked the Jaeger dashboard, the trace of `/hello` is separated to two traces, one for api-gw and the other for my_service.

### Environment

- OS: macOS
- Architecture: M1
- Go Version: 1.19
- `otelgin` version: v0.43.0

### Steps To Reproduce

n/a

### Expected behavior

otelgin can extract request header correctly and determine itself is a root or child span.

**Comment by dmathieu** [comment]
The gin middleware does extract the trace context from the request.
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/github.com/gin-gonic/gin/otelgin/gintrace.go#L70

Have you checked the TraceContext propagator is properly set on your application, and that the request does include the header?

**Comment by mong0520** [comment]
Thank you @dmathieu for the quick reply.
> Have you checked the TraceContext propagator is properly set on your application, and that the request does include the header?

Would you please hint any example for that? I am new to OpenTelemetry's world and only follows this example: https://github.com/open-telemetry/opentelemetry-go/blob/exporters/otlp/otlptrace/v1.17.0/exporters/otlp/otlptrace/otlptracehttp/example_test.go#L68 to setup my application

**Comment by dmathieu** [comment]
You can see how to explicitly set a propagator in this doc: https://opentelemetry.io/docs/instrumentation/go/manual/#propagators-and-context

**Comment by mong0520** [comment]
It worked after simply adding this line. Thank you and I am closing this issue.
```go
otel.SetTextMapPropagator(propagation.TraceContext{})
```
