### ISSUE TITLE
Dependency size for resource detection

### ISSUE THREAD

**Issue by dackroyd** [open-telemetry/opentelemetry-go-contrib#429]
Running on AWS (and other for detectors like GCP) requires that the relevant dependency is pulled in, even if the application doesn't use the library for any other purpose than detecting the host details. These libraries can be very heavy: the AWS SDK for Go is over 130 MB. While the compiled size would be far smaller based on the limited usage, the library still needs to be fetched if not cached.

To fetch the AWS metadata required to satisfy the detector, basic HTTP requests are sufficient, which could avoid the dependency needing to be included in this (fairly common?) case. There is obviously an added maintenance overhead by re-implementing this, but avoids a large dependency.

Alternatively, it could be that adding this to application code isn't intended, and instead the relevant detectors should be added to the OTel agent running on the same host? This would also avoid needing to include the dependency in an application which doesn't otherwise use the SDK. That may require customising the OTel agent for the deployment to ensure the right detectors are run in that environment?

**Comment by MrAlias** [comment]
Thanks for opening the issue. We would like to provide a lightweight codebase but we cannot allocate our limited development resources to tracking a vendors API and duplicating portions of their SDK in this project. I cannot speak for the OTel agent, but that sounds like a reasonable solution if you would like to propose it in that project.

**Comment by dackroyd** [comment]
Thanks @MrAlias, I understand. I'll look into support at the agent level 👍
