### ISSUE TITLE
Metric test helpers needed

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go-contrib#43]
This repo has a copy of the trace testing helpers from the main repository. This repo does not have a copy of the metric testing helpers. We should add test helpers to support testing metrics in this repository, but first some code should be exposed from the main repository (e.g., AsyncInstrumentState).

**Comment by matej-g** [comment]
Would take this toget with #385

**Comment by MrAlias** [comment]
Closing, stale. A manual reader and the `metricdatatest` package are used to test expected metric exports.
