### ISSUE TITLE
otelgrpc: Deprecate the interceptors 

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-contrib#4318]
> I think we should also update the existing examples to use the new instrumentation.
> 
> I propose to:
> 
> 1. Merge this PR
> 2. Create an issue for https://github.com/open-telemetry/opentelemetry-go-contrib/pull/3002/files#r1209293763
> 3. Update the existing examples to use the new functionality.
> 4. Deprecate the interceptors so that they are available in next release.
> 5. After the next release remove the interceptors. 

@open-telemetry/go-approvers please upvote/downvote if you agree or not. Feel free to leave any additional feedback.

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-go-contrib/pull/3002#pullrequestreview-1613182957_

1. Blocked by https://github.com/open-telemetry/opentelemetry-go-contrib/issues/4316
2. Deprecate the interceptors 
3. Update the docs so that grpc.StatsHandler is the first-class citizen

**Comment by dashpole** [comment]
I think we also need to add metrics to the StatsHandler implementation.

**Comment by pellared** [comment]
FYI @fatsheep9146

**Comment by pellared** [comment]
> I think we also need to add metrics to the StatsHandler implementation.

Covered by https://github.com/open-telemetry/opentelemetry-go-contrib/issues/4316
