### ISSUE TITLE
What integrations should be contributed here?

### ISSUE THREAD

**Issue by sagikazarmark** [open-telemetry/opentelemetry-go-contrib#432]
I'm working on OpenTelemetry for [Go Kit](gokit.io/) and I'm not entirely sure where I should contribute it:

- Should I try to submit it to the Go Kit project
- Should I submit it here first (and probably later to Go Kit)

Both of those make sense to me, so I wonder what you consider to be the best practice.

If there is one (or will be one), adding it to the contributing guide could help people deciding this question.

**Comment by MrAlias** [comment]
Thanks for jumping in and working on this. If the instrumentation you plan to write is going to be able to be plugged into the framework I think it is a decent idea to start here. Including it in the instrumented library will add an extra burden on that project at this point given the early phase OpenTelemetry is in, but it would make sense to include it there if the instrumentation will not be written in a plug-able way.

To ensure there isn't too much churn in the implementation, can you outline your approach to building the instrumentation here and maybe list any prior art you are referencing. Mirroring our other issues of this type might be useful (e.g. https://github.com/open-telemetry/opentelemetry-go-contrib/issues/80)

> If there is one (or will be one), adding it to the contributing guide could help people deciding this question.

Agreed. This is something we just recently identified this as something to address across OpenTelemetry. I've opened https://github.com/open-telemetry/opentelemetry-go-contrib/issues/433 to track this meta-issue.

**Comment by sagikazarmark** [comment]
Thanks @MrAlias 

I'll open an issue before submitting a PR. It's definitely going to be pluggable.

One potential issue I can see with implementing integrations in this repo though is that tracking framework compatibility, issues, version compatibility, etc this far away from the original projects could potentially cause all kinds of issues and delay the solution for them. For example, if the framework breaks backwards compatibility, developers will not necessarily keep the otel integration in mind or even if they do, it's potentially harder to coordinate. Maybe I'm too paranoid, I don't know.

In any case, I agree that it makes sense to start here, so I'll do that.

**Comment by MrAlias** [comment]
> One potential issue I can see with implementing integrations in this repo though is that tracking framework compatibility, issues, version compatibility, etc this far away from the original projects could potentially cause all kinds of issues and delay the solution for them. For example, if the framework breaks backwards compatibility, developers will not necessarily keep the otel integration in mind or even if they do, it's potentially harder to coordinate. Maybe I'm too paranoid, I don't know.


This is a valid concern for sure and something most instrumentation struggles with. I think you have the correct vision of where this should ultimately go.

Going to close this in favor of tracking the work in #434. Please reopen if you need to address other meta-concerns.
