### ISSUE TITLE
Prometheus bridge: Verify that prometheus start timestamps are working correctly

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-go-contrib#4354]
### Problem Statement

Now that support for creation timestamps exists in the promethues client, we should update to the latest version of the client, and verify that creation timestamps are working as expected.

https://github.com/prometheus/client_golang/releases/tag/v1.17.0

https://github.com/prometheus/client_golang/pull/1313

### Proposed Solution

This should be done with a new unit test.

**Comment by hiroyaonoe** [comment]
I want to work on this issue.
I read these.
- https://github.com/prometheus/client_golang/pull/1313
- https://github.com/ArthurSens/proposals/blob/ab2516375639ea69305bbefe8974d7cc91d71cf9/proposals/2023-06-13_created-timestamp.md
- https://pkg.go.dev/go.opentelemetry.io/contrib/bridges/prometheus

I'll add and update unit tests in https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/bridges/prometheus/producer_test.go
