### ISSUE TITLE
config: Parse model from JSON

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-contrib#4412]
Implement https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/file-configuration.md#parse for JSON.

**Comment by pellared** [comment]
PTAL @codeboten

**Comment by pellared** [comment]
Changing the description to update the documentation instead of adding a new function.

CC @carrbs @codeboten

**Comment by pellared** [comment]
@carrbs Good finding 👍 

Actually it should implement this: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/file-configuration.md#parse

I will update the description

**Comment by codeboten** [comment]
> Take notice that the specification currently requires only supporting YAML. Making as blocker per spec.

The specification mentions both JSON or YAML. Are you saying that since only one is required and YAML is preferred if nether/both are supported, then we should only implement YAML parsing? Just trying to clarify what blocked on specification means here

**Comment by pellared** [comment]
> TODO: decide if JSON file format is required

**Comment by codeboten** [comment]
@pellared ah fair... i missed this, as it goes against what's written further down :D

**Comment by pellared** [comment]
Closing the issue for now. We can reopen it if needed.
