### ISSUE TITLE
config: Prepare for release

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-contrib#4415]
1. Create a pkg.go.dev documentation by following https://github.com/open-telemetry/opentelemetry-go/blob/main/CONTRIBUTING.md#documentation.
2. Add a testable example.
3. Update `versions.yaml` so that the config module will be published during next release.

**Comment by pellared** [comment]
CC @codeboten

**Comment by codeboten** [comment]
happy to take this one, please assign it to me :)
