### ISSUE TITLE
[security] audit repository tooling

### ISSUE THREAD

**Issue by arademm** [open-telemetry/opentelemetry-go-contrib#4453]
The security SIG is looking to ensure that security tooling is setup consistently across the organization. As a result, we're asking maintainers to ensure the following tools are enabled in each repository:

- [ ]  CodeQL enabled via [GitHub Actions](https://github.com/open-telemetry/opentelemetry-collector/blob/main/.github/workflows/codeql-analysis.yml)
- [ ]  Static code analysis tool (the collector uses govulncheck [https://pkg.go.dev/golang.org/x/vuln] on every build)
- [ ]  Repository security settings
  - [x]  Security Policy ✅
  - [x]  Security advisories ✅
  - [x]  Private vulnerability reporting ✅
  - [ ]  Dependabot alerts ✅
  - [ ]  Code scanning alerts ✅

Parent issue: https://github.com/open-telemetry/sig-security/issues/12

**Comment by codeboten** [comment]
This was already done here: https://github.com/open-telemetry/opentelemetry-go-contrib/issues/4413, the issue can be closed

**Comment by arademm** [comment]
Noted
