### ISSUE TITLE
otelgin.Middleware("service name")  doesn't work

### ISSUE THREAD

**Issue by andotorg** [open-telemetry/opentelemetry-go-contrib#4476]
### Description

otelgin.Middleware("service name")  doesn't work

<img width="620" alt="image" src="https://github.com/open-telemetry/opentelemetry-go-contrib/assets/25116294/86005a0e-f8e9-4690-9cd6-70a943ec9425">
It is not the service name specified by me, but obtained by myself. The name is not standardized and not optimized.

### Environment

- OS: Mac Linux
- Architecture: [e.g. x86, i386]
- Go Version: [e.g. 1.20]
- `go.opentelemetry.io/contrib` version: [e.g. v0.19.0, 3c7face]
- `go.opentelemetry.io/contrib/instrumentation/github.com/gin-gonic/gin/otelgin` version: [e.g. v0.45.0, 3c7face]

### Steps To Reproduce

1. Using this code  `otelgin.Middleware("service name")`
2. Run server
3. See error  
<img width="620" alt="image" src="https://github.com/open-telemetry/opentelemetry-go-contrib/assets/25116294/86005a0e-f8e9-4690-9cd6-70a943ec9425">

### Expected behavior

jaeger display service name : `service name`

**Comment by pellared** [comment]
`service.name` should be set in a resource and not by an instrumentation library,.

See:
- https://opentelemetry.io/docs/instrumentation/go/getting-started/
- https://opentelemetry.io/docs/instrumentation/go/resources/
- https://opentelemetry.io/docs/instrumentation/go/manual/
- https://opentelemetry.io/docs/specs/semconv/resource/#service

**Comment by andotorg** [comment]
The incoming service that is adapted by the gin has no effect, so what is the meaning of the incoming service?
`engine.Use(otelgin.Middleware(what‘s the service？？？？？？ "))`

**Comment by pellared** [comment]
It sets the `net.host.name` attribute (tag).

**Comment by andotorg** [comment]
`net.host.name` this not work, not  display

**Comment by pellared** [comment]
> `net.host.name` this not work, not display

Can you give me a screenshot of tags of the span created by otelgin?

**Comment by andotorg** [comment]
![image](https://github.com/open-telemetry/opentelemetry-go-contrib/assets/25116294/eb1beb54-264d-4b35-9dee-b6c720786ee3)
see , thanks

**Comment by pellared** [comment]
The bug description is not accurate. There are no version. There are no repro steps.
Maybe you are not testing against the latest version?
You have not expanded the tags so I am not sure if I see all of them.

Our tests says that this attribute is exported: https://github.com/open-telemetry/opentelemetry-go-contrib/blob/5adc27110c6f8edff55e07c668aeb140a166dcfd/instrumentation/github.com/gin-gonic/gin/otelgin/test/gintrace_test.go#L75-L137

**Comment by andotorg** [comment]
router.Use(otelgin.Middleware("foobar", otelgin.WithTracerProvider(provider)))   
`foobar` will not be displayed in the jaeger service list, then you think it does not comply with the specification, but at the display level the service list is `service.name`, a service cannot be displayed to users as a service using `net.host.name` Check? Do you think this is reasonable?

**Comment by pellared** [comment]
I do not follow your latest message.

Please see here how to set the `service.name` resource attribute:

- https://opentelemetry.io/docs/instrumentation/go/getting-started/
- https://opentelemetry.io/docs/instrumentation/go/resources/
- https://opentelemetry.io/docs/instrumentation/go/manual/

The value of `service` parameter of https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/github.com/gin-gonic/gin/otelgin#Middleware only sets (currently) the `net.host.name` attribute in the telemetry emitted by the `otelgin` instrumentation library.

An instrumentation library cannot set the service name as the service can host multiple HTTP servers (even few gin servers). You can see `service.name` as an application name. 

otelgin tries to follow https://github.com/open-telemetry/opentelemetry-specification/blob/v1.17.0/specification/trace/semantic_conventions/http.md.

I am closing the bug as I find it invalid.

I kindly encourage to read the specification and create a new bug if you would find that otelgin does not conform to it.

**Comment by andotorg** [comment]
ok, Thanks for you !
