### ISSUE TITLE
otelgrpc: Add peer attributes to spans generated by stats handlers

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-contrib#4531]
The trace instrumentation implemented in https://github.com/open-telemetry/opentelemetry-go-contrib/pull/3002 misses peer attributes.

https://github.com/open-telemetry/opentelemetry-go-contrib/blob/23181f73f0f8743d9fdafc021cef8846f0cafd90/instrumentation/google.golang.org/grpc/otelgrpc/stats_handler.go#L78-L84

The `span` returned in `TagConn` is always `noop` as `TagConn` is invoked before `TagRPC`, therefore the peer attributes are never added to the spans.

Currently seems to be blocked by https://github.com/grpc/grpc-go/issues/6897.

**Comment by pellared** [comment]
@fatsheep9146 Can you take a look at this issue?

**Comment by fatsheep9146** [comment]
> @fatsheep9146 Can you take a look at this issue?

No problem, please assign to me :)

**Comment by pellared** [comment]
Currently seems to be blocked https://github.com/grpc/grpc-go/issues/6897
