### ISSUE TITLE
otelhttp: datadog resource name support

### ISSUE THREAD

**Issue by faizkamaludin** [open-telemetry/opentelemetry-go-contrib#4544]
On HTTP Middleware implementation the span not have resource.name attribute, and in datadog span information normally have 2 information, operation name and resource name, in otel the span is transformed to operation name, and resource name is not set in otelhttp.
This is my example code i use to set otelhttp in middleware
```
func OtelHttp(next http.Handler) http.Handler {
	return otelhttp.NewMiddleware("http.request",
		otelhttp.WithTracerProvider(otel.GetTracerProvider()),
		otelhttp.WithPropagators(
			propagation.NewCompositeTextMapPropagator(propagation.TraceContext{}, propagation.Baggage{}),
		),
	)(next)
}
```
In datadog the result is like this.
![Screenshot 2023-11-10 at 15 25 19](https://github.com/open-telemetry/opentelemetry-go-contrib/assets/111672827/fd4cdc3b-7977-4fdc-87b6-fc2c2f040677)

The expected i need is like this.
![Screenshot 2023-11-10 at 15 25 47](https://github.com/open-telemetry/opentelemetry-go-contrib/assets/111672827/77c69a50-1eca-4d02-af5a-cd90ae575583)

Maybe in otelhttp implementation we can add option config to set resource.name attribute to support datadog, thanks.

**Comment by ahmadfaizk** [comment]
Closed and changed with https://github.com/open-telemetry/opentelemetry-go-contrib/issues/4545
