### ISSUE TITLE
otelhttp: datadog resource name support

### ISSUE THREAD

**Issue by ahmadfaizk** [open-telemetry/opentelemetry-go-contrib#4545]
### Problem Statement

On HTTP Middleware implementation the span not have resource.name attribute, and in datadog span information normally have 2 information, operation name and resource name, in otel the span is transformed to operation name, and resource name is not set in otelhttp.

This is my example code to set otelhttp in middleware
```
func OtelHttp(next http.Handler) http.Handler {
	return otelhttp.NewMiddleware("http.request",
		otelhttp.WithTracerProvider(otel.GetTracerProvider()),
		otelhttp.WithPropagators(
			propagation.NewCompositeTextMapPropagator(propagation.TraceContext{}, propagation.Baggage{}),
		),
	)(next)
}
```
In datadog the span is look like this,
![Screenshot 2023-11-10 at 15 25 19](https://github.com/open-telemetry/opentelemetry-go-contrib/assets/45820010/4db2cde4-4ccb-4cc6-8ad5-1dcff9810dcd)
The expected span i need is like this
![Screenshot 2023-11-10 at 15 25 47](https://github.com/open-telemetry/opentelemetry-go-contrib/assets/45820010/bea66504-d08f-444c-a843-a9fccef40520)

### Proposed Solution

Maybe we can add otelhttp option config to set resource.name attribute, so the implementation is like this.
```
func OtelHttp(next http.Handler) http.Handler {
	return otelhttp.NewMiddleware("http.request",
		otelhttp.WithTracerProvider(otel.GetTracerProvider()),
		otelhttp.WithPropagators(
			propagation.NewCompositeTextMapPropagator(propagation.TraceContext{}, propagation.Baggage{}),
		),
		otelhttp.WithResourceNameFormatter(func(r *http.Request) string {
			return fmt.Sprintf("%s %s", r.Method, r.URL.Path)
		}),
	)(next)
}
```

#### Alternatives

N/A

#### Prior Art

In dd-trace-go library, the implementation to set resource name is like this [dd-trace-go/contrib/net/http](https://github.com/DataDog/dd-trace-go/blob/9d39644c0e722861d594f6c55970216ca1096de8/contrib/net/http/option.go#L115) may be we can follow implementation to set resource.name attribute in span. 

### Additional Context

N/A

**Comment by MrAlias** [comment]
Are you looking for [`WithSpanNameFormatter`](https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp#WithSpanNameFormatter)?

**Comment by ahmadfaizk** [comment]
WithSpanNameFormatter is only for set span name, and in datadog span name is transform to operation name, so in existing implementation with otelhttp resource name is not setted. Normally in datadog operation name like http.request, and resource name like GET /users or GET /users/:id.
This references in [datadog website](https://docs.datadoghq.com/tracing/guide/configuring-primary-operation/?code-lang=go#opentracing)

**Comment by MrAlias** [comment]
If I understand you correct, the ask is to provide a new resource for each measured span, right?

If that is the case, it is something we do not plan to support. In OTel resources are static objects that describe the source of telemetry. Providing a way to create a resource for each request would be an anti-pattern.

**Comment by ahmadfaizk** [comment]
Yes, correct. Hm, ok i'm understant with this, but can we set custom attributes from request, existing option to add attribute is from [WithSpanOptions](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/instrumentation/net/http/otelhttp/v0.45.0/instrumentation/net/http/otelhttp/config.go#L138), like this code.
```
func OtelHttp(next http.Handler) http.Handler {
	return otelhttp.NewMiddleware("http.request",
		otelhttp.WithTracerProvider(otel.GetTracerProvider()),
		otelhttp.WithSpanOptions(
			trace.WithAttributes(attribute.String("resource.name", "GET /users")),
		),
	)(next)
}
```
But this attribute is static value, maybe we can add option to set custom attribute from *http.request with function parameter, so imlementation is not stric with any provider.

**Comment by dmathieu** [comment]
``You can create a custom middleware that runs between the otelhttp one and your handler.

```
return otelhttp.NewMiddleware("http.request",
		otelhttp.WithTracerProvider(otel.GetTracerProvider()),
	)(myCustomHandler(next))
```

Then, in `myCustomHandler`, you can retrieve the current span from the context (which will be the span created by otelhttp) and modify it as you wish.

**Comment by ahmadfaizk** [comment]
Thanks @dmathieu , after i'm follow this method i can custom attributes in a middleware. this implementation in my code with go-chi.v5
```
func OtelHttp(next http.Handler) http.Handler {
	return otelhttp.NewMiddleware("http.request",
		otelhttp.WithTracerProvider(otel.GetTracerProvider()),
		otelhttp.WithPropagators(
			propagation.NewCompositeTextMapPropagator(propagation.TraceContext{}, propagation.Baggage{}),
		),
	)(otelDDCustomAttributes(next))
}

func otelDDCustomAttributes(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		next.ServeHTTP(w, r)

		span := trace.SpanFromContext(r.Context())

		resourceNameKey := attribute.Key("resource.name")
		span.SetAttributes(resourceNameKey.String(chi.RouteContext(r.Context()).RoutePattern()))
	})
}
```
One question again, i use otelhttp [Transport](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/instrumentation/net/http/otelhttp/v0.45.0/instrumentation/net/http/otelhttp/transport.go#L32) to trace http client request, but i can't custom span attributes with value from outgoing reqest, any idea to handle this ?

**Comment by dmathieu** [comment]
Exactly the same way! Otelhttp's takes a parent transport . You can add a custom one too.

**Comment by ahmadfaizk** [comment]
Oh i'm understant, In [NewTransport](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/9d4eb7e7706038b07d33f83f76afbe13f53d171d/instrumentation/net/http/otelhttp/transport.go#L50) method have base transport, i can custome span attribute with create custom transport, thanks for you for your explanation.

This issue is closed. Thanks.
