### ISSUE TITLE
gRPC metrics record duration in nanoseconds instead of milliseconds

### ISSUE THREAD

**Issue by Sovietaced** [open-telemetry/opentelemetry-go-contrib#4547]
### Description

RPC metrics are recording float64 of nanoseconds instead of milliseconds as they are intended to. 

### Expected behavior

If a float is going to be used to record RPC durations (similar to what is done for HTTP durations) we should be recording milliseconds and not nanoseconds.

**Comment by Sovietaced** [comment]
I will file a pull request for this momentarily.

**Comment by MrAlias** [comment]
Please link to appropriate semantic conventions stating these values should be recorded as nanoseconds prior to opening a PR.

As far as I can tell, they are defined to be measured milliseconds: https://github.com/open-telemetry/semantic-conventions/blob/main/docs/rpc/rpc-metrics.md#metric-rpcserverduration

**Comment by MrAlias** [comment]
> Please link to appropriate semantic conventions stating these values should be recorded as nanoseconds prior to opening a PR.
> 
> As far as I can tell, they are defined to be measured milliseconds: https://github.com/open-telemetry/semantic-conventions/blob/main/docs/rpc/rpc-metrics.md#metric-rpcserverduration

Oh, I miss-read :facepalm:. You are going the other direction

**Comment by ash2k** [comment]
Shouldn't all duration metrics be in seconds? I think I saw this requirement/recommendation somewhere in the spec. For histograms this would mean using custom buckets (which is now possible!) as the default ones would not be granular enough for "seconds" resolution.

**Comment by MrAlias** [comment]
> Shouldn't all duration metrics be in seconds? I think I saw this requirement/recommendation somewhere in the spec. For histograms this would mean using custom buckets (which is now possible!) as the default ones would not be granular enough for "seconds" resolution.

@ash2k please open an issue to track this independently.

For what it's worth, the change from `ms` to `s` happened in later versions of the semantic conventions that we do not currently support. We should track this so we can make sure we include it when we do update.

**Comment by ash2k** [comment]
@MrAlias Opened https://github.com/open-telemetry/opentelemetry-go-contrib/issues/4590. Thank you.
