### ISSUE TITLE
otelgrpc: stats handler doesn't seem to have an option for filtering

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-go-contrib#4575]
With the latest release, interceptors were deprecated from otelgrpc instrumentation. However, there doesn't seem to be an equivalent to `WithInterceptorFilter` which can filter spans (we use it to filter health checks `filters.Not(filters.HealthCheck())`. If there is a way that I missed, it likely needs to be added to the deprecation notice on `WithInterceptorFilter`.

https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/google.golang.org/grpc/otelgrpc/config.go#L149

**Comment by ymtdzzz** [comment]
I started this on #5196, but if anyone else has already worked on it, please let me know so I'll close it 😀

**Comment by mm2175** [comment]
encouter same issue

**Comment by kperreau** [comment]
Any update on this issue?

**Comment by bkane-msft** [comment]
Thanks to @ymtdzzz  in https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5196 , I was able to filter out traces with code similar to the following:

```go
server := grpc.NewServer(
	grpc.StatsHandler(
		otelgrpc.NewServerHandler(
			otelgrpc.WithFilter(filters.None(
				filters.ServiceName("grpc.health.v1.Health"),
				filters.ServiceName("grpc.reflection.v1.ServerReflection"),
				filters.ServiceName("grpc.reflection.v1alpha.ServerReflection"),
			),
			),
		),
	),
)
```

This took me a bit to figure out. The deprecation message on `otelgrpc.WithInterceptorFilter` just says `Deprecated: Use stats handlers instead`, which I didn't find particular clear.

**Comment by dmathieu** [comment]
Note that the grpc example uses the stats handler.
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/google.golang.org/grpc/otelgrpc/example/server/main.go#L128
