### ISSUE TITLE
Move `otelgin/internal/semconvutil` into `otelgin`

### ISSUE THREAD

**Issue by els0r** [open-telemetry/opentelemetry-go-contrib#4581]
### Problem Statement

Analogous to https://github.com/open-telemetry/opentelemetry-go-contrib/issues/4580, just for `gin-gonic`.

The `semconvutil` package follows semantic conventions for span attributes set during handling of a request by a server.

Exposing the utility functions from `semconvutil` would allow other gin middlewares to use them, leading to consistent, semconv-aligned telemetry.

In my specific use case, I'm providing a logging middleware and would like to use the same attribute keys as the `otelgin` Middleware does.

### Proposed Solution

Move `semconvutil` from `go.opentelemetry.io/contrib/instrumentation/github.com/gin-gonic/gin/otelgin/internal/semconvutil` to `go.opentelemetry.io/contrib/instrumentation/github.com/gin-gonic/gin/otelgin/semconvutil`

#### Alternatives

* Copy-pasting the internals of `semconvutil` to internal instrumentation library. Which isn't really maintainable
* Or keep the current implementation, which doesn't align with the semantic conventions
* Accessing the attributes of the parent span from the `otelgin` middleware (if that's even possible)

#### Prior Art

Not aware of any.

### Additional Context

We have some servers which handle a low frequency of requests and would like to correlate log messages in our system with the corresponding spans we export.

**Comment by MrAlias** [comment]
These are all copied packages from https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/internal/shared/semconvutil

There should be no difference between the semconvutil packge in otelhttp and otelgin. I would recommend closing this issue in favor of #4580 given we do not plan to export two of the same package.

**Comment by els0r** [comment]
Thanks for the broader context and the link to the `semconvutil` generators. No need to track two issues, then. Let's continue discussion in #4580 .
