### ISSUE TITLE
otelgrpc: Remove withoutContext

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-contrib#4703]
With https://github.com/open-telemetry/opentelemetry-go/pull/4671 the `withoutContext` implementation is no longer needed.

This issue awaits a new release of OTel Go SDK where the mentioned PR will be included.

This issue is nice to have in [v0.47.0](https://github.com/open-telemetry/opentelemetry-go-contrib/milestone/15)
 but it can be moved to next release.

**Comment by pellared** [comment]
CC @carrbs

**Comment by carrbs** [comment]
@pellared, should I be assigned to this?
