### ISSUE TITLE
Mux Instrumentation should not set span status to OK

### ISSUE THREAD

**Issue by wilguo** [open-telemetry/opentelemetry-go-contrib#474]
Based on the [specs](https://github.com/open-telemetry/opentelemetry-specification/blob/82865fae64e7b30ee59906d7c4d25a48fe446563/specification/trace/api.md#set-status) the `statuscode` should be unset by default. [Here](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/master/instrumentation/github.com/gorilla/mux/otelmux/mux.go#L149) the status code is always being set, even for success.

**Comment by matej-g** [comment]
Are you able to pin-point where this is happening exactly? Looking at [`SpanStatusFromHTTPStatusCode`](https://github.com/open-telemetry/opentelemetry-go/blob/master/semconv/http.go#L266), it seems it will return either `codes.Error` or `codes.Unset`. So even though there is explicit call to `SetStatus` below, it should still leave the span status to be `codes.Unset` in case of success.

**Comment by wilguo** [comment]
@ anuraaga

**Comment by wilguo** [comment]
Hi @matej-g, I think after more investigation, I found out the issue I was facing was caused by something else. Sorry!
