### ISSUE TITLE
Gorilla mux middleware wont compile

### ISSUE THREAD

**Issue by pintonunes** [open-telemetry/opentelemetry-go-contrib#48]
Hi, trying to use the gorilla mux trace middleware and I'm having this issue

```
$ go get go.opentelemetry.io/contrib
go: go.opentelemetry.io/contrib@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/d49ffc8cef0173d441fe62eb6e9b03ad04147087/plugins/gorilla/mux/go.mod#L10

Is this something on my side?

**Comment by Aneurysm9** [comment]
See #45.  You can add a `replace` directive, as outlined in [this comment](https://github.com/open-telemetry/opentelemetry-go-contrib/issues/45#issuecomment-634355917), as a temporary workaround until we ship a release from -contrib.

**Comment by pintonunes** [comment]
Thanks! Didnt saw that issue.
