### ISSUE TITLE
autoexport: Change WithFallback options signatures

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-contrib#4877]
### Problem Statement

The current definition of fallback options is as following:

```go
func WithFallbackMetricReader(exporter metric.Reader) MetricOption
```

The problem is that we need to create an instance of a metric reader or span exporter and it may not even be needed/used (it may even leak resources).

### Proposed Solution

Change the signature to accept a factory function e.g.

```go
func WithFallbackMetricReader(factory func(context.Context) (metric.Reader, error)) MetricOption
```

**Comment by hcelaloner** [comment]
Hi @pellared, I went ahead and prepared a PR for the requested change: https://github.com/open-telemetry/opentelemetry-go-contrib/pull/4891

I directly changed the signature of the method as requested. Doesn't this create a breaking change for existing autoexport users who use that method? How do you proceed in that kind of situation in opentelemetry-go-contrib? Should we create a new method and deprecate the old one instead?
