### ISSUE TITLE
add support for packages in golang standard library

### ISSUE THREAD

**Issue by andrewhsu** [open-telemetry/opentelemetry-go-contrib#50]
Similar to the open tracing support https://github.com/opentracing-contrib/go-stdlib

**Comment by Aneurysm9** [comment]
Do the `Handler` and `Transport` types in [the othttp package](https://github.com/open-telemetry/opentelemetry-go/tree/master/instrumentations/othttp) not cover this?

**Comment by MrAlias** [comment]
I think @Aneurysm9 is correct. Please reopen if there are other things this was meant to address @andrewhsu .
