### ISSUE TITLE
otelgrpc: error handling in StreamClientInterceptor

### ISSUE THREAD

**Issue by glazychev-art** [open-telemetry/opentelemetry-go-contrib#501]
Hello,
Seems, there is a problem in grpc interceptor
The goroutine is creating inside `wrapClientStream` and it is waiting for events (ex. from `RecvMsg`)

What if we get an error here?
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/master/instrumentation/google.golang.org/grpc/otelgrpc/interceptor.go#L279-L280
In this case there will be goleak.

May be better if we handle this error?
```
var stream *clientStream
s, err := streamer(ctx, desc, cc, method, callOpts...)
if err == nil {
	stream = wrapClientStream(s, desc)
}
```
Thank you

**Comment by MrAlias** [comment]
Related to https://github.com/open-telemetry/opentelemetry-go-contrib/issues/502
