### ISSUE TITLE
[otelgrpc] ambiguous import in the current version and past ones 

### ISSUE THREAD

**Issue by AnomalRoil** [open-telemetry/opentelemetry-go-contrib#5131]
### Description

Importing the current version of `go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc` breaks our go module imports because of ambiguous imports:
```
go: github.com/drand/drand/v2/internal/net imports
	go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc tested by
	go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.test imports
	google.golang.org/grpc/interop imports
	golang.org/x/oauth2/google imports
	cloud.google.com/go/compute/metadata: ambiguous import: found package cloud.google.com/go/compute/metadata in multiple modules:
	cloud.google.com/go v0.26.0 (/home/anomalroil/go/pkg/mod/cloud.google.com/go@v0.26.0/compute/metadata)
	cloud.google.com/go/compute/metadata v0.2.3 (/home/anomalroil/go/pkg/mod/cloud.google.com/go/compute/metadata@v0.2.3)
``` 

This seems to have been fixed in https://github.com/open-telemetry/opentelemetry-go-contrib/issues/4896 however it hasn't yet been included in a new version.

Sadly the changes which led to this issue mean that **we also cannot downgrade to a previous version** of `otelgrpc` because they now all suffer from that ambiguous import it seems.

### Environment

- OS: Linux 6.6.10-76060610-generic
- Architecture: x64
- Go Version: go version go1.21.7 linux/amd64
- `otelgrpc` version: v0.48.0

### Steps To Reproduce

1. Using this code:
```
package main

import (
	"fmt"

	grpc_recovery "github.com/grpc-ecosystem/go-grpc-middleware/recovery"
	"go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"
	"google.golang.org/grpc"
)

func main() {
	opts := append([]grpc.ServerOption{},
		grpc.StreamInterceptor(
			grpc_recovery.StreamServerInterceptor(),
		),
		grpc.StatsHandler(otelgrpc.NewServerHandler()),
	)

	fmt.Println(len(opts))
}
```
with version `go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.48.0`

2. Run `go mod tidy`
3. See error:
```
go: test imports
	go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc tested by
	go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.test imports
	google.golang.org/grpc/interop imports
	golang.org/x/oauth2/google imports
	cloud.google.com/go/compute/metadata: ambiguous import: found package cloud.google.com/go/compute/metadata in multiple modules:
	cloud.google.com/go v0.26.0 (/home/anomalroil/go/pkg/mod/cloud.google.com/go@v0.26.0/compute/metadata)
	cloud.google.com/go/compute/metadata v0.2.3 (/home/anomalroil/go/pkg/mod/cloud.google.com/go/compute/metadata@v0.2.3)
```

### Expected behavior

To not have ambiguous import paths and to have a new release ASAP when such issues arise.

So, any chance you could release a new version or should we pin the above commit in our `go.mod` file?

**Comment by MrAlias** [comment]
Thank you for opening the issue and including all the relevant information. [Release v0.49.0](https://github.com/open-telemetry/opentelemetry-go-contrib/releases/tag/v1.24.0) seems to have fixed this based on the provided code. I'm going to close this based on that validation, but if it is in error please reopen.
