### ISSUE TITLE
Add slog log bridge

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-contrib#5138]
Add `slog.Handler` log bridge

- The bridge factory should accept a logger provider and set the name of the bridge (e.g. `go.opentelemetry.io/contrib/bridges/sloghandler`) and its version as instrumentation scope
- The bridge should not make any heap allocation when the application emits a log using slog with up to 5 non-complex (no slices, no maps) attributes. There should be "zero allocation" unit tests for this.
- Calling `WithGroup` should result in nesting the attributes in a https://pkg.go.dev/go.opentelemetry.io/otel/log#Map so that it has similar behavior to `slog.JSONHandler`. See: https://go.dev/play/p/bjJp7A-56bf
- The bridge needs to have benchmarks

Additional resources:

- You can find a prototype implementation here: https://github.com/pellared/opentelemetry-go/blob/147762ffb5c4394417b3f973274cc570723db79b/log/internal/slog.go (from https://github.com/open-telemetry/opentelemetry-go/pull/4725)
- A guide on writing custom `slog.Handler`: https://github.com/golang/example/blob/master/slog-handler-guide/README.md
- More resources on slog: https://go.dev/wiki/Resources-for-slog

**Comment by jpkrohling** [comment]
I've added this to the scope of a few internships, such as LFX and Outreachy. Please, talk to me before working on this one.

**Comment by pellared** [comment]
@jpkrohling I updated the description to make the issue more open for new contributors.

**Comment by jpkrohling** [comment]
I think the LFX announcement happens today, and we'll start working on that right away.

**Comment by pellared** [comment]
We are already starting working on it 🚀

**Comment by pellared** [comment]
@jba, we have an initial version of `otelslog.Handler` here: https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/bridges/otelslog. Are you willing to review it? 

You can simply create a new GitHub issue with your feedback or even add some comments here.

You can also review and add comments here: https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5314 as this is the PR  that introduced most of the implementation.

**Comment by jba** [comment]
Thanks for including me. I made a couple of performance-related comments on the PR, not really important.
I didn't dig too deeply but everything looks good to me.

**Comment by Nikola-Milovic** [comment]
I am combing through the current version of the `slog` bridge code and I couldn't figure out the intended way to set the log level

In `slog.Handler` we can use the `slog.HandlerOptions`

```
slog.HandlerOptions{
	Level: level,
}
```

While in `otelslog.NewHandler` we can set the source, version, provider and the schema url.

Did I overlook some API?

**Comment by scorpionknifes** [comment]
> I am combing through the current version of the `slog` bridge code and I couldn't figure out the intended way to set the log level
> 
> 
> 
> In `slog.Handler` we can use the `slog.HandlerOptions`
> 
> 
> 
> ```
> 
> slog.HandlerOptions{
> 
> 	Level: level,
> 
> }
> 
> ```
> 
> 
> 
> While in `otelslog.NewHandler` we can set the source, version, provider and the schema url.
> 
> 
> 
> Did I overlook some API?

The current log level is set here and cannot be set manually https://github.com/open-telemetry/opentelemetry-go-contrib/blob/00786cc3fe5b58f2c0e14235eab8fb4d8ef1ae43/bridges/otelslog/handler.go#L190

It's designed to map the following https://github.com/open-telemetry/opentelemetry-go-contrib/blob/00786cc3fe5b58f2c0e14235eab8fb4d8ef1ae43/bridges/otelslog/handler.go#L19-L25

What's your use case that the above mapping doesn't work for you?

**Comment by Nikola-Milovic** [comment]
@scorpionknifes The mapping is fine, my question was how to control the minimum log level. I usually disable the `LevelDebug` in production. Eg setting the handler option for the level, which doesn't seem to be available with the bridge

```
slog.HandlerOptions{
	Level: slog.LevelInfo,
}
```

**Comment by scorpionknifes** [comment]
> @scorpionknifes The mapping is fine, my question was how to control the minimum log level. I usually disable the `LevelDebug` in production. Eg setting the handler option for the level, which doesn't seem to be available with the bridge
> 
> 
> 
> ```
> 
> slog.HandlerOptions{
> 
> 	Level: slog.LevelInfo,
> 
> }
> 
> ```

There is a similar conversation about a different bridge, this should help: https://github.com/open-telemetry/opentelemetry-go-contrib/issues/6283#issuecomment-2448482101

**Comment by pellared** [comment]
@Nikola-Milovic, PTAL at https://pkg.go.dev/go.opentelemetry.io/contrib/processors/minsev
