### ISSUE TITLE
Add zap log bridge

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-contrib#5191]
Add [`zapcore.Core`](https://pkg.go.dev/go.uber.org/zap/zapcore#Core) log bridge.

**Comment by pellared** [comment]
@khushijain21 is working on it.

**Comment by khushijain21** [comment]
Outline of the approach

- [ ] Skeleteon of zapcore and config for the bridge
- [ ] Implement zapcore methods
- [ ] Implement zapcore encoder
- [ ] Add Benchmarks

**Comment by pellared** [comment]
1. We do not need to implement zapcore.Encoder as we are providing a zapcore.Core
2. You can first implement `Write` and then `With` method as separate PRs
3. You can handle https://pkg.go.dev/go.uber.org/zap/zapcore#NamespaceType as a separate PR
4. You can handle trace correlation (handling `context.Context`) as a separate PR
5. After benchmarks are in place we can add performance improvements. I suggests adding usage of `sync.Pool` and other improvements after benchmarks are in place and we have required functionality in place.
6. Go doc comment should be updated after the implementation is done.
7. A testable example should be added demonstrating how to setup `otelzap`.
8. After the release the Go module should be added to https://opentelemetry.io/ecosystem/registry
9. After the release we could document the bridge also in https://opentelemetry.io/docs/languages/go/

Do you want to be a CODEOWNER? Can you maintain `otelzap` after your internship is finished?
