### ISSUE TITLE
Add logr log bridge

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-contrib#5192]
Add [logr.LogSink](https://pkg.go.dev/github.com/go-logr/logr#LogSink) log bridge.

Prototype implementation: https://github.com/pellared/opentelemetry-go/blob/147762ffb5c4394417b3f973274cc570723db79b/log/internal/logr.go

TODO:
- [x] Implementation: (draft: https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5357)
- [x] Benchmarks
- [ ] Add to published modules
- [ ] Add to OpenTelemetry Registry. Example PR: https://github.com/open-telemetry/opentelemetry.io/pull/4857
- [ ] [Handle key-naming conventions](https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5357#discussion_r1680750975) (separate issue?)

**Comment by scorpionknifes** [comment]
Keen to pick this one up

**Comment by pellared** [comment]
@scorpionknifes You are assigned. I suggest also looking at https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/bridges/otelslog as reference.

**Comment by pellared** [comment]
@scorpionknifes, I think that as the point we can publish the `otellogr` module. I find it safer to track https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5357#discussion_r1680750975 as a separate issue.
