### ISSUE TITLE
Filter support for new stats handlers

### ISSUE THREAD

**Issue by Sovietaced** [open-telemetry/opentelemetry-go-contrib#5248]
### Problem Statement

WithInterceptorFilter was [deprecated](https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc#WithInterceptorFilter) but there is no equivalent functionality for the new stats handlers. Personally I'd like to be able to ignore tracing/metrics for the health check API. 

### Proposed Solution

Implement filtering in stats handlers

Would be happy to contribute this, let me know!

**Comment by dmathieu** [comment]
Duplicate of https://github.com/open-telemetry/opentelemetry-go-contrib/issues/4575

**Comment by Sovietaced** [comment]
Sorry! Should have searched first
