### ISSUE TITLE
Processor that discards metrics older than 1 hour

### ISSUE THREAD

**Issue by rahuldimri** [open-telemetry/opentelemetry-go-contrib#5249]
### Problem Statement
Previously we have had issues where the OTEL agent (on user's K8s cluster) is not able to reach our central OTEL pipeline so it temporarily stores metric data in its queue. Eventually the connection is restored and the agent is able to forward data to our pipeline, which will process it and forward it to final destination. However, by this point, all that data is > 1 hour old. This is an issue because the final destination for our metrics is Amazon-managed Prometheus (AMP), which automatically discards data > 1 hour old, which means all the processing and forwarding we just did was a waste.
So, for efficiency, we should have a processor in our central pipeline that can automatically detect if incoming data (from agent) is > 1 hour old and throw it away instead of processing+forwarding it to AMP.

**Comment by dmathieu** [comment]
It looks like you want a collector processor. This repository is for modules of the Go SDK.
See https://github.com/open-telemetry/opentelemetry-collector-contrib

Also note that receivers, processors and exporters have public interfaces. So you can write them as you need them, you don't need someone else to do that for you.

**Comment by rahuldimri** [comment]
thanks for the feedback. Just wanted to have expert advice on this. Will work on this.
