### ISSUE TITLE
OpenTelemetry and Gin Context Key Conflict

### ISSUE THREAD

**Issue by dlinkov-roblox** [open-telemetry/opentelemetry-go-contrib#5277]
### Description

The[ key used for the span id](https://github.com/open-telemetry/opentelemetry-go/blob/main/trace/context.go#L41), directly conflicts with the "pass-through" key used by [Gin](https://github.com/gin-gonic/gin/blob/ab8042e9e5370bbe0e93ea5adc6e74ae4c5df95e/context.go#L1228). As such, passing a gin.Context to any other outgoing call (gRPC or HTTP) will result in a new trace being created as any call of `trace.SpanFromContext(c)` will return a NoopSpan.

### Environment

- OS: [e.g. iOS] Mac OS Sonoma 14.2
- Architecture: [e.g. x86, i386] ARM64
- Go Version: [e.g. 1.15] 1.19
- `otelgin` version: [e.g. v0.14.0, 3c7face]  v0.49.0

### Steps To Reproduce

1. Using this code: `main.go`
```
func main() {

  httpL, err := net.Listen("tcp", ":"+config.Config.HttpPort)
  if err != nil {
    return fmt.Errorf("cannot start listener for http %w", err)
  }
  
  r := gin.New()
  gz := (ginzap.Ginzap(logger.Logger, time.RFC3339, true))
  r.Use(ginzap.RecoveryWithZap(logger.Logger, true))
  r.GET(HealthCheckPath, otelgin.Middleware("example-service"), HealthCheckHandler)

  if err := r.RunListener(httpL); err != nil {
    logger.Logger.Fatal("failed to start http server", zap.Error(err))
  }
}
```

`healthcheck_handler.go`
```
func HealthCheckHandler(c *gin.Context) {
	client := http.Client{Transport: otelhttp.NewTransport(http.DefaultTransport)}
        span := trace.SpanFromContext(c)
	fmt.Println(span.SpanContext().SpanID())
	req, err := http.NewRequestWithContext(c, "GET", "Any endpoint", nil)
	if err != nil {
		log.Fatal(err)
	}

	resp, err := client.Do(req)
	if err != nil {
		log.Fatal(err)
	}
	_ = resp.Body.Close()

	c.JSON(http.StatusOK, gin.H{})
}
```
3. Run the above code
4. See that the Span ID in the healthcheck handler is all zeros (note that span := trace.SpanFromContext(c.Request.Context()) leads to a valid spanID).

### Expected behavior

There should be no issue propagating the gin.Context considering it implements the context.Context interface. This would require changing the key that is used for the span, so it may not be feasible. If that is not feasible, this edge case should be called out very explicitly in the documentation in otelgin.

**Comment by dlinkov-roblox** [comment]
Just created one here - https://github.com/gin-gonic/gin/issues/3888

**Comment by appleboy** [comment]
@dlinkov-roblox Thanks for your PR. I will take it.

**Comment by dmathieu** [comment]
Closing as fixed in gin.
