### ISSUE TITLE
Log Bridge: Explicit Context Injection for Zapcore

### ISSUE THREAD

**Issue by khushijain21** [open-telemetry/opentelemetry-go-contrib#5328]
Completes #5191

For more details on context injection - [Bridge API](https://github.com/open-telemetry/opentelemetry-specification/blob/976432b74c565e8a84af3570e9b82cb95e1d844c/specification/logs/bridge-api.md#explicit-context-injection)

Prototype: https://docs.google.com/document/d/15vR7D1x2tKd7u3zaTF0yH1WaHkUr2T4hhr7OyiZgmBg/edit#heading=h.4xuru5ljcups

**Comment by AkhigbeEromo** [comment]
Hello @khushijain21 
Can i work on this?
