### ISSUE TITLE
Make `otelhttp` produce old, new and duplicate Server Trace Attributes

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/opentelemetry-go-contrib#5331]
Make `instrumentation/net/http/otelhttp` produce Server Traces following the migration plan #5132.

A user should be able to produce Traces from the `handler` in current semconv (default), the latest semconv (1.24.0), and a duplicate form based on the Environment variable `OTEL_HTTP_CLIENT_COMPATIBILITY_MODE`

- [x] [Produce Old Server Attributes](https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5333)
- [x] ~[Produce Duplicate Server Attributes](https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5400)~ Will not do to simplify rollout
- [x] [Produce New Server Attributes](https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5401)
- [x] Create a changelog for Server Attributes availability.

**Comment by MrAlias** [comment]
For changelog entry: New environment variable that will produce both old and new needs to be added to the changelog.

**Comment by MrAlias** [comment]
Done
