### ISSUE TITLE
Make otelhttp produce old, new and duplicate Metrics

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-contrib#5360]
- [ ] Produce Old Server Metrics: https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5818
- [ ] Produce New Server Metrics
- [ ] Produce Old Client Metrics - todo @VinozzZ 
- [ ] Produce New Client Metrics
- [ ] Add a changelog entry

**Comment by MadVikingGod** [comment]
Split into  #5972 and #5973
