### ISSUE TITLE
Allow to carry-over a traceparent from another library

### ISSUE THREAD

**Issue by JonasDoe** [open-telemetry/opentelemetry-go-contrib#5380]
### Problem Statement

Currently, my server is running with fiber, with https://docs.gofiber.io/contrib/otelfiber as middleware. At the same time, this server does a `GET` request itself, with an ordinary `http.Client`  and the `RoundTriper` from `otelhttp.NewTransport`. Since the latter relies on a different `Context` key `currentSpanKey`, it will ignore the `traceparent` set by the fiber middleware, and I don't see any possible to fix in my application. As a result, I can't trace the chain of requests based on `trace-id`.

### Proposed Solution

Maybe the `SpanStartOption` resp. the underlying [`SpanConfig`](https://github.com/open-telemetry/opentelemetry-go/blob/014c6fc3323554065532b2b260945a9d0cd62b74/trace/config.go#L57) could allow `traceparent` to be regarded?

#### Alternatives

I figure there are reasons why the `Context` key is private and the current span is read-only. But if it was public, I could set the desired `traceparent` in the `Context` myself.

**Comment by dmathieu** [comment]
If your application requires a span on a new context, you can use [trace.ContextWithSpan](https://pkg.go.dev/go.opentelemetry.io/otel/trace#ContextWithSpan) to inject the span of your choice into it.

```
ctx := trace.ContextWithSpan(context.Background(), span)
```

**Comment by JonasDoe** [comment]
> If your application requires a span on a new context, you can use [trace.ContextWithSpan](https://pkg.go.dev/go.opentelemetry.io/otel/trace#ContextWithSpan) to inject the span of your choice into it.
> 
> ```
> ctx := trace.ContextWithSpan(context.Background(), span)
> ```

Omg, how could I miss this? Thanks for the fast response!
