### ISSUE TITLE
Add zerolog log bridge

### ISSUE THREAD

**Issue by scorpionknifes** [open-telemetry/opentelemetry-go-contrib#5405]
Add [zerolog.Hook](https://pkg.go.dev/github.com/rs/zerolog#Hook) log bridge.

Another pretty popular log library, keen to work on this if we keen on this suggestion

**Comment by AkhigbeEromo** [comment]
Hello @scorpionknifes , Can i work on this?

**Comment by scorpionknifes** [comment]
👍 Feel free, I don't have permission to assign you tho.

Checkout for other bridge implementation
https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/bridges/otellogrus
https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/bridges/otelslog
https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/bridges/otelzap

**Comment by domino14** [comment]
How's the progress on this @AkhigbeEromo ? Did you decide to take this on?

**Comment by AkhigbeEromo** [comment]
Yes I did @domino14 
Currently still working on it
Waiting for more reviews so I can make changes

**Comment by pellared** [comment]
The zerolog bridge has been not published. 
Root cause: https://github.com/rs/zerolog/issues/493
More: https://github.com/open-telemetry/opentelemetry-go-contrib/issues/5969
