### ISSUE TITLE
Add a resource detector that sets a default value for `service.instance.id` according to semantic conventions

### ISSUE THREAD

**Issue by pyohannes** [open-telemetry/opentelemetry-go-contrib#5423]
### Problem Statement

Currently, there is no resource detector provided that populates `service.instance.id` as specified in semantic conventions.

### Proposed Solution

A resource detector for service attributes should be provided which sets values according to [experimental semantic conventions for services](https://github.com/open-telemetry/semantic-conventions/tree/main/docs/resource#service-experimental).

#### Alternatives

Setting `service.instance.id` manually and ensuring that it is unique for each service instance.

**Comment by dashpole** [comment]
If this eventually is moved to stable, it will become part of the default resource detector.  Could we instead make this a feature of the default detector, similar to the [defaultServiceNameDetector](https://github.com/open-telemetry/opentelemetry-go/blob/fe8e3a1b42997767073598aaf6c5923b664b1254/sdk/resource/resource.go#L223)?

We could use environment variables to gate the feature, similar to other experimental parts of the SDK.

@MrAlias do you think we could move https://github.com/open-telemetry/opentelemetry-go/tree/main/sdk/metric/internal/x to sdk/internal/x so it can be used for non-metric SDK features?

**Comment by MrAlias** [comment]
> @MrAlias do you think we could move https://github.com/open-telemetry/opentelemetry-go/tree/main/sdk/metric/internal/x to sdk/internal/x so it can be used for non-metric SDK features?

Yeah, we could add a similar package there. We wouldn't want to move it there as that would cross module boundaries. But we can implement the same thing there for other experimental features of that module.

**Comment by ayushrakesh** [comment]
@pyohannes  Can you help me how to start work on this issue?
