### ISSUE TITLE
otelhttp response writer implementation does not track `WriteHeader` when `Flush` is called

### ISSUE THREAD

**Issue by cpuguy83** [open-telemetry/opentelemetry-go-contrib#5438]
### Description

When using the otelhttp wrapper to instrument an http endpoint, the wrapper is doing its own tracking to determine if `WriteHeader` should be called during a `Write`.

However the wrapper does not implement `http.Flusher`, as such  when `Flush()` is called on the http.ResponseWriter the undrlying flusher from net/http is called, however otelhttp is not aware that the headers have already been written.
When a subsequent call to `Write` is made, otelhttp calls `WriteHeader` first, which has already been called on the underlying net/http implementation, and we wend up with a log printed from net/http:

> http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*respWriterWrapper).WriteHeader (wrap.go:98)

### Environment

- OS: N/A
- Architecture: N/A
- Go Version: N/A
- `otelhttp` version: v0.46.1

### Steps To Reproduce

Basic example:

```go
func someHandler(w http.ResponseWriter, _ *http.Request) {
  w.(http.Flusher).Flush()
  w.Write([]byte("hello world"))
}
```

### Expected behavior

Since otelhttp is doing its own tracking in its `Write` implementation for when to call `WriteHeader`, it needs to be aware of when `Flush` is called.

**Comment by dmathieu** [comment]
Could you give us the implementation of your flusher?
In our test suite, if I flush the response writer, then write to it, everything works properly.
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/a91e60beace7c1d96302fe359050d705c4723e72/instrumentation/net/http/otelhttp/handler_test.go#L27-L35

Which makes sense, because the wrapped response writer is a RecorderTest, for which Flush is implemented there:
https://pkg.go.dev/net/http/httptest#ResponseRecorder.Flush

This method will only write the header if it hasn't been written yet (and `WriteHeader` does the same check).
So when `Flush()` is called, the header is written. But any further call of `WriteHeader` is a noop from the main writer.

Should your flusher implementation be doing the same check?

**Comment by cpuguy83** [comment]
@dmathieu This is the stdlib implementation from a standard net/http.Server

**Comment by cpuguy83** [comment]
For reference, here is how we fixed this in moby: https://github.com/moby/moby/pull/47796
I do prefer the changes we made to work around this, but still seems like there's a minor issue in the otelhttp implementation.

**Comment by dmathieu** [comment]
All right, it wasn't happening in tests because the log only happens in the runtime response implementation, not in httptest.
https://cs.opensource.google/go/go/+/refs/tags/go1.22.3:src/net/http/server.go;l=1157

I have opened a fix in #5634.

**Comment by cpuguy83** [comment]
Thanks for jumping on that!

**Comment by Salmonster** [comment]
@dmathieu Thanks for making the PR fix for this issue. I'm seeing right now that it has conflicts with the target branch. Do you have an idea of when this will be resolved and a new release issued? A service I work on that has an indirect dependency on `go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp` is getting this log quite a lot, and I was able to correlate it with http response status 500 errors logged by the same service.

**Comment by dmathieu** [comment]
Thank you. I have rebased the branch.
Note that this log is a warning though. Removing it will not change any behavior.

**Comment by lambrospetrou** [comment]
It seems that somehow this fix got reverted in some renames...
The current version does not check the `w.wroteHeader`: https://github.com/open-telemetry/opentelemetry-go-contrib/blob/bb3cf243ee89f724bcab1da580323cbe775505da/instrumentation/net/http/otelhttp/internal/request/resp_writer_wrapper.go#L82

The fix that disappeared: https://github.com/open-telemetry/opentelemetry-go-contrib/commit/94799103a321c114e7202f63bf95dcb940e0133a
