### ISSUE TITLE
Deprecate and remove go.opentelemetry.io/otel/detectors/aws/ecs

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-contrib#5543]
This module has been identified to not have an [owner](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/5d8c6d20b1852e47e15b989abe813c20cb935e9b/CODEOWNERS). Based on the [project's ownership policy](https://github.com/open-telemetry/opentelemetry-go-contrib/issues/2834#issuecomment-1282698918), this module will be deprecated and then removed.

### How to keep this module

For this module to continue in this repository, it needs a sponsor.

If you would like to sponsor this module and become an owner, please comment in this issue about your desire. As an owner you will assume the following responsibilities:

- You will need to [be a member of the OpenTelemetry organization](https://github.com/open-telemetry/community/blob/main/community-membership.md#member) and maintain that membership.
  - If you are not an existing member, we can add you to the community. This is not a disqualification, but something you will need in the process of becoming a sponsor.
- You will be responsible for keeping up with the instrumented library. Any "upstream" changes that impact this module need to be proactively handle by you.
- You will be expected to review any Pull Requests or Issues created that relate to this module.
- You will be responsible for the stability and versioning compliance of the module.

You will need to have a good working knowledge of the code this module is instrumenting and, ideally, familiarity with the existing module code.

### How this module will be removed

This module is in the process of being deprecated. After that deprecation notice has been published, we will wait 3 months or 2 two releases (whichever is the longer time period). After that time period, this module will be removed from this repository and no more versions of the module will be published.

#### Resurrection

If a sponsor is found after the module has been deprecated or removed, these operations can be reversed (i.e. coded added back, deprecation notice removed).

**Comment by MrAlias** [comment]
cc @Aneurysm9

**Comment by MrAlias** [comment]
@pyohannes would like to become the owner of this.

**Comment by akats7** [comment]
Hi @dmathieu, I'm also willing to become code owner for this

**Comment by MrAlias** [comment]
@akats7 thanks for the interest! Can you review the [Code Ower](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/CONTRIBUTING.md#code-owners) policy and comment if you meet the requirements and are comfortable assuming the responsibilities?

**Comment by akats7** [comment]
@MrAlias yep I meet the requirements and am comfortable assuming the responsibilities, I'll also join the SIG meeting tmrw

**Comment by wangzlei** [comment]
@Aneurysm9  I'm willing to be code owner for this component

**Comment by jj22ee** [comment]
I can be a code owner for this module
@Aneurysm9 @MrAlias

**Comment by akats7** [comment]
Hey @MrAlias, any update/ should I open a PR?

**Comment by MrAlias** [comment]
> Hey @MrAlias, any update/ should I open a PR for the set of packages

Sorry about the delay. I should have a PR out today to address this. Thanks for the patience!

**Comment by MrAlias** [comment]
> > Hey @MrAlias, any update/ should I open a PR for the set of packages
> 
> Sorry about the delay. I should have a PR out today to address this. Thanks for the patience!

@akats7 https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5712

**Comment by akats7** [comment]
Awesome, thanks @MrAlias!

**Comment by MrAlias** [comment]
@jj22ee linking my response from [here](https://github.com/open-telemetry/opentelemetry-go-contrib/issues/5545#issuecomment-2145895167):

> @jj22ee I see you are not already a [CNCF project member ](https://github.com/open-telemetry). This is one of the [requirements](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/CONTRIBUTING.md#requirements) we have for becoming a Code Owner.
> 
> I'm going to hold off on adding you as a Code Owner for now. If you do become a CNCF member in the future and still wish to be a Code Owner of this module, please open an issue to apply then.

**Comment by MrAlias** [comment]
> @Aneurysm9 @MrAlias I'm willing to be code owner for this component

Awesome @wangzlei! It looks like you meet all the requirements to become a Code Owner of this module. I will open a PR to add you once https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5712 merges (to help prevent merge conflicts).
