### ISSUE TITLE
why otelhttptrace duplicate?

### ISSUE THREAD

**Issue by zdyj3170101136** [open-telemetry/opentelemetry-go-contrib#5562]
in example:
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/net/http/httptrace/otelhttptrace/example/client/client.go

```
client := http.Client{
		Transport: otelhttp.NewTransport(
			http.DefaultTransport,
			otelhttp.WithClientTrace(func(ctx context.Context) *httptrace.ClientTrace {
				return otelhttptrace.NewClientTrace(ctx)
			}),
		),
	}

	bag, _ := baggage.Parse("username=donuts")
	ctx := baggage.ContextWithBaggage(context.Background(), bag)

	var body []byte

	tr := otel.Tracer("example/client")
	err = func(ctx context.Context) error {
		ctx, span := tr.Start(ctx, "say hello", trace.WithAttributes(semconv.PeerService("ExampleService")))
		defer span.End()

		ctx = httptrace.WithClientTrace(ctx, otelhttptrace.NewClientTrace(ctx))
		req, _ := http.NewRequestWithContext(ctx, "GET", *url, nil)

		fmt.Printf("Sending request...\n")
		res, err := client.Do(req)
		if err != nil {
			panic(err)
		}
		body, err = io.ReadAll(res.Body)
		_ = res.Body.Close()

		return err
	}(ctx)
```
why func  otelhttptrace.NewClientTrace have called twice?

which is correct?

**Comment by dmathieu** [comment]
Both are not required, but they are there for the sake of the example (we could possibly document that only one is required).

The otelhttp transport will override the client trace from the context in case one is set:
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/8cb2ad68f7d36c2055be5895a00a36519c2a2b25/instrumentation/net/http/otelhttp/transport.go#L136-L138

So setting in the client allows making sure there's one set for every HTTP request that client makes. Setting it in the context is the official recommended way from the httptrace example: https://pkg.go.dev/net/http/httptrace

**Comment by dmathieu** [comment]
Ah yes, [WithClientTrace](https://pkg.go.dev/net/http/httptrace#WithClientTrace) appends new tracers, it does not replace.
There is no way to remove already appended client tracers though. So we can't "fix" this per-se.

This probably warrants a documentation change, but the only real fix here is to only use one of the two config methods, not both.

**Comment by Cirilla-zmh** [comment]
>  There is no way to remove already appended client tracers though. So we can't "fix" this per-se.
> 
> This probably warrants a documentation change, but the only real fix here is to only use one of the two config methods, not both.

Thanks for your reply.

Maybe we can get do `ContextClientTrace` while `WithClientTrace` and replace the fields of the old tracer rather than append a new one?

**Comment by Cirilla-zmh** [comment]
@dmathieu  Sorry, my bad. `WithClientTrace` is actually an SDK from Golang, and it looks like making a straight-up replacement is pretty tough.

Thanks again for getting back to me.

**Comment by dmathieu** [comment]
Closing, as this issue seems to be resolved.
