### ISSUE TITLE
Nested http spans from different modules

### ISSUE THREAD

**Issue by amirrmonfared** [open-telemetry/opentelemetry-go-contrib#5572]
### Description
Hi team! 

We have different API modules implementing interfaces that are wrapped inside a caller to do an iteration on those modules and calling the inner APIs. The spans are propagating as expected except one thing which is the spans from different API modules are getting nested as children into each other on each iteration and it will continue until the loops end and in the next loop iteration again the same thing will happen but these loops will never be a child and only each iteration will make the nested children.

### Environment
- Go Version: [1.21]
- `otelhttptrace` version: v0.45.0

### Steps To Reproduce
You can check the code on how we set the tracing and you can do a loop on HTTP calls from different modules that are using the same function on every httpClient initialization

This SetTracingTransport is called on every API module that uses one parent HTTP client and copy to make their client
```
func SetTracingTransport(client Client, spanName string, isTracingEnabled bool) Client {
	if !isTracingEnabled {
		return client
	}

	costumClient, ok := client.(*costumClient)
	if !ok || costumClient.client == nil || costumClient.tracingEnabled {
		return client
	}

	updatedCostumClient:= *costumClient
	updatedCostumClient.client.Transport = otelhttp.NewTransport(
		updatedCostumClient.client.Transport,
		otelhttp.WithSpanNameFormatter(func(_ string, r *http.Request) string {
			return spanName + "/HTTP " + r.Method
		}))
	updatedCostumClient.tracingEnabled = true

	return &updatedCostumClient
}
```

### Expected behavior
We expect each API call have it's own traces instead of being a child of another API

**Comment by dmathieu** [comment]
This is the expected behavior. Distributed tracing propagation allows marking spans from sub-services as childs of the parent one.
You can use the [WithPublicEndpoint](https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp#WithPublicEndpoint), and `WithPublicEndpointFn` options when you configure otelhttp to mark specific requests as not being childs of the propagated trace.
They will be a root span, with the parent becoming a link.

**Comment by dmathieu** [comment]
Closing, as my previous comment should answer the question. Feel free to comment again if that's not the case.
