### ISSUE TITLE
log bridges must not depend on SDK

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-contrib#5586]
These must not depend on `go.opentelemetry.io/otel/sdk`:

- https://github.com/open-telemetry/opentelemetry-go-contrib/blob/a8f5abc8b1ac3cdf0a747e87690f477763233a9f/bridges/otelslog/go.mod#L8
- https://github.com/open-telemetry/opentelemetry-go-contrib/blob/a8f5abc8b1ac3cdf0a747e87690f477763233a9f/bridges/otellogrus/go.mod#L9
- https://github.com/open-telemetry/opentelemetry-go-contrib/blob/a8f5abc8b1ac3cdf0a747e87690f477763233a9f/bridges/otelzap/go.mod#L8

**Comment by MrAlias** [comment]
How is the instrumentation library going to be provided if this dependency is not allowed?

**Comment by MrAlias** [comment]
The import comes from the `WithInstrumentationScope` options[^1]. How do we want to replace these?

Should we provide a `Scope` type for each bridge?

Should we provide options for each scope field (e.g. `WithInstrumentationName`, `WithInstrumentationVersion`, and `WithInstrumentationSchemaURL`)?

[^1]: https://github.com/open-telemetry/opentelemetry-go-contrib/blob/a8f5abc8b1ac3cdf0a747e87690f477763233a9f/bridges/otelslog/handler.go#L113-L125

**Comment by MrAlias** [comment]
> We should also consider redesigning the `go.opentelemetry.io/otel/api` and introduce the `InstrumentationScope` type there.

Assuming you mean `go.opentelemetry.io/otel/log`, this sounds reasonable.

This would diverge from other signals (trace and metrics), but since the logs API isn't an "API", but a "bridge API" this seems to make sense.

**Comment by pellared** [comment]
Based on the usages we have so far, I think we might even consider removing https://pkg.go.dev/go.opentelemetry.io/otel/log#LoggerConfig and related https://pkg.go.dev/go.opentelemetry.io/otel/log#LoggerOption and changing it into `InstrumentationScope`. The `LoggerProvider.Logger` would simply accept the `InstrumentationScope`. This would be complaint with the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/bridge-api.md#get-a-logger) which says:

> Get a Logger
>
> This API MUST accept the following [instrumentation scope](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-instrumentationscope) parameters:

**Comment by MrAlias** [comment]
> Based on the usages we have so far, I think we might even consider removing https://pkg.go.dev/go.opentelemetry.io/otel/log#LoggerConfig and https://pkg.go.dev/go.opentelemetry.io/otel/log#LoggerOption and adding `InstrumentationScope`. The `LoggerProvider.Logger` would simply accept the `InstrumentationScope`. This should be complaint with the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/bridge-api.md#get-a-logger) that says:
> 
> > Get a Logger
> > This API MUST accept the following [instrumentation scope](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-instrumentationscope) parameters:

That might limit our ability to extend the Logger configuration in the future beyond what we want to do.

**Comment by pellared** [comment]
> That might limit our ability to extend the Logger configuration in the future beyond what we want to do.

I agree. I think it would be safer to replace the existing [options](https://pkg.go.dev/go.opentelemetry.io/otel/log#LoggerOption) with one `WithInstrumentationScope`. Then we have still flexibility to add other not scope related options in future.

**Comment by MrAlias** [comment]
Looking at use-cases will help with the new design.

## Current design

```go
var logger = otelslog.NewLogger(
	otelslog.WithInstrumentationScope(instrumentation.Scope{
		Name:      name,
		Version:   version,
		SchemaURL: schemaURL,
	}),
)
```

- This requires that bridges import `go.opentelemetry.io/otel/sdk`
- Requires the boilerplate of `instrumentation.Scope{}` to wrap options

## Proposals

### Add `Scope` type to `otelslog`

```go
var logger = otelslog.NewLogger(
	otelslog.WithInstrumentationScope(otelslog.Scope{
		Name:      name,
		Version:   version,
		SchemaURL: schemaURL,
	}),
)
```

- Requires the boilerplate of `otelslog.Scope{}` to wrap options
- Competing `Scope` types across all bridge implementations (a simplistic IDE may import the wrong one)

### Add `WithInstrumentationName`, `WithInstrumentationVersion`, and `WithInstrumentationSchemaURL`

```go
var logger = otelslog.NewLogger(
	otelslog.WithInstrumentationName(name),
	otelslog.WithInstrumentationVersion(version),
	otelslog.WithInstrumentationSchemaURL(schemaURL),
)
```

- Extra `otelslog` API surface area (N options instead of 1 option and 1 struct type with N fields)
- Competing option types across all bridge implementations (a simplistic IDE may import the wrong one)

### Adding `Scope` to `go.opentelemetry.io/otel/log`

```
var logger = otelslog.NewLogger(
	otelslog.WithInstrumentationScope(log.Scope{
		Name:      name,
		Version:   version,
		SchemaURL: schemaURL,
	}),
)
```

- Requires the boilerplate of `log.Scope{}` to wrap options
- Duplicates the `Scope` type from `go.opentelemetry.io/otel/sdk/instrumentation` (a simplistic IDE may import the wrong one)
- Requires the additional import of `go.opentelemetry.io/otel/log`

**Comment by MrAlias** [comment]
Given we want to encourage the instrumentation name be provided we could also update that to be a required variable. Additionally, we can drop the `*Instrumentation*` part of the options. Meaning we would have:

```go
func NewLogger(name string, options ...Option) *slog.Logger { /* ... */ }

func NewHandler(name string, options ...Option) *Handler { /* ... */ }

func WithVersion(version string) Option { /* ... */ }

func WithSchemaURL(schemaURL string) Option { /* ... */ }
```

The creation pattern would then be:

```go
var logger = otelslog.NewLogger(
	name,
	otelslog.WithVersion(version),
	otelslog.WithSchemaURL(schemaURL),
)
```

and

```go
var handler = otelslog.NewHandler(
	name,
	otelslog.WithVersion(version),
	otelslog.WithSchemaURL(schemaURL),
)
```

**Comment by MrAlias** [comment]
The "splitting into multiple options" proposal matches our [logs bridge API design](https://pkg.go.dev/go.opentelemetry.io/otel/log#LoggerOption):

![20240515_112302](https://github.com/open-telemetry/opentelemetry-go-contrib/assets/5543599/40cd2d11-9696-48c9-a1e7-c1fde05e36fa)

**Comment by MrAlias** [comment]
"splitting into multiple options" prototype: https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5588

**Comment by pellared** [comment]
@MrAlias, here is another proposal that you can add to the list.

It may occur that getting a logger for some bridges is going to be on the hot-path. E.g. in zap `LoggerName` is a field of the [Entry](https://pkg.go.dev/go.uber.org/zap/zapcore#Entry). Each `OnEmit` may need to get a logger if we do not want to store a `map[string]log.Logger` in the bridge. We might prefer using structs instead of options pattern for getting a logger to decrease the amount of heap allocations. 

In `go.opentelemetry.io/otel/log` we could simply change the `LoggerConfig` to be a simple struct with exported fields and make `LoggerProvider.Logger` to accept `LoggerConfig` instead of options.

**Comment by MrAlias** [comment]
That would violate our design patterns we have already established.

If a user cares about the allocations of performance they can do similar things to the metric signal an cache option allocations outside of the hot-path. I would strongly prefer consistency in this situation.
