### ISSUE TITLE
Unable to get tracer back in otelecho

### ISSUE THREAD

**Issue by deefdragon** [open-telemetry/opentelemetry-go-contrib#561]
When creating a tracer via otelecho, it is impossible to get the tracer back from otelecho.Middleware without using a hard coded string to get the value from the context every call, or without using a different hard coded string to generate a new trace provider. Neither of these strings are exposed outside otelecho.

**Comment by MrAlias** [comment]
Thanks for the question. Based on how you describe the situation, this is the intent of how named tracers are intended to be (or really not be) used. The instrumentation library should be the only one using that `Tracer` to create spans. If additional spans are meant to be created, the code creating that span should use a `Tracer` named after that code itself.

Hopefully this helps.
