### ISSUE TITLE
Reflected cross-site scripting

### ISSUE THREAD

**Issue by Nanmozhi22** [open-telemetry/opentelemetry-go-contrib#5625]
Directly writing user input (for example, an HTTP request parameter) to an HTTP response without properly sanitizing the input first, allows for a cross-site scripting vulnerability.

This kind of vulnerability is also called reflected cross-site scripting, to distinguish it from other types of cross-site scripting.

Recommendation:

To guard against cross-site scripting, consider using contextual output encoding/escaping before writing user input to the response, or one of the other solutions .

**Comment by Nanmozhi22** [comment]
I will work on this

**Comment by dmathieu** [comment]
Hi,

Unless you can provide us with more information, I will be closing this issue in a week.

**Comment by Nanmozhi22** [comment]
Hi , 

we have got the vulnerability as part of the code scanning alerts . here are the few reference CWE's.


Common Weakness Enumeration: [CWE-79](https://cwe.mitre.org/data/definitions/79.html).
Common Weakness Enumeration: [CWE-116](https://cwe.mitre.org/data/definitions/116.html).

**Comment by dmathieu** [comment]
Which instrumentation does that happen on? Which input is being impacted?

**Comment by Nanmozhi22** [comment]
Hi , Here is the details I got. 

![Capture](https://github.com/open-telemetry/opentelemetry-go-contrib/assets/117385609/713c598c-37b1-4ca3-8197-92434bb5f810)

**Comment by dmathieu** [comment]
Your alert is coming from an example, not runtime code.
In a real application, it would be your responsibility to do sanitization if you're using `mux.Vars` in your code.

**Comment by Nanmozhi22** [comment]
Got it , Does this mean contribution of this code change will not be required ?

**Comment by dmathieu** [comment]
This is how the var is retrieved:
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/c93294856571d9cb67503dfad4cbaf695b579ee7/instrumentation/github.com/gorilla/mux/otelmux/example/server.go#L37-L39

As you can see, it retrieved `id`, which can only be `[0-9]+` per the route regexp. So technically, the content is already sanitized. If it contains anything else than a suite of numbers, it won't be accepted.

There is no cross-site scripting issue here.

**Comment by Nanmozhi22** [comment]
got it , Thanks for the information, I can close this issue.

**Comment by Nanmozhi22** [comment]
This issue can closed as there is no cross-site scripting issue
