### ISSUE TITLE
Add codespell to CI

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-contrib#5659]
Add `codespell` Make target and GitHub workflow like in https://github.com/open-telemetry/opentelemetry-go. References:
- https://github.com/open-telemetry/opentelemetry-go/blob/main/.github/workflows/codespell.yaml
- https://github.com/open-telemetry/opentelemetry-go/blob/main/Makefile

**Comment by SequoiaGod** [comment]
@pellared 
Hi mate,
I have already added the codespell GitHub action and its related makefile command on this PR: [Add codespell to CI #5683](https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5683). The codespell is working now, but there are sorts of potential typos in the project, so the codespell workflow doesn't pass. You can also check this PR on my repository: [PR](https://github.com/SequoiaGod/opentelemetry-go-contrib/actions/runs/9301727492/job/25600434373?pr=1)

**Comment by dmathieu** [comment]
> The codespell is working now, but there are sorts of potential typos in the project, so the codespell workflow doesn't pass. 

These should be either fixed, or added to the ignore config.

**Comment by SequoiaGod** [comment]
> > The codespell is working now, but there are sorts of potential typos in the project, so the codespell workflow doesn't pass.
> 
> These should be either fixed, or added to the ignore config.

Thanks for mentoring, I have already added the ignore config and also fixed all of the typos. I think it should be ok to be reviewed.

**Comment by SequoiaGod** [comment]
> > The codespell is working now, but there are sorts of potential typos in the project, so the codespell workflow doesn't pass.
> 
> These should be either fixed, or added to the ignore config.

Thanks for mentoring, I have already added the ignore cofig and also fixed the rest of the typos. I think it should ready for reviewing now.
