### ISSUE TITLE
WithInstrumentationScope change needs getstarted updates

### ISSUE THREAD

**Issue by xorima** [open-telemetry/opentelemetry-go-contrib#5706]
### Description

Type: Documentation
Under: https://opentelemetry.io/docs/languages/go/getting-started/#add-custom-instrumentation there is a part of the guide where the code uses: 

```golang
	logger = otelslog.NewLogger(
		otelslog.WithInstrumentationScope(instrumentation.Scope{
			Name: name,
		}),
	)
```

with changes in 1.27.0 https://github.com/open-telemetry/opentelemetry-go-contrib/releases/tag/v1.27.0 this func was replaced so the get started should also be updated 

### Steps To Reproduce

Follow the get started guide, code fails to work due to renamed function

### Expected behavior

Guide to show us how to get things working correctly.

**Comment by dmathieu** [comment]
Fixed in https://github.com/open-telemetry/opentelemetry.io/pull/4577
