### ISSUE TITLE
gin context with tracing not work

### ISSUE THREAD

**Issue by pepea23** [open-telemetry/opentelemetry-go-contrib#5765]
when implementing use otel tracing like this
image
![image](https://github.com/open-telemetry/opentelemetry-go/assets/32633442/8b8613f5-b6aa-417b-b4bb-c26e6c4d3103)

and apply to router like "router.POST("/v4/*xxxx", gatewayPostHandler, WithTracer())"

then tried to get a trace I found that gin context does not save trace_id and span_id it empty so how to reproduce the problem?

handler function
image
![image](https://github.com/open-telemetry/opentelemetry-go/assets/32633442/aad089ee-f39d-40a1-a123-0ecbaa5d7456)
trace_id and span_id is empty

GetTraceIds function
image
![image](https://github.com/open-telemetry/opentelemetry-go/assets/32633442/fdbb144f-790a-4572-8a21-1d4fd1b0d251)

Environment
go version: 1.22.4
gin version (or commit ref): github.com/gin-gonic/gin v1.10.0

**Comment by dmathieu** [comment]
cc @hanyuancheung

**Comment by dmathieu** [comment]
Did you setup otelgin, as documented in this example?
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/github.com/gin-gonic/gin/otelgin/example/server.go#L36

Could you provide us with a small app reproducing the issue?

**Comment by pepea23** [comment]
> Did you setup otelgin, as documented in this example? https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/github.com/gin-gonic/gin/otelgin/example/server.go#L36
> 
> Could you provide us with a small app reproducing the issue?

here is my example reproducing

`package main

import (
	"context"
	"log"
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
	"go.opentelemetry.io/contrib/exporters/autoexport"
	"go.opentelemetry.io/contrib/instrumentation/github.com/gin-gonic/gin/otelgin"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/propagation"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	"go.opentelemetry.io/otel/trace"
)

var healthcheckPaths = []string{"/healthz", "/healthcheck/liveness", "/v4/healthcheck/liveness"}

func isHealth(c *http.Request) bool {
	for _, healthcheckPath := range healthcheckPaths {
		if strings.HasPrefix(c.URL.Path, healthcheckPath) {
			return false
		}
	}
	return true
}

func init() {
}

func main() {
	cleanup := initTracer()
	defer cleanup(context.Background())
	routers := gin.New()
	InitRouter(routers)

	routers.Use(otelgin.Middleware("gateway-web", otelgin.WithFilter(isHealth)))

	err := routers.Run(":8080")
	if err != nil {
		log.Fatal(err.Error())
	}
}

func initTracer() func(context.Context) error {

	exporter, err := autoexport.NewSpanExporter(
		context.Background(),
	)
	if err != nil {
		log.Print(err.Error())
	}

	otel.SetTracerProvider(

		sdktrace.NewTracerProvider(
			sdktrace.WithSampler(sdktrace.AlwaysSample()),
			sdktrace.WithBatcher(exporter),
		),
	)

	otel.SetTextMapPropagator(propagation.NewCompositeTextMapPropagator(propagation.TraceContext{}, propagation.Baggage{}))
	return exporter.Shutdown
}

func InitRouter(router *gin.Engine) {
	router.GET("/hello", func(ctx *gin.Context) {
		traceId, spanId := GetTraceIds(ctx)
		log.Print("traceId : ", traceId)
		log.Print("spanId : ", spanId)
		ctx.JSON(200, "hello")
	})
}

func GetTraceIds(ctx *gin.Context) (traceId string, spanId string) {
	spanContext := trace.SpanFromContext(ctx.Request.Context()).SpanContext()
	if spanContext.IsValid() {
		traceId = spanContext.TraceID().String()
		spanId = spanContext.SpanID().String()
	}
	return traceId, spanId
}
`

**Comment by dmathieu** [comment]
```golang
InitRouter(routers)
routers.Use(otelgin.Middleware("gateway-web", otelgin.WithFilter(isHealth)))
```

You need to inverse those two. If you define middlewares after your routes, gin executes them after routes (or not at all it seems).

```golang
routers.Use(otelgin.Middleware("gateway-web", otelgin.WithFilter(isHealth)))
InitRouter(routers)
```

**Comment by pepea23** [comment]
thank you :)
