### ISSUE TITLE
Use logtest.AssertRecordEqual in otellogrus test

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-contrib#5851]
_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5847#discussion_r1663893751_

**Comment by dmathieu** [comment]
I solved that problem in https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5852 by using `j.Record`, which is made available by `EmittedRecord`.

**Comment by dmathieu** [comment]
>  the EmittedRecord return for a recorder needs to be reconsidered in logtest.

We need `EmittedRecord` if we want to keep storing the context.

> An AssertEmittedRecordEqual should be added

That assertion would probably have to check for the context as well, which we wouldn't want to do in the logrus bridge anyway.
