### ISSUE TITLE
Proposal to Add Arm64 Support Using GitHub Actions for Testing

### ISSUE THREAD

**Issue by ryuichi1208** [open-telemetry/opentelemetry-go-contrib#5865]
### Problem Statement

Problem Statement
Our current project does not support the arm64 architecture, which limits our deployment options and restricts testing on modern hardware that uses arm64 processors.

### Proposed Solution

Recently, it has become possible to run tests on Arm64 using GitHub Actions. Do we have plans to support this in the future?

https://github.blog/changelog/2024-06-24-github-actions-ubuntu-24-04-image-now-available-for-arm64-runners/

**Comment by dmathieu** [comment]
Thank you for the report. We're actually already doing that in the SDK, even though not with the new GitHub runners (yet).
I have opened https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5868 which does the same as in the SDK, but for this repository.
