### ISSUE TITLE
Add an option for default attributes to be included on http transport

### ISSUE THREAD

**Issue by luca-filipponi** [open-telemetry/opentelemetry-go-contrib#5877]
Currently, there is no option to include some default attributes for http transport metrics, custom attributes can only be added via the labeler in the request context.

If you want to create an http client and always include some attributes (for example the client name), you need to create a wrapper and add these attributes on a request basis.

I've made a draft pr to show how this could be done: https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5876

**Comment by pellared** [comment]
@luca-filipponi, why was it reopened?
