### ISSUE TITLE
Upgrade v1.24.0 to v1.26.0 semconv for otelhttp

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-contrib#5902]
An audit of the new semconv for any additions missing will be needed.

**Comment by VinozzZ** [comment]
Hi @MrAlias , I would like to work on this issue.

FYI, based on this message in [CNCF's slack ](https://cloud-native.slack.com/archives/C01NJ7V1KRC/p1716316290206639), it's called out by the Semconv Maintainers that adoption for HTTP should wait until final migration to stabilized semconv is ready.

**Comment by MrAlias** [comment]
> Hi @MrAlias , I would like to work on this issue.
> 
> FYI, based on this message in [CNCF's slack ](https://cloud-native.slack.com/archives/C01NJ7V1KRC/p1716316290206639), it's called out by the Semconv Maintainers that adoption for HTTP should wait until final migration to stabilized semconv is ready.

The note you linked to is referring to database semantic conventions:

> Quite a few DB related breaking changes are in this release.  As with HTTP, please hold on adopting these until final migration to stabilized semconv is ready.

The HTTP semantic conventions are already stable: https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-spans.md

Though an audit of any additions between v1.24.0 and v1.26.0 needs to be done. These are allowed stable changes.

**Comment by VinozzZ** [comment]
Thank you for the clairification!

It looks like we have a few new attributes that currently are all under `experimental` status
[Add url.template to HTTP client attributes](https://github.com/open-telemetry/semantic-conventions/commit/eb859d55d66a63bd6b2cde3d57c8758d5b023caf)
[Add experimental HTTP attributes to HTTP spans](https://github.com/open-telemetry/semantic-conventions/commit/30402c468f38c8d0250fa37b1dda590bfb9f81f2). The list of attributes are

For both client and server side:
- `http.request.size`
- `http.response.size`
- `http.request.body.size`
- `http.response.body.size`

For only client side:
- `url.template`

**Comment by MrAlias** [comment]
Gotcha :+1: . We'll want to not add anything experimental at this point.

Sounds like the upgrade without those additions should just be a version bump then.

**Comment by VinozzZ** [comment]
I assume we will do this after we finish adding support for v1.24.0. Is that correct?

**Comment by MrAlias** [comment]
> I assume we will do this after we finish adding support for v1.24.0. Is that correct?

Possibly. Adding experimental semantic conventions is what got us into this dual export situation.

We will likely not add them at all until stable. Or add them behind a flag.

**Comment by VinozzZ** [comment]
That makes sense.

I'm trying to figure out where we define the semconv version is defined for otelhttp.
Is this the right place? https://github.com/open-telemetry/opentelemetry-go-contrib/blob/dedcf91a55a36a5a8589c56f2e43c188eb42f4f2/instrumentation/net/http/otelhttp/version.go#L7

**Comment by MrAlias** [comment]
Here: https://github.com/open-telemetry/opentelemetry-go-contrib/blob/dedcf91a55a36a5a8589c56f2e43c188eb42f4f2/instrumentation/net/http/otelhttp/internal/semconv/v1.24.0.go#L11

That file likely needs to be renamed as well. Please rename to something that doesn't include the version in the name.

**Comment by MadVikingGod** [comment]
#5923 fixed this.
