### ISSUE TITLE
`otelslog` Handler support different group attribute data model

### ISSUE THREAD

**Issue by magodo** [open-telemetry/opentelemetry-go-contrib#5915]
### Problem Statement

Currently, the following `WithGroup` usage ends up with a nested hierarchy of KV pairs:

```
	// Groups are represented as map value types in OpenTelemetry. This means
	// that for an slog group hierarchy like the following ...
	//
	//   WithGroup("G").WithGroup("H").WithGroup("I")
	//
	// the corresponding OpenTelemetry log value types will have the following
	// hierarchy ...
	//
	//   KeyValue{
	//     Key: "G",
	//     Value: []KeyValue{{
	//       Key: "H",
	//       Value: []KeyValue{{
	//         Key: "I",
	//         Value: []KeyValue{},
	//       }},
	//     }},
	//   }

```

### Proposed Solution

There wants a way to change the log data model for the grouped attributes.

E.g. Given:

```
WithGroup("G").WithGroup("H").WithGroup("I")
```

User shall be able to have the following data model:

```
   KeyValue{
     Key: "G.H.I",
     Value: []KeyValue{}
   }
```

Similar to the behavior of `slog.TextHandler`:

```go
	logger = logger.WithGroup("G").WithGroup("H").WithGroup("I")
	logger.Info("wubalubadubdub", "name", "Rick")
```

Output:

```go
time=2024-07-16T15:45:09.533+08:00 level=INFO msg=wubalubadubdub G.H.I.name=Rick
```

#### Prior Art

A clear and concise list of any similar and existing solutions from other projects that provide context to possible solutions.

### Additional Context

There are some platform has poor support for the current group attribute model, e.g. the platform is table based, that it assumes the attributes have only one level.

**Comment by MrAlias** [comment]
Thank you for your interest in the project. The hierarchical design of how groups are represented match the allowed and expected structure of OTLP. We do no plan to flatten this structure for this one special case.

Please note that the processing pipeline is flexible. Feel free to build your own exporter that implements this flattening behavior if you find it desirable.
