### ISSUE TITLE
Add log bridge for log

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-contrib#5963]
Add a log bridge for [`log`](https://pkg.go.dev/log) which implements `io.Writer` and can be set via https://pkg.go.dev/log#Logger.SetOutput.

Each log call on `log.Logger` causes a single Write call on the passed `io.Writer`: https://cs.opensource.google/go/go/+/refs/tags/go1.22.5:src/log/log.go;l=245

The bridge factory should accept to options set `prefix` and `flag` (e.g. see https://pkg.go.dev/log#New) values which will help parsing the log line.

**Comment by pohly** [comment]
Who uses https://pkg.go.dev/log? Is that really needed?

**Comment by pellared** [comment]
From https://pkg.go.dev/log?tab=importedby:

> Known importers: 1,117,071 

Only public repos. For some software `log` is really good enough.

**Comment by pellared** [comment]
@khushijain21, do you want to take this issue?

**Comment by pohly** [comment]
> For some software log is really good enough. 

And you you expect such software to use opentelemetry?

> Known importers: 1,117,071

Kubernetes imports it, but we don't use it. The situation might be similar elsewhere. All the serious users that I know about who care about logging and telemetry are using more advanced logging solutions - but perhaps I have a biased view.

**Comment by pellared** [comment]
>  All the serious users that I know about who care about logging and telemetry are using more advanced logging solutions 

It all depends. I recommend reading: https://peter.bourgon.org/blog/2016/02/07/logging-v-instrumentation.html. Logging can be very expensive and some software do it only when there is no other way to report problems.

**Comment by khushijain21** [comment]
I'll pick this up if we decide to move forward

**Comment by pellared** [comment]
I propose to add `go.opentelemetry.io/contrib/bridges/otellog` bridge.
I can be a codeowner together with @khushijain21.

I think we should start with a draft PR with the intended implementation (as usual). Then after initial approval create smaller PRs with unit tests, benchmarks, etc.

**Comment by MrAlias** [comment]
Isn't the default output for log now slog? Why not just rely on that bridge?

**Comment by pellared** [comment]
**SIG meeting:**
Because `log` does not handle context correlation nor structured logging users may see almost no value from this and may expect to request for some custom parsing. Because of this we prefer to not add a bridge for `log` in this repository as it will be too poor or underperforming. We prefer to have it in some external repository and adding to OTel Registry. If an external package would occur to be very popular and successful then it can always be moved here.
