### ISSUE TITLE
Do not publish otelzerolog as it is not handling core functionality

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-contrib#5969]
This Issue originates from a SIG discussion around https://github.com/open-telemetry/opentelemetry-go-contrib/issues/5963#issuecomment-2263628919 on 2024-08-01.

With `otelzerolog` bridge not being able transform fields into attribute nor handle context correlation (because of https://github.com/rs/zerolog/issues/493), we do not see value in publishing (and even maintaining) `otelzerolog.`

Can we move this module to a separate repository until https://github.com/rs/zerolog/issues/493 is solved?

CC @dmathieu @AkhigbeEromo

**Comment by AkhigbeEromo** [comment]
I will like to take it

**Comment by pellared** [comment]
@AkhigbeEromo, I assigned it to you. Please create a PR that removes the `otelzerolog` and share with us where you are migrating it. After the migration you can add it to the OTel Registry. So far I created a PR to remove `otelzerolog` from OTel Registry: https://github.com/open-telemetry/opentelemetry.io/pull/4932

**Comment by MrAlias** [comment]
@pellared is going to create a PR to just remove this. The clone of this can reference the history of the repository to make the copy.

**Comment by pellared** [comment]
@AkhigbeEromo I created https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5996 as it is blocking the next release of OTel Go. Still, feel free to move the code to a fork and add it to the OTel Registry. Please make sure to keep the "license header" in the files to not violate the licensing.

**Comment by AkhigbeEromo** [comment]
Hello @pellared 
How do I add the code to Otel registry

**Comment by pellared** [comment]
The reverse of https://github.com/open-telemetry/opentelemetry.io/pull/4932

**Comment by AkhigbeEromo** [comment]
I have the code on a branch of my fork of the repo, I will add it to the Otel registry
Thank you @pellared 
Is there anything else to do?

**Comment by pellared** [comment]
Calling it "fork" was not precise. I mean move this module to a separate repository e.g. https://github.com/AkhigbeEromo/otelzerolog.

After you move the code and publish a release, you can add it to the registry by summitting a PR in https://github.com/open-telemetry/opentelemetry.io
