### ISSUE TITLE
Make Otel HTTP produce old and new Server Metrics

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/opentelemetry-go-contrib#5972]
Make `instrumentation/net/http/otelhttp` produce Server Metrics following the migration plan #5132.

A user should be able to produce Metrics from the `handler` in current semconv (default), and the latest semconv (1.26.0) based on the Environment variable `OTEL_HTTP_CLIENT_COMPATIBILITY_MODE`

- [x] Produce Old Server Metrics https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5818
- [ ] Produce New Server Metrics

**Comment by MrAlias** [comment]
Closing. Will split remaining work to dedicated issue.
