### ISSUE TITLE
bug: OtelGrpc not record error, added an event when panic

### ISSUE THREAD

**Issue by afifurrohman-id** [open-telemetry/opentelemetry-go-contrib#6094]
### Description

When a handler panic we may have interceptor for recover that panic.
But, when add an event or set otel status to error from interceptor when panic occur is not work, even a span is also valid

### Environment

- OS: `Linux ⭐ 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 GNU/Linux`
- Architecture: x86_64
- Go Version: 1.22
- `otelgrpc` version: `v0.54.0`

### Steps To Reproduce

1. Modify [existing server example](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/google.golang.org/grpc/otelgrpc/example/server/main.go) to add recovery interceptor
```go
s := grpc.NewServer(
                grpc.StatsHandler(otelgrpc.NewServerHandler()),
                grpc.UnaryInterceptor(
                        func(ctx context.Context, req any, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (resp any, err error) {
                                span := trace.SpanFromContext(ctx)
                                defer span.End()

                                span.AddEvent("interceptor is call")
                                defer func() {
                                        if r := recover(); r != nil {
                                                slog.Info("PANIC OCCUR")

                                                fmt.Println("IS SPAN IS VALID", span.SpanContext().IsValid())

                                                span.AddEvent("PANIC OCCUR")

                                                pErr := errors.New(fmt.Sprintf("%v", r))

                                                span.RecordError(pErr)
                                                span.SetStatus(codes.Error, "PANIC OCCUR")

                                                err = status.Error(grpccode.Internal,pErr.Error())
                                        }
                                }()

                                return handler(ctx, req)
                }),
        )
```
3. Modify existing hello world server rpc method to add panic and add an event
```go
func (s *server) SayHello(ctx context.Context, in *api.HelloRequest) (*api.HelloResponse, error) {
	span := trace.SpanFromContext(ctx)
	defer span.End()

	span.AddEvent("Say hello")

	log.Printf("Received: %v\n", in.GetGreeting())
	s.workHard(ctx)
	time.Sleep(50 * time.Millisecond)

	panic("UPS")

	return &api.HelloResponse{Reply: "Hello " + in.Greeting}, nil
}
```
5. Run the server and make request with client

### Expected behavior

It should set OTel status to Error, record an error and add an event

**Comment by amanakin** [comment]
Hello @afifurrohman-id!

You use `span.End()` incorrectly, according to description:
> End ends the span. This method does nothing if the span is already ended or is not being recorded.
In the current implementation, after `SayHello` has finished, the span is no longer recording. As a result, subsequent calls to `span.End()` do not have the effect.

To address this, you can remove all your `span.End()` calls and events and statuses from interceptor will be available.
In server example `span.End()` is called because it is a new span (not Server span).
This span exists only in `workHard` scope.
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/9f2491a1c0c6aac2774d1184c2924dc705d3a43d/instrumentation/google.golang.org/grpc/otelgrpc/example/server/main.go#L46

**Comment by afifurrohman-id** [comment]
> Hello @afifurrohman-id!
> 
> You use `span.End()` incorrectly, according to description:
> 
> > End ends the span. This method does nothing if the span is already ended or is not being recorded.

I see, looks like i miss understand how span works.

Does this span will automatically close by server (`otelgrpc`)?

> To address this, you can remove all your `span.End()` calls and events and statuses from interceptor will be available. In server example `span.End()` is called because it is a new span (not Server span). This span exists only in `workHard` scope.

I can confirm this works, thankyou...

**Comment by dmathieu** [comment]
Yes, the entire purpose of the otelgrpc middleware is to start and end spans based on the lifecycle of a request. So it will be ended automatically.

See https://github.com/open-telemetry/opentelemetry-go-contrib/blob/53b99aea3498ec571a045ef9e1dd2a220f98ba6e/instrumentation/google.golang.org/grpc/otelgrpc/stats_handler.go#L188-L204

Closing this, as it appears this isn't an actual issue.
