### ISSUE TITLE
superfluous response.WriteHeader call on errors

### ISSUE THREAD

**Issue by stmcginnis** [open-telemetry/opentelemetry-go-contrib#6112]
### Description

My basic web app has been seeing "superflous response.WriteHeader call" errors in the logs when someone hits on invalid endpoint. This same behavior has been observed here: https://github.com/prometheus/prometheus/issues/13678

I think I may see where this is happening. I could probably write up a small repro, but I hope this description is enough to go on based on what I've seen.

Many [tutorials](https://edgedelta.com/company/blog/how-to-instrument-a-go-application-using-opentelemtry-complete-guide-best-practices) out there show instrumenting the individual route:

```go
handleFunc := func(pattern string, handlerFunc func(http.ResponseWriter, *http.Request)) {
	handler := otelhttp.WithRouteTag(pattern, http.HandlerFunc(handlerFunc))
	mux.Handle(pattern, handler)
}

handleFunc("/spinwheel", spinwheel)
```

as well as installing a server-wide handler:

```go
// Add HTTP instrumentation for the whole server
handler := otelhttp.NewHandler(mux, "/")
```

This works fine under normal operations. But if there is a problem, like possibly the side effects from high memory usage mentioned in the issue linked above, I see this error message. It appears when `http.Error()` is used, the first `Error()` does is write the status code in the header. But `http.Error` also takes a string to return. So in the `Error()` code, [it writes the header, then writes to the ResponseWriter](https://github.com/golang/go/blob/eb975601a07ad25a47fdcb0cc6166ec695973d3e/src/net/http/server.go#L2251-L2252).

In the `RespWriterWrapper`, I'm seeing the `writeHeader` call happen twice for this error. The first time I believe is from the direct header write from `http.Error()`, then the second one from the write of the string content.

I think there is a bug in `RespWriterWrapper`'s logic for `writeHeader()`. In the [code](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/d312469f21ca6606e872292bdca206b2680608d3/instrumentation/net/http/otelhttp/internal/request/resp_writer_wrapper.go#L76) it checks `if !w.wroteHeader`. If it hadn't written the header it will set the flag to true. But the problem here is that regardless of whether the flag is `true` or `false` it will still fall through and attempt to call `WriteHeader` at the end.

I believe this is where the original issue error message is coming from. if `w.wroteHeader` is `true` it should just return. Walking through the code execution, on the second call to `RespWriterWrapper.writeHeader()` the flag is correctly set to `true`, but it still tries to set the header anyway.

### Environment

- OS: Linux
- Architecture: x86_64
- Go Version: 1.23
- `go.opentelemetry.io/contrib` version: [e.g. v0.14.0, 3c7face]

```
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.54.0
go.opentelemetry.io/otel v1.29.0
go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc v1.29.0
go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.29.0
go.opentelemetry.io/otel/metric v1.29.0
go.opentelemetry.io/otel/sdk v1.29.0
go.opentelemetry.io/otel/sdk/metric v1.29.0
go.opentelemetry.io/otel/trace v1.29.0
```

### Steps To Reproduce

See description above. I think this is possible with a basic `http.Serve` instrumented setup. I do not have a simple repro handy, but if the above is not enough I can look in to doing that.

### Expected behavior

`http.Error()` calls result in returned error to client and no logs showing superfluous WriteHeader calls are being made.

**Comment by dmathieu** [comment]
This appears to be a duplicate of https://github.com/open-telemetry/opentelemetry-go-contrib/issues/6053.

**Comment by stmcginnis** [comment]
#6055 does indeed fix the issue. Sorry I missed that, but things are looking great with the latest release.
