### ISSUE TITLE
Redis attributes not aligned with latest semantic conventions

### ISSUE THREAD

**Issue by luke6Lh43** [open-telemetry/opentelemetry-go-contrib#6152]
### Description

Hello,

I have recently been working on a project that required Redis instrumentation for two different languages. During this process, I noticed some discrepancies in the attributes being collected. To investigate further, I conducted testing to check the attributes collected for Redis instrumentation across six of the most popular languages. I have documented my testing in this GitHub repository:

[[Link to GitHub Repo]](https://github.com/luke6Lh43/otel-redis-testing)

Findings for Go:

What We Capture Today ==> How It Should Look in Latest Semantic Conventions

server.address: localhost  ==> server.address: localhost
server.port: 6379 ==> server.port: 6379
db.system: redis ==> db.system: redis
db.connection_string: redis://localhost:6379 ==> Not needed
db.statement: get id1234 ==> db.query.text: get id1234
(Not captured) ==> db.redis.database_index: 0

The latest OpenTelemetry semantic conventions for Redis can be found here:
[OpenTelemetry Semantic Conventions for Redis](https://opentelemetry.io/docs/specs/semconv/database/redis/)

### Environment

OS: macOS Sequoia
Architecture: x86_64 (Intel processor)
Go Version: go1.23.1
go-redis/v9 version: v9.6.1
go.opentelemetry.io/otel version: v1.30.0

### Steps To Reproduce

https://github.com/luke6Lh43/otel-redis-testing/blob/main/Readme.md#go

### Expected behavior

N/A

**Comment by dmathieu** [comment]
The redis instrumentation is not within this repository, but at https://github.com/redis/go-redis/tree/master/extra/redisotel
You're importing that package within your code: https://github.com/luke6Lh43/otel-redis-testing/blob/fad280f01a3a4c94f8d52b9f276148f609eb84e3/go-redis/main.go#L10C6-L10C50

That go-redis repository is where the fix should happen, and where your issue should be opened, not here.
