### ISSUE TITLE
Lychee CI failure: 429 too many requests

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-contrib#6183]
```
### Errors in ./RELEASING.md

* [429] [https://github.com/open-telemetry/opentelemetry-go/commits/main](https://github.com/open-telemetry/opentelemetry-go/commits/main) | Failed: Network error: Too Many Requests
```

Example: https://github.com/open-telemetry/opentelemetry-go-contrib/actions/runs/11151936706/job/30996462798?pr=6002

**Comment by dmathieu** [comment]
The two fixes here could be to get https://github.com/lycheeverse/lychee/pull/1403 to move forward, so a links check that fails would still update the cache with URLs that succeeded, making retries only fetch the previously failing URLs, and fixing rate limit issues.

If we can't get that moving, we'll have to disable the links check temporarily, or have it consider 429s as success.
