### ISSUE TITLE
SpanName is overwritten to <ip>:<port> if HTTPServerAttributesFromHTTPRequest is used

### ISSUE THREAD

**Issue by brugnara** [open-telemetry/opentelemetry-go-contrib#622]
Hi everyone!

I noticed that Gin instrumentation works, but the name is not the path, but always 127.0.0.1:8000 and this happens because of this line:

https://github.com/open-telemetry/opentelemetry-go-contrib/blob/7a8e6f588651f5bbe78dd809be4d40f79627d60c/instrumentation/github.com/gin-gonic/gin/otelgin/gintrace.go#L68

See how it is *with* the line:

![image](https://user-images.githubusercontent.com/2781191/111318551-748abb80-8665-11eb-8479-3e53e62bccda.png)

And how it is if I remove it:

![image](https://user-images.githubusercontent.com/2781191/111318407-502edf00-8665-11eb-88fe-c38632be002d.png)

Will do a PR if it's the case but the strange thing here is that tests are passing so I just want to be sure what's the hidden deal I'm surely missing here.

Thank you for considering my request.

**Comment by matej-g** [comment]
Hi! Would you be able to provide a code snippet of how you're using the instrumentation or some more context? Where are you exporting it?

Indeed, nothing in `semconv.HTTPServerAttributesFromHTTPRequest` _should_ be affecting the span name and I was not able to observe this either in the tests or in the [example](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation/github.com/gin-gonic/gin/otelgin/example).

**Comment by brugnara** [comment]
I updated to 0.18 and the problem is now different.

In my opinion the output is generated in a way that works for OpenTelemetry but problems arise when an agent needs to send to x-ray, for example, the example you linked, outputs:

```json
"Name": "getUser",
```

which is correct, but below in the same JSON:

```json
		"Resource": [
			{
				"Key": "service.name",
				"Value": {
					"Type": "STRING",
					"Value": "unknown_service:example"
				}
			},
```

This service.name is what x-ray uses for naming, and with the version 0.18, this happens because `oteltrace.WithSpanKind(oteltrace.SpanKindServer)` is used.

Closing because it's not a problem for gintrace itself but specific for my use case.

**Comment by brugnara** [comment]
@bryanpaluch this problem for me happened because the version that is installed with the go get sometimes it is wrong.

Check this search for better understand: https://pkg.go.dev/search?q=opentelemetry+contrib+gin&m=

You may need the 0.26 version but it is super easy to install the old 0.11 if you do a little edit in the search query: https://pkg.go.dev/search?q=opentelemetry+gin&m=package

So, double check in the go.mod what the version is and be sure to use the last one.

Hope this helps.
