### ISSUE TITLE
otelslog: WithSource

### ISSUE THREAD

**Issue by Jesse0Michael** [open-telemetry/opentelemetry-go-contrib#6244]
### Problem Statement

I would love to move to an otel logger from slog using the slog bridge, but there is one feature that I would miss.
The [HandlerOptions](https://pkg.go.dev/log/slog#HandlerOptions) used to configure a slog JSONHandler or TextHandler allow for a bool toggle `AddSource` which, when set, will include the source file information of where the log occurred in the log attributes.
### Proposed Solution

I would like to add a bool `source` field to the otelslog [config](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/bridges/otelslog/handler.go#L63-L67) that is set in a new  `WithSource` Option that takes a bool as a parameter. When `source` is set, the otelbridge would [mimic the behavior](https://cs.opensource.google/go/go/+/master:src/log/slog/record.go;l=214-226) of the slog options and include the source information of the log as attributes when [converting the slog record](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/bridges/otelslog/handler.go#L167-L199).

**Comment by dmathieu** [comment]
This makes sense. Do you want to work on a PR?
Should we also provide `ReplaceAttr`? (in a different PR)
