### ISSUE TITLE
Support Environment Variable Installation and Configuration of Jaeger Remote Sampler

### ISSUE THREAD

**Issue by pwinters-tanium** [open-telemetry/opentelemetry-go-contrib#6256]
### Problem Statement
The jaeger remote sampler does not currently support auto installation or configuration using the standard `OTEL_TRACES_SAMPLER` and `OTEL_TRACES_SAMPLER_ARG` environment variables (see [Environment Variable Specification](https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/)). Although this is not explicitly required by Otel specifications, it is a common practice that allows an application's tracing to be configured for different contexts without recompilation.

### Proposed Solution

The OTel golang SDK should automatically use the jaeger remote sampler when `OTEL_TRACES_SAMPLER` equals `jaeger_remote`.

The installed Jaeger Remote Sampler should use configuration values drawn by parsing `OTEL_TRACES_SAMPLER_ARG` as a comma separated list of `key=value` pairs that include keys `endpoint`, `pollingIntervalMs`, and `initialSamplingRate`.

> For jaeger_remote and parentbased_jaeger_remote: The value [of OTEL_TRACES_SAMPLER_ARG] is a comma separated list:
> - endpoint: the endpoint in form of scheme://host:port of gRPC server that serves the sampling strategy for the service ([sampling.proto](https://github.com/jaegertracing/jaeger-idl/blob/master/proto/api_v2/sampling.proto)).
> - pollingIntervalMs: in milliseconds indicating how often the sampler will poll the backend for updates to sampling strategy.
> - initialSamplingRate: in the [0..1] range, which is used as the sampling probability when the backend cannot be reached to retrieve a sampling strategy. This value stops having an effect once a sampling strategy is retrieved successfully, as the remote strategy will be used until a new update is retrieved.
>
> Example: endpoint=http://localhost:14250,pollingIntervalMs=5000,initialSamplingRate=0.25

[Reference: Docs - Specs - OTel 1.38.0 - Configuration - Env var](https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/)

**Comment by RichardChukwu** [comment]
Hello @pwinters-tanium is this currently being worked on please?

**Comment by akstron** [comment]
Hi @pwinters-tanium , if I understand it correctly, we want to override the values used in code (which is used while creating the sampler) with values specified in environment variable?

**Comment by pwinters-tanium** [comment]
@RichardChukwu, no I am not currently working on this.
@akstron, this would remove the need to configure the jaeger remote sampler in code. the otel project seems to promote specification and configuration of samplers by environment variable.

**Comment by dmathieu** [comment]
cc @yurishkuro as code owner of this component.
