### ISSUE TITLE
otelzap: Ability to configure loglevel

### ISSUE THREAD

**Issue by Jamess-Lucass** [open-telemetry/opentelemetry-go-contrib#6283]
### Problem Statement

There doesn't seem to be a way to configure a minimum log level with otelzap.

### Proposed Solution

Add a new option with allows you to set the minimum log level

```go
otelzap.NewCore("test", otelzap.WithLogLevel(zapcore.ErrorLevel))
```

Which can then be checked within the `Check` func.

#### Alternatvies

Similar to [`zapcore.NewCore()` ](https://github.com/uber-go/zap/blob/0ba452dbe15478739ad4bab1067706018a3062c6/zapcore/core.go#L58), have the ability to pass a minimum log level when calling `otelzap.NewCore()`

#### Prior Art

A clear and concise list of any similar and existing solutions from other projects that provide context to possible solutions.

**Comment by scorpionknifes** [comment]
Hello, would the following be suitable for your use case? In most log bridges we rely on `logger.Enabled` to check whether a log level is enabled: https://github.com/open-telemetry/opentelemetry-go-contrib/blob/c1cdce774e78992f5973cb69bf4844ecadd7fbcd/bridges/otelzap/core.go#L143-L148
you can set the logger level by creating a custom log processor. See: https://pkg.go.dev/go.opentelemetry.io/otel/sdk/log#Processor
you can also take a look at: https://github.com/open-telemetry/opentelemetry-go/issues/5078

**Comment by MrAlias** [comment]
This option would be in direct contradiction to how OTel manages minimum logging levels. It is not the library author who should be deciding what minimum is used, it is the operator. That means the person constructing and installing the SDK. Please see go.opentelemetry.io/contrib/processors/minsev for how to configure the minimum severity logged by the OTel SDK.

**Comment by Jamess-Lucass** [comment]
> Hello, would the following be suitable for your use case? In most log bridges we rely on `logger.Enabled` to check whether a log level is enabled:
> 
> https://github.com/open-telemetry/opentelemetry-go-contrib/blob/c1cdce774e78992f5973cb69bf4844ecadd7fbcd/bridges/otelzap/core.go#L143-L148
> 
> 
> you can set the logger level by creating a custom log processor. See: https://pkg.go.dev/go.opentelemetry.io/otel/sdk/log#Processor
> you can also take a look at: [open-telemetry/opentelemetry-go#5078](https://github.com/open-telemetry/opentelemetry-go/issues/5078)



> This option would be in direct contradiction to how OTel manages minimum logging levels. It is not the library author who should be deciding what minimum is used, it is the operator. That means the person constructing and installing the SDK. Please see [go.opentelemetry.io/contrib/processors/minsev](https://pkg.go.dev/go.opentelemetry.io/contrib/processors/minsev) for how to configure the minimum severity logged by the OTel SDK.

Thank you both, this is exactly what I was looking for :)
