### ISSUE TITLE
otelhttp still uses old semconv, resulting in `exemplar label name "net.host.name" is invalid` errors

### ISSUE THREAD

**Issue by xsteadfastx** [open-telemetry/opentelemetry-go-contrib#6398]
### Description

the otelhttp tracer throws me some errors in production code. i dont know if its just warnings or errors. but on tracing i get this

```
Dez 04 09:24:47 templeton hemingway[695]: 2024/12/04 09:24:47 exemplar label name "net.protocol.version" is invalid
Dez 04 09:24:47 templeton hemingway[695]: 2024/12/04 09:24:47 exemplar label name "net.protocol.version" is invalid
Dez 04 09:24:47 templeton hemingway[695]: 2024/12/04 09:24:47 exemplar label name "net.protocol.name" is invalid
```

i checked the code and saw that it semconvutil still depends on semconv version 1.20.0 which has `net.protocol.version` and so on as keys. 

### Environment

- OS: linux
- Architecture: amd64
- Go Version: 1.23.3
- `go.opentelemetry.io/contrib` version: v0.57.0

### Expected behavior

using valid label names.

**Comment by dmathieu** [comment]
There are breaking changes between those semconv versions. So we can't just update them.
See this migration plan: https://github.com/open-telemetry/opentelemetry-go-contrib/issues/5132

Right now, setting the `OTEL_SEMCONV_STABILITY_OPT_IN` environment variable with a value of `http/dup` will duplicate the attributes so they match both semantic conventions.
Right now, if you don't specify this config, we still emit the 1.20.0 attributes. In the near future, the default behavior will change, and the default attributes will be on 1.26.0.

Closing this issue, as it's a migration we're already tracking.

**Comment by xsteadfastx** [comment]
ok thanks for the info. added the env variable. i still get the 

```
Dez 04 14:57:27 templeton hemingway[697]: 2024/12/04 14:57:27 exemplar label name "http.scheme" is invalid
Dez 04 14:57:27 templeton hemingway[697]: 2024/12/04 14:57:27 exemplar label name "net.host.name" is invalid
Dez 04 14:57:27 templeton hemingway[697]: 2024/12/04 14:57:27 exemplar label name "net.protocol.version" is invalid
```

this still should apperar right? because labels get duplicated.

**Comment by dmathieu** [comment]
Yes, this should still appear because the attributes are duplicated.

**Comment by xsteadfastx** [comment]
thanks alot for your informations :)
