### ISSUE TITLE
add support for contrib plugin mongodb 🍃

### ISSUE THREAD

**Issue by andrewhsu** [open-telemetry/opentelemetry-go-contrib#7]
https://github.com/mongodb/mongo-go-driver

This is done when:
- [x] code complete with tests passing
- [ ] `Dockerfile` with example app showing instrumentation
- [x] documentation updated
- [x] plugin added to the opentelemetry [registry](https://opentelemetry.io/registry/)

**Comment by andrewhsu** [comment]
#26

**Comment by andrewhsu** [comment]
@rnburn i think the other items in the description need to be ticked off as well when you get the chance.

**Comment by PaurushGarg** [comment]
@krnowak @andrewhsu @MrAlias please assign this issue to me. I can work on rest 3 points. I am working in @alolita team. 
Tag @alolita

**Comment by MrAlias** [comment]
This looks done.
