### ISSUE TITLE
Add Instrumentation for gofiber/fiber

### ISSUE THREAD

**Issue by rizalgowandy** [open-telemetry/opentelemetry-go-contrib#714]
## Background

**Package Link**: https://github.com/gofiber/fiber

Another go router, like echo and mux.

## Proposed Solution

Middleware

### Tracing

- attributes:
  - semconv.NetAttributesFromHTTPRequest
  - semconv.EndUserAttributesFromHTTPRequest
  - semconv.HTTPServerAttributesFromHTTPRequest
  - semconv.HTTPAttributesFromHTTPStatusCode
  - semconv.SpanStatusFromHTTPStatusCode
- events:
  - Incoming HTTP request
- links:
  - Unsure about this one

### Prior Art

https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation/github.com/labstack/echo/otelecho

## Tasks

- Code complete:
  - [ ] Comprehensive unit tests.
  - [ ] End-to-end integration tests.
  - [ ] Tests all passing.
  - [ ] Instrumentation functionality verified.
- Documented
  - [ ] Added to the [OpenTelemetry Registry](https://opentelemetry.io/registry/)
  - [ ] README included for the module describing high-level purpose.
  - [ ] Complete documentation of all public API including package documentation.
  - [ ] [Instrumentation documentation](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/README.md#instrumentation-packages) updated.
- Examples
  - [ ] `Dockerfile` file to build example application.
  - [ ] `docker-compose.yml` to run example in a docker environment to demonstrate instrumentation.

**Comment by rizalgowandy** [comment]
Since gofiber/fiber use valyala/fasthttp instead of net/http.
We shouldn't support it. I'll never use gofiber/fiber any more.
Hopefully the library will die out on its own, since it doesn't use the standardized way.

**Comment by lifepeer** [comment]
May I ask why the use of `valyala/fasthttp` instead of the much slower `net/http` should be an issue? `gofiber/fiber` is the second most popular Go framework in its category, the fastest, with active development and steady growth of its user base. I think it would be a mistake not to support it.
