### ISSUE TITLE
Extending functional options

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-contrib#746]
## Why

It would be good to provide guidance on how to extend on top of functional options API.

## What

Make vendor-specific (which may be not OTel compliant) extensibility "easy" and user-friendly.

The whole idea behind https://github.com/signalfx/splunk-otel-go is to create convenient and easy to use helpers that are working on top of OTel libraries. For example:

1. `splunkhttp.NewHandler` may set default otelhttp options
2. the user does not need to call `otelhttp.NewHandler`

I have experimented with 4 approaches. I will post them as separate comments so you can comment/upvote/downvote each one individually.

All of these approaches allow achieving the following usage code:

```go
handler = splunkhttp.NewHandler(handler, "server", otelhttp.WithTracerProvider(provider), splunkhttp.WithTraceResponseHeader(false))
```

The `splunkhttp.WithOTelOpts(....)` call is no longer needed.

All of the approaches are not making any breaking change.

I posted this issue because I think we should strive to use similar extensibility approaches across different vendors. 

### Blocking extensibility by design?

Is there any reason to do [such things](https://github.com/open-telemetry/opentelemetry-go/blob/b09df84a24b35cb5f287a501e31d9dec324be5a9/trace/config.go#L43-L46)? I would say it is blocking extensibility on purpose, but why? BTW even if I would like to do so I would rather unexport this method: https://github.com/open-telemetry/opentelemetry-go/blob/b09df84a24b35cb5f287a501e31d9dec324be5a9/trace/config.go#L41.

**Answered [here](https://github.com/open-telemetry/opentelemetry-go-contrib/issues/746#issuecomment-820434852).**

### Why functional options cannot return an error?

One of the main advantages of [functional options pattern](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis) is that it can be also used to encapsulate validation. How we would notify the client that his configuration passed to https://github.com/open-telemetry/opentelemetry-go-contrib/blob/e1a7c4781baf5716364bc5661052c5746e87e344/instrumentation/net/http/otelhttp/handler.go#L60 is invalid?

**Answered [here](https://github.com/open-telemetry/opentelemetry-go-contrib/issues/746#issuecomment-820434852).**

**Comment by pellared** [comment]
## Approach 1 - `WithNop` dummy option

Add `WithNop` functional option to make it easier to do a composition. 

Example: https://github.com/signalfx/splunk-otel-go/pull/37

**Pros:**
- It is not a breaking change - it does not touch any existing exported API.

**Cons**:
- Hacky
- Adding a dummy option to add extensibility feels wrong
- The extensibility code is noisy and not strightforward

**Comment by pellared** [comment]
## Approach 2 - `Config`

Export `Config` and unexport all its fields.
- Changes in OTel SDK: https://github.com/signalfx/splunk-otel-go/pull/39/files#r613507010 + all usages
- Changes in vendor repo: https://github.com/signalfx/splunk-otel-go/pull/39/files#diff-0ef2bba381e8157f09baa7100a4ea93855e194f5fd9b00bb73db2c9611a2c861
- Full PR for deeper analysis:  https://github.com/signalfx/splunk-otel-go/pull/39

**Pros:**
- It changes the existing API in a not breaking way

**Cons**:
- Having an exported struct with no exported fields feels wrong upfront
- The extensibility code is still noisy and not straightforward
- Sometimes exported fields are handy if one would like to marshall/unmarshall it

**Comment by pellared** [comment]
## Approach 3 - `interface`

Change `Apply` in `Option` interface to accept `interface{}` instead of `*config`.
- Changes in OTel SDK: 
- Changes in vendor repo: 
- Full PR for deeper analysis: 

**Pros:**
- It changes the existing API in a not breaking way
- The `Option` interface definition cleaner
- The vendor's `config.go` code is similar ("orthogonal") to its OTel SDKs counterpart 
- The vendor's code is shorter
- _From personal experience, I prefer to use type assertions rather than type embedding._

**Cons**:
- Forces to use type assertions in `Apply` method which is "less" type-safe (at least compiler is not helping that much)

**Comment by pellared** [comment]
I am extremely biased and subjective. I favour **Approach 3** after all my experiments. Feel free to point out other pros/cons and also feel free to argue if anything I described is not true.

**Comment by pellared** [comment]
## Approach 4  - type embedding + type assertion

Use type embedding and type assertion in vendor-specific repo. 
- Changes in OTel SDK: **NONE**
- Changes in vendor repo: https://github.com/signalfx/splunk-otel-go/pull/40/files#diff-0ef2bba381e8157f09baa7100a4ea93855e194f5fd9b00bb73db2c9611a2c861
- Full PR for deeper analysis: https://github.com/signalfx/splunk-otel-go/pull/40

It does not require any change.

**Pros:**
- This pattern can be applied most probably to any functional option API.

**Cons**:
- Uses both type assertions and type embedding which is not straightforward. As a rule of thumb, both language features should be used in moderation.

**Comment by pellared** [comment]
Personally, I would go for **approach 4**. 

However maybe after looking at this analysis we would still like to make some changes in the current OTel functional options design.

**Comment by tgulacsi** [comment]
otelhttp.Option is a function that applies to an inner structure with inner options - a black box.
I'd vote to option 4, as that's what respects this mostly.

Here you embed otelhttp's functionality, so you should embed their options, too - even better, hide them!
You don't want to allow ANY unknown option, as you don't know what to do with them.
Or if you want, then accept a preconfigured (otel)http.Handler, and decorate that only with splunk's functionality.

**Comment by pellared** [comment]
@tgulacsi First off all thanks for your comment 👍 

> You don't want to allow ANY unknown option, as you don't know what to do with them.

No sure if you are talking about Splunk or OTel package. However take notice that it is not possible to "not allow" external options (there is one possibility but it would result in very unfriendly API - unexport the Option interface). We can only make sure that external options are not processed. All described approaches achieve it (for OTel at least).

**Comment by tgulacsi** [comment]
otelhttp exposes several Option, but as a black box. Only those are usable os configuration-altering options.
At this level, exporting Option may be an error, but may help the documentation.

splunkhttp SHOULD NOT expose otelhttp options, MUST hide them behind a wrapper.

For me it's weird to allow any otelhttp option through splunkhttp. Esp. as they're in a  constant flux...
It's more flexible to allow a configured http.Handler, that may be an otelhttp.Handler, already configured.

**Comment by MadVikingGod** [comment]
So a bit of logistics before we get into any technical discussion. It seems like you have done a lot of work to explore these options, but you need a bit more to make it presentable to this audience.  What would go a long way to achieve this is:
1. An example of how you want to "Extend" the config.  Not just how you are using it, but what feature would make most sense in your copy of the config and not upstream (in here)
2. Your changes in each proposal in a format that is normally used here.  This would be a PR that encompasses just what was changed.  Right now the PRs linked have all of the library in green, so it is hard to tell what is already there and what you changed.
 
Remember you are asking for a review from others that don't know what you know and have limited time to review.  Try to make it easy for them to understand what you are changing and why.

As for the technical discussion:
Why are the configs not extendable?  Because they are intended to be a black box, only used by the tool that the config exists within.  Every change that we make to allow extensions has the potential to break extended versions as we change things.  If we make config members public we can't ever move away from them.  If we allow others to add members we will break any other implementation when we add a conflicting member.  This doesn't mean it's a hard No on extensibility, but there has to be good reasons to take on that burden.

Returning errors:
It is totally possible to return errors there, but by not doing so we put a constraint on ourselves to not return a self-inconsistent handler.  It may not work, but it won't work because of reasons that can not be determined at creation, e.g. wrong tls certs, not A and B can't be on at the same time.

**Comment by pellared** [comment]
@tgulacsi Thanks for clarification

> otelhttp exposes several Option, but as a black box. Only those are usable os configuration-altering options.
> At this level, exporting Option may be an error, but may help the documentation.

Returning an unexported type is highly discouraged. You cannot make a field, function, array variable (the last is critical for functional options) it the type is unexported. This is also why I have written "it would result in very unfriendly API". More: https://github.com/golang/lint/issues/210

> splunkhttp SHOULD NOT expose otelhttp options, MUST hide them behind a wrapper.

Thanks 👍  PRs fixed 

> For me it's weird to allow any otelhttp option through splunkhttp. Esp. as they're in a constant flux...
> It's more flexible to allow a configured http.Handler, that may be an otelhttp.Handler, already configured.

Good remark. It is designed that way so that:
1. `splunkhttp.NewHandler` may set default otelhttp options
2. the user does not need to call `otelhttp.NewHandler`

The whole idea of https://github.com/signalfx/splunk-otel-go is to create convenient and easy to use helpers that are working on top of OTel libraries.

**Comment by pellared** [comment]
@MadVikingGod I highly appreciate your comment. 

>[...] What would go a long way to achieve this is: [...]

Great guidance 👍  In progress...

> Why are the configs not extendable? 

Thanks. Currently, I only think that **approach 3** could make it extensibility easier, while still keeping the options as black boxes.

> Returning errors

Not sure if I follow. But I believe it would be better to create a separate issue 😉

**Comment by pellared** [comment]
@MadVikingGod I highly appreciate your comment. 

>[...] What would go a long way to achieve this is: [...]

Great guidance 👍 Done. Please review and feel free to tell me if I can make it more approachable (without making too much noise). 

> Why are the configs not extendable? 

Currently, I only think that **approach 3** could make the extensibility easier. While still keeping the options as black boxes.

> Returning errors

Not sure if I follow. But I believe it would be better to create a separate issue 😉

**Comment by Aneurysm9** [comment]
> Good remark. It is designed that way so that:
> 
>  1. `splunkhttp.NewHandler` may set default otelhttp options
>  2. the user does not need to call `otelhttp.NewHandler`

While I can understand the desire to have these properties, I think as it is currently structured it may prove overly limiting and lead to users to being unable to use it at all.  By having `splunkhttp.NewHandler` embed the creation of an `otelhttp.Handler` it is limiting users to that instrumentation and either foreclosing users of other instrumentations such as `otelecho` or `otelmux` or forcing them to accept or find workarounds for double instrumentation.

If, instead, the `splunkhttp` handler were designed to be composed with another handler that was responsible for span lifecycle management, then the `splunkhttp` handler could deal with only the `Option`s relevant to its internal workings and take the currently active span from the `request.Context()`.  It could then be used in any of these ways:

```go
splunkHandler := splunkhttp.NewHandler(handler, splunkhttp.WithFoo())

h := otelhttp.NewHandler(splunkHandler, otelhttp.WithBar())
h2 := otelmux.NewHandler(splunkHandler)
h3 := otelgin.NewHandler(splunkHandler, otelgin.WithBaz())
```

**Comment by pellared** [comment]
@Aneurysm9 Thanks for your insight 👍 

I think that what you presented can be done in Splunk in addition to one of the presented approaches. _And it can be also reused internally._

What you presented is more flexible and composable. However, it requires the client to write more code. Especially if we would like to set some default options (not sure if we have a use case for it TBH, but I imagine someone might want to add some default filter?). 

```go
splunkHandler := splunkhttp.NewHandler(handler, splunkhttp.WithFoo())
opts := splunkhttp.DefaultHttpOpts()
opts = append(otelHttpOpts, otelhttp.WithBar())
instrHandler := otelhttp.NewHandler(splunkHandler, opts...)
```

Compare it to:

```go
instrHandler := otelhttp.NewHandler(handler, splunkhttp.WithFoo(), otelhttp.WithBar())
```

Correct, the presented approach has to be implemented per each instrumentation. To achieve the same coding experience for `otelmux` and `otelecho` instrumentation, one would have to respectively create `splunkmux` and `splunkecho`. I just strive to offer [ease of programming](https://golang.org/doc/faq#creating_a_new_language),

Besides I guess that your comment would also be valid for extending instrumentations done on top of `database/sql` package 😉 

_PS. nit: Your code snippett probably should have `otelecho` instead of `otelgin` 😉_

**Comment by MadVikingGod** [comment]
If you are really looking to make programing this easier, then you should entirely encapsulate the otelhttp package.  Users of your package shouldn't know or have to find out what otelhttp configuration options there are, they should be using splunkhttp options.

This lets you keep up with changes to otelhttp at your pace, and if you want to keep in lockstep I would look at code generation, and it would mean users have only one location they have to search to understand what knobs they can configure.

I would also point out in what you linked:
> Orthogonality makes it easier to understand what happens when things combine.
If these are orthogonal features you should make the component orthogonal.  But you look to want to encapsulate, so you should make your component encapsulate entirely the API.

**Comment by pellared** [comment]
## Approach 5  - encapsulate the `otelhttp` and extend what is needed

by @MadVikingGod

Entirely encapsulate the `otelhttp` package and add all needed features. 
- Changes in OTel SDK: **NONE**
- Extending the in vendor repo: _use your imagination please_ 😉

It does not require any change.

**Pros:**
- The client does not need even to know nor import `otelhttp`
- _Possibily no dependency to otelhttp at all if the `otelhttp` code is copied instead of encapsulated_

**Cons**:
- Requires synchronization if there is ANY change in `otelhttp` API
- Lot of work to encapsulate/copy the `otelhttp` package. Could be solved by some kind of automation, but it is a more complex tool than both type embedding and type assertions.

**Comment by pellared** [comment]
@Aneurysm9 

I am getting convinced that your proposal is the most pragmatic one.
Besides what was already written there are more benefits of what you proposed:
1. Not mixing `splunkhttp.` and `otelhttp.` in a single line feels better and is easier to understand for the reader
2. It does NOT force to use the default options if one would be provided by `splunkhttp`. Functional options often make "unseting" configuration very hard.
3. It is the simplest approach.

At the same time, I start to feel that each of my proposed approaches are overcomplicated compared to the benefits that are achieved (and that are still very questionable).

**Comment by pellared** [comment]
## Approach 6  - do NOT extend, but create another middleware

by @Aneurysm9 

Create `splunkhttp.NewHandler` which may be composed with `otelhttp.NewHandler`
- Changes in OTel SDK: **NONE**
- Extending the in vendor repo: **IN PROGRESS**

It does not require any change.

**Pros:**
- The simplest, most composable and flexible approach
- Can be used for other instrumentation like `otelmux` and `otelecho` without writing any more code.

**Cons**:
- Client needs to write more code 
- The client needs to make sure that the order of composing handlers is correct

**Comment by pellared** [comment]
@Aneurysm9 @MrAlias 
We ended up with **Approach 6**.

Feel free to close the issue. I am not closing it, because maybe you want to have some follow up (e.g. docs) 😉  🤷
