### ISSUE TITLE
Prometheus as remote-write-receiver Encountered error 204 No Content

### ISSUE THREAD

**Issue by valdemarpavesi** [open-telemetry/opentelemetry-go-contrib#790]
### Description

Prometheus as remote-write-receiver
url: http://localhost:9090/api/v1/write 
Return success code "204 No Content"

but it will be considered as an error for  (pusher, err := cortex.InstallNewPipeline)

### Environment

- OS: Linux
- Architecture: [x86_64]
- Go Version: [go1.16.2]
- go.opentelemetry.io/otel v0.20.0

### Steps To Reproduce

1. run example:

https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/exporters/metric/cortex/example

2. deploy prometheus

`
docker run -u root -d -p 9090:9090 \
    -v $PWD/prometheus.yml:/etc/prometheus/prometheus.yml \
    --name prometheus \
    prom/prometheus --config.file=/etc/prometheus/prometheus.yml  --enable-feature=remote-write-receiver --enable-feature=exemplar-storage
`

3. config.yml opentelemtry to url: http://localhost:9090/api/v1/write 

### Expected behavior

fmt.Println("Encountered error: ", err.Error())

it will return:  Encountered error 204 No Content

**Comment by MrAlias** [comment]
Closing, stale. The cortex exporter and example were remove in https://github.com/open-telemetry/opentelemetry-go-contrib/releases/tag/v1.5.0
