### ISSUE TITLE
otelgprc: stream not closed on eof

### ISSUE THREAD

**Issue by tonistiigi** [open-telemetry/opentelemetry-go-contrib#818]
Currently, when stream interceptor is used it closes only if EOF is received and the client also calls `CloseSend` https://github.com/open-telemetry/opentelemetry-go-contrib/blob/f2fb9c8d5524abba85c87ef341d707c7a8173932/instrumentation/google.golang.org/grpc/otelgrpc/interceptor.go#L225 . That behavior was a bit surprising to me as I've always considered `CloseSend` optional as grpc only allows one-sided close from one side. The docs in `CloseSend` are not very specific but the docs for `RecvMsg` do say that `EOF` indicates completion of the stream. https://pkg.go.dev/google.golang.org/grpc#ClientStream

My suggestion would be for the client stream to finish always if EOF is received. I think `CloseSend` should be completely ignored. It can log an event but it doesn't indicate that stream is complete nor is it required for the stream to finish.

I'm willing to implement the required changes if the above makes sense.

**Comment by vadimberezniker** [comment]
Tõnis, I completely agree with you. We recently ran into massive goroutine leaks after adding gRPC instrumentation. 

I sent https://github.com/open-telemetry/opentelemetry-go-contrib/pull/836 to fix this. Let's see what the project approvers think.
