### ISSUE TITLE
Add instrumentation for github.com/astaxie/beego

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-contrib#82]
https://github.com/astaxie/beego

## Tasks

- [ ] code complete with tests passing
- [ ] `Dockerfile` with example app showing instrumentation
- [ ] documentation updated
- [ ] instrumentation added to the opentelemetry [registry](https://opentelemetry.io/registry/)

## Prior Art

- https://github.com/opentracing-contrib/beego

**Comment by reggiemcdonald** [comment]
Could the beego integration leverage the `net/http` integration that was merged in this week?

**Comment by MrAlias** [comment]
> Could the beego instrumentation leverage the `net/http` instrumentation that was merged in this week?

That seems to be what the OpenTracing project did: https://github.com/opentracing-contrib/beego/blob/master/middleware.go

Sounds like a good approach to me. :+1:

**Comment by reggiemcdonald** [comment]
@MrAlias go ahead and close this one! `opentelemetry.io` has been updated with a link to the beego integration

**Comment by MrAlias** [comment]
Awesome @reggiemcdonald!  Thanks for all the help :1st_place_medal:
