### ISSUE TITLE
Add instrumentation for Redis: github.com/go-redis/redis

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-contrib#83]
https://github.com/go-redis/redis

## Tasks

- [ ] code complete with tests passing
- [ ] `Dockerfile` with example app showing instrumentation
- [ ] documentation updated
- [ ] instrumentation added to the opentelemetry [registry](https://opentelemetry.io/registry/)

## Prior Art

- https://github.com/opentracing-contrib/goredis
- https://github.com/DataDog/dd-trace-go/tree/v1/contrib/go-redis/redis
- https://github.com/opencensus-integrations/redis

**Comment by reggiemcdonald** [comment]
@MrAlias could @TigerHe7 and myself take this one?

**Comment by MrAlias** [comment]
@reggiemcdonald @TigerHe7 all yours :smile:

**Comment by TigerHe7** [comment]
Thanks @MrAlias, could you assign me as well?

**Comment by MrAlias** [comment]
> Thanks @MrAlias, could you assign me as well?

done :+1:

**Comment by TigerHe7** [comment]
@MrAlias Do you know if there's a particular version of Redis we should be building this for?

**Comment by MrAlias** [comment]
@TigerHe7 I was thinking just the latest stable. At least to start with.

I think it's up to you both at this point to make the final decision of which versions to support. My only ask will be to document that support in some form of the documentation.

**Comment by reggiemcdonald** [comment]
You can find our initial PR [here](https://github.com/go-redis/redis/pull/1398)

**Comment by MrAlias** [comment]
This instrumentation was added to the go-redis library directly.
