### ISSUE TITLE
gRPC: provide the ability to set additional attributes for the generated spans

### ISSUE THREAD

**Issue by vadimberezniker** [open-telemetry/opentelemetry-go-contrib#838]
Our use case is as follows.
We implement a third-party API (Bazel Remote Execution) and most of the requests have a well known identifier called the invocation ID. I would like to add the invocation ID to the generated spans so that it's easy to find traces by invocation ID.

I patched our version of opentelemetry-go-contrib: 
https://github.com/open-telemetry/opentelemetry-go-contrib/compare/main...vadimberezniker:context_hook?expand=1

My questions are:
(1) Is it already somehow possible to accomplish this without modifying the instrumentation code?
(2) Are you interested in this patch?

**Comment by vadimberezniker** [comment]
Figured out how to do it without modifying the instrumentation code and super simple. 
Add another interceptor that retrieves the current Spans and adds an attribute.
```
span := trace.SpanFromContext(ctx)
span.SetAttributes(...)
```

**Comment by Aneurysm9** [comment]
> Figured out how to do it without modifying the instrumentation code and it's super simple.
> Add another interceptor that retrieves the current Spans and adds an attribute.
> 
> ```
> span := trace.SpanFromContext(ctx)
> span.SetAttributes(...)
> ```

Heh, I was going to suggest this but I assumed you were looking for a more generic approach.  I don't do much (read anything) with gRPC so I assumed there was a complication I was missing.  Glad you've come to a working solution!
