### ISSUE TITLE
Add instrumentation for go.uber.org/zap

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-contrib#84]
https://github.com/uber-go/zap

## Tasks

- [ ] code complete with tests passing
- [ ] `Dockerfile` with example app showing instrumentation
- [ ] documentation updated
- [ ] instrumentation added to the opentelemetry [registry](https://opentelemetry.io/registry/)

## Prior Art

- https://github.com/opentracing-contrib/go-zap

**Comment by dstdfx** [comment]
@MrAlias would be glad to start working on this one

**Comment by marcellodesales** [comment]
@dstdfx is your WIP working? I don't see any instructions, documentation, etc on this... I'd love to contribute if that's possible... We are in need of such integration... Thank you!

**Comment by dstdfx** [comment]
> @dstdfx is your WIP working? I don't see any instructions, documentation, etc on this... I'd love to contribute if that's possible... We are in need of such integration... Thank you!

It's just a stub in PR but I'm planning to fill this up on the week

**Comment by marcellodesales** [comment]
@dstdfx I will be up on the weekend in case there's anything I can help to test

**Comment by Mistic92** [comment]
Hi, any update?:)

**Comment by jasondeutsch** [comment]
I wrote an update of the _prior art_ for a project. I can submit a PR in a day or so.
