### ISSUE TITLE
Unify Configuration and Initialization

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-contrib#851]
## Why

This is a "clone" of https://github.com/open-telemetry/opentelemetry-go/issues/536 so that we can track adherence to https://github.com/open-telemetry/opentelemetry-go/blob/main/CONTRIBUTING.md#configuration

## What

Modules compliance table:

| Module | Compliant | Review date |
| --- | ---| --- |
| . | ✔️ | 2021-07-06 |
| ./detectors/aws | ✔️ | 2021-07-06 |
| ./detectors/aws/ecs | ✔️ | 2021-07-06 |
| ./detectors/aws/eks | ✔️ | 2021-07-06 |
| ./detectors/gcp | ✔️ | 2021-07-06 |
| ./exporters/metric/cortex | ❌ ❓   | 2021-07-06 |
| ./exporters/metric/cortex/utils | ❌ ❓ | 2021-07-06 |
| ./exporters/metric/datadog | ❌ ❓ | 2021-07-06 |
| ./exporters/metric/dogstatsd | ❌ ❓ | 2021-07-06 |
| ./instrumentation/github.com/Shopify/sarama/otelsarama |❌ https://github.com/open-telemetry/opentelemetry-go-contrib/pull/852 ⌛  | 2021-07-06 |
| ./instrumentation/github.com/astaxie/beego/otelbeego |❌ https://github.com/open-telemetry/opentelemetry-go-contrib/pull/853 ⌛ | 2021-07-06 |
| ./instrumentation/github.com/aws/aws-sdk-go-v2/otelaws |❌ https://github.com/open-telemetry/opentelemetry-go-contrib/pull/854 ⌛  | 2021-07-06 |
| ./instrumentation/github.com/bradfitz/gomemcache/memcache/otelmemcache |❌ https://github.com/open-telemetry/opentelemetry-go-contrib/pull/855 ⌛ | 2021-07-06 |
| ./instrumentation/github.com/emicklei/go-restful/otelrestful |❌ https://github.com/open-telemetry/opentelemetry-go-contrib/pull/856 ⌛ | 2021-07-06 |
| ./instrumentation/github.com/gin-gonic/gin/otelgin |❌ https://github.com/open-telemetry/opentelemetry-go-contrib/pull/857 ⌛ | 2021-07-06 |
| ./instrumentation/github.com/go-kit/kit/otelkit |❌ https://github.com/open-telemetry/opentelemetry-go-contrib/pull/858 ⌛ | 2021-07-06 |
| ./instrumentation/github.com/gocql/gocql/otelgocql |❌ https://github.com/open-telemetry/opentelemetry-go-contrib/pull/859 ⌛ | 2021-07-06 |
| ./instrumentation/github.com/gorilla/mux/otelmux | ❌ https://github.com/open-telemetry/opentelemetry-go-contrib/pull/860 ⌛  | 2021-07-06 |
| ./instrumentation/github.com/labstack/echo/otelecho |❌ https://github.com/open-telemetry/opentelemetry-go-contrib/pull/861 ⌛   | 2021-07-06 |
| ./instrumentation/go.mongodb.org/mongo-driver/mongo/otelmongo |❌ https://github.com/open-telemetry/opentelemetry-go-contrib/pull/862 ⌛  | 2021-07-06 |
| ./instrumentation/google.golang.org/grpc/otelgrpc |❌ https://github.com/open-telemetry/opentelemetry-go-contrib/pull/863 ⌛  | 2021-07-06 |
| ./instrumentation/gopkg.in/macaron.v1/otelmacaron |❌ https://github.com/open-telemetry/opentelemetry-go-contrib/pull/864 ⌛  | 2021-07-06 |
| ./instrumentation/host |❌ https://github.com/open-telemetry/opentelemetry-go-contrib/pull/865 ⌛  | 2021-07-06 |
| ./instrumentation/net/http/httptrace/otelhttptrace |❌ https://github.com/open-telemetry/opentelemetry-go-contrib/pull/866 ⌛  | 2021-07-06 |
| ./instrumentation/net/http/otelhttp | ❌ https://github.com/open-telemetry/opentelemetry-go-contrib/pull/750 https://github.com/open-telemetry/opentelemetry-go-contrib/pull/869 ⌛  | 2021-07-08 |
| ./instrumentation/runtime |❌ https://github.com/open-telemetry/opentelemetry-go-contrib/pull/867 ⌛  | 2021-07-06 |
| ./propagators | ⚠️ ❌ https://github.com/open-telemetry/opentelemetry-go-contrib/pull/868 ⌛ |  2021-07-06 |
| ./propagators/aws | ✔️ | 2021-07-06 |
| ./propagators/opencensus | ✔️ | 2021-07-06 |
| ./tools | ✔️ | 2021-07-06 |

**Comment by pellared** [comment]
@ercl Do you want to take over the `exporters/metric/cortex` part?

**Comment by pellared** [comment]
Is there anyone who wants to take care of `exporters/metric/datadog` and `exporters/metric/dogstatsd`?

**Comment by pellared** [comment]
During the SIG meeting, we agreed that we should also create a module for each propagator package.

**Comment by lastchiliarch** [comment]
> Is there anyone who wants to take care of `exporters/metric/datadog` and `exporters/metric/dogstatsd`?

I'd like to have a try.
