### ISSUE TITLE
Add instrumentation for Kafka: github.com/Shopify/sarama

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-contrib#87]
https://github.com/Shopify/sarama

## Tasks

- [ ] code complete with tests passing
- [ ] `Dockerfile` with example app showing instrumentation
- [ ] documentation updated
- [ ] instrumentation added to the opentelemetry [registry](https://opentelemetry.io/registry/)

## Prior Art

- https://github.com/DataDog/dd-trace-go/tree/v1/contrib/Shopify/sarama

**Comment by XSAM** [comment]
@MrAlias I'd like to take this up.
