### ISSUE TITLE
otelhttptrace: Add Options for customizing Spans

### ISSUE THREAD

**Issue by clly** [open-telemetry/opentelemetry-go-contrib#949]
There is no way to customize any of the spans that are emitted by otelhttptrace. We could implement 2 Options in otelhttptrace that would allow that customization:
1. WithSpanOptions
2. WithTracerProvider

These Options exist in otelhttp and are currently unimplemented in otelhttptrace and would provide that functionality.

**Comment by seh** [comment]
See #1105 and #1128.

**Comment by clly** [comment]
LGTM
